# -*- coding: utf-8 -*-
"""Module 11 (talking to AI) + the capstone project."""

# ---- module 11: speaking with AI. Same shape as the other modules (t/d/w) ----
AI_MODULE = {
 "id": "ai", "icon": "✦",
 "title": {"en": "Talking to AI", "he": "לדבר עם AI"},
 "blurb": {"en": "The other half of your job now. Treat it as an engineer, not an oracle.",
           "he": "החצי השני של העבודה שלך עכשיו. תתייחס אליו כמהנדס, לא כאורקל."},
 "terms": [
  {"t": {"en": "Context window", "he": "חלון הקשר"},
   "d": {"en": "Everything the model can see at once: your prompt, the files you pasted, the conversation so far. It is finite.",
         "he": "כל מה שהמודל רואה בבת אחת: הפרומפט שלך, הקבצים שהדבקת, השיחה עד כה. הוא סופי."},
   "w": {"en": "The model is not forgetting on purpose. Anything outside the window never existed for it.",
         "he": "המודל לא שוכח בכוונה. כל מה שמחוץ לחלון מעולם לא היה קיים מבחינתו."}},
  {"t": {"en": "Specificity beats politeness", "he": "דיוק מנצח נימוס"},
   "d": {"en": "Constraints, file names, versions and examples change the output. Please and thank you do not.",
         "he": "אילוצים, שמות קבצים, גרסאות ודוגמאות משנים את הפלט. בבקשה ותודה לא."},
   "w": {"en": "Fix the app is a wish. Fix the 500 on POST /orders when quantity is 0, in api/orders.ts is a task.",
         "he": "תתקן את האפליקציה זו משאלה. תתקן את ה-500 ב-POST /orders כשהכמות 0, בקובץ api/orders.ts זו משימה."}},
  {"t": {"en": "State the shape of the answer", "he": "תגדיר את צורת התשובה"},
   "d": {"en": "Say what form you want back: a diff, one file, a list of options, a table, three sentences.",
         "he": "תגיד באיזו צורה אתה רוצה את התשובה: diff, קובץ אחד, רשימת אפשרויות, טבלה, שלושה משפטים."},
   "w": {"en": "Unspecified shape gets you an essay wrapped around the two lines you needed.",
         "he": "צורה לא מוגדרת מחזירה לך חיבור שעוטף את שתי השורות שהיית צריך."}},
  {"t": {"en": "Constrain the blast radius", "he": "תגביל את רדיוס הפגיעה"},
   "d": {"en": "Name the files it may touch and the ones it must not. Ask for the smallest change that works.",
         "he": "תציין אילו קבצים מותר לו לגעת בהם ואילו אסור. תבקש את השינוי הקטן ביותר שעובד."},
   "w": {"en": "Without a boundary it will helpfully refactor four files you did not ask about, and one of them mattered.",
         "he": "בלי גבול הוא ישכתב בעזרה רבה ארבעה קבצים שלא ביקשת, ואחד מהם היה חשוב."}},
  {"t": {"en": "Ask for the trade-off first", "he": "תבקש קודם את ההתלבטות"},
   "d": {"en": "Before code, ask for two or three approaches with their costs. Then choose, then ask for code.",
         "he": "לפני קוד, תבקש שתיים-שלוש גישות עם המחירים שלהן. אז תבחר, ואז תבקש קוד."},
   "w": {"en": "Models are eager. Asked for code, they give code — even when the right answer was do not build this.",
         "he": "מודלים להוטים. כשמבקשים קוד, הם נותנים קוד — גם כשהתשובה הנכונה הייתה אל תבנה את זה."}},
  {"t": {"en": "Hallucination", "he": "הזיה"},
   "d": {"en": "Confidently stated output that is wrong: a function that does not exist, a flag that was never added, an API shaped the way it should be rather than the way it is.",
         "he": "פלט שנאמר בביטחון ואינו נכון: פונקציה שלא קיימת, דגל שמעולם לא נוסף, API בצורה שהוא היה אמור להיות ולא כפי שהוא."},
   "w": {"en": "Confidence carries no information about correctness. Library names, version numbers and config keys are the highest-risk answers — verify those against real docs.",
         "he": "ביטחון לא נושא שום מידע על נכונות. שמות ספריות, מספרי גרסאות ומפתחות קונפיגורציה הם התשובות המסוכנות ביותר — תאמת אותן מול תיעוד אמיתי."}},
  {"t": {"en": "Make it verify itself", "he": "תגרום לו לאמת את עצמו"},
   "d": {"en": "Ask for the failing test first, or for the command that proves the fix, or for the three inputs that would break it.",
         "he": "תבקש קודם את הבדיקה שנכשלת, או את הפקודה שמוכיחה את התיקון, או את שלושת הקלטים שישברו אותו."},
   "w": {"en": "A claim you can run is worth more than a paragraph explaining why it should work.",
         "he": "טענה שאפשר להריץ שווה יותר מפסקה שמסבירה למה זה אמור לעבוד."}},
  {"t": {"en": "Small steps over one big ask", "he": "צעדים קטנים במקום בקשה אחת גדולה"},
   "d": {"en": "Several reviewed changes beat one enormous generated change you cannot read.",
         "he": "כמה שינויים שנסקרו עדיפים על שינוי ענק אחד שאתה לא מסוגל לקרוא."},
   "w": {"en": "You can only catch a mistake inside a diff you are willing to read. Set the size accordingly.",
         "he": "אתה יכול לתפוס טעות רק בתוך diff שאתה מוכן לקרוא. תקבע את הגודל בהתאם."}},
  {"t": {"en": "Read the diff", "he": "תקרא את ה-diff"},
   "d": {"en": "Before accepting anything, look at what actually changed — not at the summary of what changed.",
         "he": "לפני שאתה מקבל משהו, תסתכל על מה שבאמת השתנה — לא על הסיכום של מה שהשתנה."},
   "w": {"en": "This single habit separates people who ship with AI from people who are shipped by it.",
         "he": "ההרגל הבודד הזה מפריד בין אנשים שמשחררים בעזרת AI לבין אנשים שה-AI משחרר אותם."}},
  {"t": {"en": "Prompt injection", "he": "הזרקת פרומפט"},
   "d": {"en": "Text the model reads — from a web page, a file, an issue, a dependency — that contains instructions aimed at it.",
         "he": "טקסט שהמודל קורא — מדף אינטרנט, קובץ, תקלה, תלות — שמכיל הוראות שמכוונות אליו."},
   "w": {"en": "It is the injection bug from module 08 in a new suit: data being treated as instructions. Anything an agent reads is data, never orders.",
         "he": "זה באג ההזרקה ממודול 08 בחליפה חדשה: נתונים שמטופלים כהוראות. כל מה שסוכן קורא הוא נתונים, אף פעם לא פקודות."}},
 ]
}

AI_DETAIL = {
"Context window": {
 "en": "A model has no memory between messages other than what is placed in front of it. A long conversation is re-read from the start every single turn, and when it no longer fits, the oldest parts fall away silently.\n\nThis explains most mysterious behaviour. A rule you established twenty messages ago stops being followed not because the model changed its mind, but because that rule is no longer in the room. Restating the important constraints, or starting fresh with a tight summary, fixes more than rephrasing ever will.",
 "he": "למודל אין זיכרון בין הודעות מעבר למה שמונח לפניו. שיחה ארוכה נקראת מחדש מההתחלה בכל תור, וכשהיא כבר לא נכנסת, החלקים הישנים ביותר נושרים בשקט.\n\nזה מסביר את רוב ההתנהגויות המסתוריות. חוק שקבעת לפני עשרים הודעות מפסיק להישמר לא כי המודל שינה את דעתו, אלא כי החוק הזה כבר לא בחדר. חזרה על האילוצים החשובים, או התחלה מחדש עם סיכום הדוק, מתקנת יותר מכל ניסוח מחדש."},
"Specificity beats politeness": {
 "en": "A model fills every gap you leave with the most statistically ordinary choice. Vagueness does not produce a question back — it produces a confident guess.\n\nSo the useful prompt reads like a ticket: what is broken, where, what you already tried, what must not change, and how you will know it worked. Almost all of the improvement people attribute to prompt tricks is really just this.",
 "he": "מודל ממלא כל חור שאתה משאיר בבחירה הסטטיסטית הרגילה ביותר. עמימות לא מייצרת שאלה חוזרת — היא מייצרת ניחוש בטוח בעצמו.\n\nאז הפרומפט המועיל נקרא כמו כרטיס עבודה: מה שבור, איפה, מה כבר ניסית, מה אסור שישתנה, ואיך תדע שזה עבד. כמעט כל השיפור שאנשים מייחסים לטריקים של פרומפטים הוא באמת רק זה."},
"State the shape of the answer": {
 "en": "Specifying the output format is the cheapest control you have. It reduces the surface you must read, makes two answers comparable, and quietly forces the model to commit rather than hedge.\n\nAsking for exactly three options is a real constraint. It prevents both the single overconfident answer and the exhausting list of twelve.",
 "he": "הגדרת פורמט הפלט היא השליטה הזולה ביותר שיש לך. היא מקטינה את המשטח שאתה צריך לקרוא, הופכת שתי תשובות להשוואות, ובשקט מכריחה את המודל להתחייב במקום לגדר.\n\nבקשה לשלוש אפשרויות בדיוק היא אילוץ אמיתי. היא מונעת גם את התשובה הבודדת הבטוחה מדי וגם את הרשימה המתישה של שתים-עשרה."},
"Constrain the blast radius": {
 "en": "An agent with file access will do what it believes is helpful, and helpful is a much broader category than correct. Unbounded, it will tidy, rename, upgrade and reorganise.\n\nTwo habits make this safe and cost nothing: work on a branch, and state the files in scope. Then the worst outcome is a change you throw away, not a change you have to find.",
 "he": "סוכן עם גישה לקבצים יעשה את מה שהוא מאמין שמועיל, ומועיל היא קטגוריה הרבה יותר רחבה מנכון. בלי גבולות, הוא יסדר, ישנה שמות, ישדרג ויארגן מחדש.\n\nשני הרגלים הופכים את זה לבטוח ולא עולים כלום: לעבוד על ענף, ולציין את הקבצים בתחום. אז התוצאה הגרועה ביותר היא שינוי שאתה זורק, לא שינוי שאתה צריך לחפש."},
"Ask for the trade-off first": {
 "en": "The most valuable thing a model can give you is not code, it is a map of the decision — what the options are, what each costs, and which one fails badly.\n\nThis also protects you from the failure mode unique to fluent assistants: a plausible implementation of the wrong idea. Code is easy to produce and expensive to unpick, so put the judgement step before it, not after.",
 "he": "הדבר הכי בעל ערך שמודל יכול לתת לך הוא לא קוד, אלא מפה של ההחלטה — מה האפשרויות, מה כל אחת עולה, ואיזו נכשלת קשה.\n\nזה גם מגן עליך ממצב הכשל הייחודי לעוזרים רהוטים: מימוש סביר של הרעיון הלא נכון. קוד קל לייצר ויקר לפרום, אז שים את שלב השיפוט לפניו, לא אחריו."},
"Hallucination": {
 "en": "A model predicts plausible text. Plausible and true overlap most of the time, which is exactly what makes the gap dangerous — the wrong answer arrives in the same tone as the right one.\n\nThe risk is highest wherever the truth is arbitrary rather than derivable: exact flag names, version numbers, pricing, quotas, API field names. Reasoning it can do; remembering a specific string it cannot be trusted on. Check those in the real documentation, every time.",
 "he": "מודל מנבא טקסט סביר. סביר ונכון חופפים רוב הזמן, וזה בדיוק מה שהופך את הפער למסוכן — התשובה השגויה מגיעה באותו טון כמו הנכונה.\n\nהסיכון גבוה ביותר בכל מקום שבו האמת שרירותית ולא נגזרת: שמות דגלים מדויקים, מספרי גרסאות, תמחור, מכסות, שמות שדות ב-API. להסיק הוא יכול; לזכור מחרוזת ספציפית אי אפשר לסמוך עליו. תבדוק את אלה בתיעוד האמיתי, בכל פעם."},
"Make it verify itself": {
 "en": "Shift the burden of proof onto something executable. A failing test written before the fix turns a claim into an experiment with a visible result.\n\nIt also improves the fix. Writing the test forces the problem to be stated precisely, and a precisely stated problem is most of the way to being solved — by a person or a model.",
 "he": "העבר את נטל ההוכחה למשהו שאפשר להריץ. בדיקה שנכשלת ונכתבה לפני התיקון הופכת טענה לניסוי עם תוצאה נראית.\n\nזה גם משפר את התיקון. כתיבת הבדיקה מכריחה לנסח את הבעיה בדיוק, ובעיה מנוסחת בדיוק היא רוב הדרך לפתרון — על ידי אדם או מודל."},
"Small steps over one big ask": {
 "en": "Review capacity, not generation capacity, is the real limit. A model can produce more correct-looking code per minute than any person can meaningfully check.\n\nSo the batch size should be set by what you can actually read, not by what it can produce. Working in small reviewed steps also keeps the context focused, which makes each answer better than the last.",
 "he": "יכולת הסקירה, לא יכולת הייצור, היא המגבלה האמיתית. מודל יכול לייצר יותר קוד שנראה נכון בדקה ממה שאדם יכול לבדוק באופן משמעותי.\n\nאז גודל המנה צריך להיקבע לפי מה שאתה באמת יכול לקרוא, לא לפי מה שהוא יכול לייצר. עבודה בצעדים קטנים שנסקרים גם שומרת את ההקשר ממוקד, מה שהופך כל תשובה לטובה מקודמתה."},
"Read the diff": {
 "en": "A summary is written by the same system that made the change, and it describes intent rather than result. The diff is the result.\n\nThree things to look for every time: something deleted that you did not ask to delete, a new dependency, and a changed default. Those three account for most of the damage that gets through.",
 "he": "סיכום נכתב על ידי אותה מערכת שעשתה את השינוי, והוא מתאר כוונה ולא תוצאה. ה-diff הוא התוצאה.\n\nשלושה דברים לחפש בכל פעם: משהו שנמחק שלא ביקשת למחוק, תלות חדשה, וברירת מחדל שהשתנתה. שלושת אלה אחראים לרוב הנזק שעובר."},
"Prompt injection": {
 "en": "When a model can read the outside world — a page, a repository, a ticket, an email — anything it reads may contain text written to steer it. The model has no reliable way to tell a document apart from an instruction, because both are just text.\n\nTreat it exactly like the injection problem in module 08. Content that arrives from outside is data, and the defences are the same in spirit: least privilege, a human confirmation before anything irreversible, and never letting fetched content authorise an action.",
 "he": "כשמודל יכול לקרוא את העולם החיצוני — דף, ריפוזיטורי, תקלה, מייל — כל מה שהוא קורא עלול להכיל טקסט שנכתב כדי לכוון אותו. למודל אין דרך אמינה להבחין בין מסמך להוראה, כי שניהם פשוט טקסט.\n\nתתייחס לזה בדיוק כמו לבעיית ההזרקה במודול 08. תוכן שמגיע מבחוץ הוא נתונים, וההגנות זהות ברוחן: הרשאות מינימליות, אישור אנושי לפני כל דבר בלתי הפיך, ואף פעם לא לתת לתוכן שנשלף להרשות פעולה."},
}

# ---- capstone: 0 -> deployed, Docker, 2 instances on AWS, managed Redis ----
# Prompts stay in English on purpose: that is the language you will paste.
PROJECT = {
 "id": "project", "icon": "▶",
 "title": {"en": "Final Project", "he": "פרויקט מסכם"},
 "blurb": {"en": "From an empty folder to a real deployment: Docker, two running instances behind a load balancer, managed Postgres and managed Redis on AWS. Every step has a prompt to paste.",
           "he": "מתיקייה ריקה לפריסה אמיתית: Docker, שני מופעים רצים מאחורי מאזן עומסים, Postgres מנוהל ו-Redis מנוהל ב-AWS. לכל שלב יש פרומפט להדביק."},
 "warn": {"en": "This project creates real AWS resources that cost real money — roughly $50-90/month if left running. Step 13 tears it all down. Do that the same day unless you are keeping it.",
          "he": "הפרויקט הזה יוצר משאבי AWS אמיתיים שעולים כסף אמיתי — בערך 50-90 דולר לחודש אם משאירים אותם. שלב 13 מוחק הכל. תעשה את זה באותו יום, אלא אם אתה שומר את זה."},
 "steps": [
  {"n": 1,
   "title": {"en": "Decide what you are building", "he": "תחליט מה אתה בונה"},
   "goal": {"en": "One page of plain text: what it does, who for, what it explicitly will not do. No code yet.",
            "he": "עמוד אחד של טקסט פשוט: מה זה עושה, למי, ומה זה במפורש לא יעשה. עדיין בלי קוד."},
   "uses": ["Ask for the trade-off first", "Technical debt"],
   "why": {"en": "Every later decision — database shape, caching, scaling — is answerable only if this page exists. Skipping it is why projects get rewritten.",
           "he": "כל החלטה מאוחרת יותר — מבנה בסיס נתונים, מטמון, סקייל — ניתנת למענה רק אם העמוד הזה קיים. דילוג עליו הוא הסיבה שפרויקטים נכתבים מחדש."},
   "prompt": "I want to build a small web app: <describe it in two sentences>. Before any code, help me write a one-page spec.\n\nGive me: (1) the single core user action the whole product exists to support, (2) the 3-5 smallest features needed for that action to work end to end, (3) an explicit NON-goals list of things I will be tempted to add but should not build now, (4) the data I will need to store, described as plain nouns and their relationships, not as tables.\n\nThen tell me the two riskiest assumptions in this plan. Do not write code. Keep it under 400 words."},

  {"n": 2,
   "title": {"en": "Repo, runtime, first commit", "he": "ריפו, סביבת ריצה, קומיט ראשון"},
   "goal": {"en": "A git repo with a running hello-world server, a .gitignore, and a README that says how to start it.",
            "he": "ריפו git עם שרת hello-world שרץ, קובץ .gitignore, ו-README שמסביר איך להפעיל אותו."},
   "uses": ["Repository (repo)", "Runtime", "Terminal / CLI", "Package manager"],
   "why": {"en": "The README is not paperwork. If you cannot write down how to start it, you do not yet have a reproducible project.",
           "he": "ה-README הוא לא ביורוקרטיה. אם אתה לא יכול לכתוב איך מפעילים את זה, עוד אין לך פרויקט שניתן לשחזור."},
   "prompt": "Set up a minimal TypeScript + Node.js (Express or Fastify) project in the current empty folder.\n\nRequirements: pin the Node version in a .nvmrc and in package.json engines; include a .gitignore that covers node_modules, .env and build output; one GET /health endpoint returning {status:\"ok\"}; an npm script for dev and one for start; a README with exactly the commands needed to clone, install and run.\n\nDo not add a frontend framework, a database, a logger library or Docker yet. Show me the file tree first and wait for my approval before writing files."},

  {"n": 3,
   "title": {"en": "Data model and Postgres", "he": "מודל נתונים ו-Postgres"},
   "goal": {"en": "A local Postgres via Docker Compose, a schema created by a migration, and one endpoint that reads and writes real rows.",
            "he": "Postgres מקומי דרך Docker Compose, סכמה שנוצרה על ידי מיגרציה, ונקודת קצה אחת שקוראת וכותבת שורות אמיתיות."},
   "uses": ["Database", "Schema", "Migration", "Index", "Transaction"],
   "why": {"en": "Starting with migrations from the first table is the difference between a project you can deploy and one you can only run locally.",
           "he": "התחלה עם מיגרציות כבר מהטבלה הראשונה היא ההבדל בין פרויקט שאפשר לפרוס לבין כזה שרץ רק מקומית."},
   "prompt": "Add PostgreSQL to my project.\n\n1. A docker-compose.yml running Postgres 16 locally with a named volume, port 5432, credentials read from .env (and add a committed .env.example).\n2. A migration tool (node-pg-migrate or Drizzle — recommend one and justify it in two sentences).\n3. The first migration creating the tables for this data model: <paste the nouns from step 1>. Include primary keys, NOT NULL where the field is genuinely required, foreign keys, created_at/updated_at, and an index on every column I will filter or sort by — tell me which ones those are and why.\n4. One endpoint that writes a row and one that reads it back.\n\nShow me the migration SQL and explain each index before applying anything."},

  {"n": 4,
   "title": {"en": "Auth", "he": "הזדהות"},
   "goal": {"en": "Sign up, log in, and one endpoint that only the owner of a resource can call.",
            "he": "הרשמה, התחברות, ונקודת קצה אחת שרק הבעלים של המשאב יכול לקרוא לה."},
   "uses": ["Authentication vs Authorization", "Hashing vs encryption", "Token / JWT", "Session & cookie", "Environment variables / secrets"],
   "why": {"en": "Authorization is where real breaches happen. Getting the owner check right on one endpoint teaches the pattern for all of them.",
           "he": "הרשאה היא המקום שבו קורות פריצות אמיתיות. לעשות נכון את בדיקת הבעלות בנקודת קצה אחת מלמדת את הדפוס לכולן."},
   "prompt": "Add authentication and authorization.\n\nUse argon2id (or bcrypt) for password hashing — never store or log the plaintext. Use httpOnly, Secure, SameSite=Lax session cookies backed by a server-side session, not a localStorage JWT, and explain that choice in two sentences.\n\nThen add one endpoint that returns a resource ONLY if the logged-in user owns it. Show me explicitly where the ownership check happens and prove it cannot be bypassed by changing the id in the request.\n\nFinally, list every secret this now needs, and add them to .env.example with placeholder values. Never put a real secret in a committed file."},

  {"n": 5,
   "title": {"en": "Add Redis as a cache", "he": "הוספת Redis כמטמון"},
   "goal": {"en": "Redis running locally in Compose, caching your slowest read with a TTL, and a measurement showing it worked.",
            "he": "Redis רץ מקומית ב-Compose, שומר במטמון את הקריאה האיטית ביותר עם TTL, ומדידה שמוכיחה שזה עבד."},
   "uses": ["Cache", "TTL", "Hit / Miss", "Redis / in-memory store", "Latency vs throughput"],
   "why": {"en": "Caching locally first means that when you swap in managed Redis at step 10, only the connection string changes.",
           "he": "מטמון מקומי קודם אומר שכשתחליף ל-Redis מנוהל בשלב 10, רק מחרוזת החיבור משתנה."},
   "prompt": "Add Redis to docker-compose and cache my most expensive read endpoint.\n\nRequirements: a single cache module wrapping get/set/delete so the rest of the code never touches the Redis client directly; an explicit TTL with a comment justifying the number; a cache key that includes every input that changes the result (tell me what those are for my endpoint); and the app must still work correctly with Redis completely down — degrade to hitting the database, do not 500.\n\nThen give me a short script that calls the endpoint 20 times and prints the timing, so I can see the hit rate effect. Tell me what number would mean my cache key is wrong."},

  {"n": 6,
   "title": {"en": "Tests that mean something", "he": "בדיקות עם משמעות"},
   "goal": {"en": "A handful of tests covering the auth rule, the cache fallback, and one real end-to-end path.",
            "he": "קומץ בדיקות שמכסות את חוק ההרשאה, את נפילת המטמון, ומסלול אמיתי אחד מקצה לקצה."},
   "uses": ["Make it verify itself", "Race condition", "Idempotency"],
   "why": {"en": "You need exactly the tests that would catch a bad AI-generated change. Coverage percentage is not the goal.",
           "he": "אתה צריך בדיוק את הבדיקות שיתפסו שינוי גרוע שה-AI ייצר. אחוז כיסוי הוא לא המטרה."},
   "prompt": "Write tests for the three things most likely to break silently in this project:\n\n1. The authorization rule — a user must NOT be able to read another user's resource by changing the id.\n2. The cache — with Redis unavailable the endpoint still returns correct data, and a second call within the TTL does not hit the database.\n3. One end-to-end happy path: sign up, create, read back.\n\nUse Vitest plus Testcontainers (or a compose-based test database) so tests run against real Postgres and Redis, not mocks — explain in two sentences why mocks would make test 2 worthless. Each test name must state the rule it protects."},

  {"n": 7,
   "title": {"en": "Dockerize the app", "he": "אריזת האפליקציה ב-Docker"},
   "goal": {"en": "A multi-stage Dockerfile producing a small image that runs as a non-root user, plus the whole stack up with one command.",
            "he": "Dockerfile רב-שלבי שמייצר דמות קטנה שרצה כמשתמש לא-root, ובנוסף כל הסטאק עולה בפקודה אחת."},
   "uses": ["Container / Docker", "Environment", "Environment variables / secrets", "Stateless"],
   "why": {"en": "This is the artifact AWS will run. If it works here and fails there, the difference is configuration, not code.",
           "he": "זו הדמות ש-AWS תריץ. אם היא עובדת כאן ונכשלת שם, ההבדל הוא קונפיגורציה, לא קוד."},
   "prompt": "Write a production Dockerfile for this app.\n\nRequirements: multi-stage build (deps, build, runtime); the runtime stage contains no dev dependencies and no source, only build output; run as a non-root user; a .dockerignore excluding node_modules, .git and .env; an explicit HEALTHCHECK hitting /health; and config read only from environment variables — no secrets baked into the image.\n\nThen update docker-compose.yml so `docker compose up` runs app + Postgres + Redis together. Tell me the final image size and the three biggest things contributing to it."},

  {"n": 8,
   "title": {"en": "CI: make the checks unskippable", "he": "CI: להפוך את הבדיקות לבלתי ניתנות לדילוג"},
   "goal": {"en": "On every push: install, typecheck, lint, test, and build the Docker image. Red means it does not ship.",
            "he": "בכל דחיפה: התקנה, בדיקת טיפוסים, לינט, בדיקות, ובניית דמות Docker. אדום אומר שזה לא יוצא."},
   "uses": ["CI/CD", "Deploy", "Read the diff"],
   "why": {"en": "This is the guardrail that makes AI-generated changes safe to accept quickly. Without it, review is the only defence and review gets tired.",
           "he": "זה המעקה שהופך שינויים שה-AI ייצר לבטוחים לקבלה מהירה. בלעדיו, סקירה היא ההגנה היחידה, וסקירה מתעייפת."},
   "prompt": "Create a GitHub Actions workflow that runs on every push and pull request.\n\nJobs: install with a cached lockfile, typecheck, lint, run the test suite against real Postgres and Redis service containers, then build the Docker image (build only, no push yet). Fail the workflow on any step failing. Pin action versions.\n\nAlso tell me which of these checks would NOT have caught a plausible bad change in my project, so I know what the pipeline does not protect me from."},

  {"n": 9,
   "title": {"en": "AWS groundwork: account, network, registry", "he": "תשתית AWS: חשבון, רשת, מאגר דמויות"},
   "goal": {"en": "A VPC with public and private subnets, security groups, and your image pushed to ECR.",
            "he": "VPC עם תת-רשתות ציבוריות ופרטיות, קבוצות אבטחה, והדמות שלך נדחפה ל-ECR."},
   "uses": ["The cloud", "AWS / Azure / GCP", "localhost & port", "Single point of failure"],
   "why": {"en": "Subnets and security groups are the whole AWS security model. Everything after this depends on getting this layer right.",
           "he": "תת-רשתות וקבוצות אבטחה הן כל מודל האבטחה של AWS. כל מה שאחרי זה תלוי בכך שהשכבה הזו נכונה."},
   "prompt": "Walk me through the AWS groundwork for deploying this container. I am a beginner — explain each resource in one sentence before creating it.\n\nI need: a VPC across two availability zones with public subnets (for the load balancer) and private subnets (for the app, the database and Redis); security groups where the load balancer accepts 443 from the internet, the app accepts traffic ONLY from the load balancer, and Postgres and Redis accept traffic ONLY from the app; and an ECR repository with my image pushed to it.\n\nGive me this as Terraform, and before the code, list every resource with its rough monthly cost. Flag anything that costs money while idle — especially NAT gateways."},

  {"n": 10,
   "title": {"en": "Managed Postgres and managed Redis", "he": "Postgres מנוהל ו-Redis מנוהל"},
   "goal": {"en": "RDS Postgres and ElastiCache Redis in the private subnets, reachable only by the app.",
            "he": "RDS Postgres ו-ElastiCache Redis בתת-רשתות הפרטיות, נגישים רק לאפליקציה."},
   "uses": ["Database", "Redis / in-memory store", "Environment variables / secrets", "Single point of failure"],
   "why": {"en": "Managed means backups, patching and failover are someone else's job. That is what you are paying for — not the server.",
           "he": "מנוהל אומר שגיבויים, עדכונים והחלפה בכשל הם העבודה של מישהו אחר. זה מה שאתה משלם עליו — לא על השרת."},
   "prompt": "Add managed data stores to my Terraform.\n\n1. RDS PostgreSQL in the private subnets: smallest reasonable instance, storage encrypted, automated backups with a 7-day retention, NOT publicly accessible, credentials generated and stored in AWS Secrets Manager — never in the Terraform code or state output.\n2. ElastiCache for Redis in the private subnets, encryption in transit on, reachable only from the app security group.\n\nThen show me exactly which environment variables my container needs and how it reads the database password from Secrets Manager at startup.\n\nBefore applying: tell me the monthly cost of both, and what specifically breaks if the Redis node is replaced while my app is running."},

  {"n": 11,
   "title": {"en": "Two instances behind a load balancer", "he": "שני מופעים מאחורי מאזן עומסים"},
   "goal": {"en": "ECS Fargate running two tasks of your image, an Application Load Balancer in front, HTTPS with a real certificate.",
            "he": "ECS Fargate שמריץ שני מופעים של הדמות שלך, Application Load Balancer מלפנים, HTTPS עם תעודה אמיתית."},
   "uses": ["Scaling up vs out", "Load balancer", "Stateless", "HTTPS / TLS", "Deploy"],
   "why": {"en": "Two instances is where every assumption about local memory breaks. If anything still lives in the process, you will find out here.",
           "he": "שני מופעים הם המקום שבו כל הנחה לגבי זיכרון מקומי נשברת. אם משהו עדיין חי בתהליך, תגלה את זה כאן."},
   "prompt": "Deploy my container to ECS Fargate with exactly 2 tasks running across 2 availability zones.\n\nInclude: an Application Load Balancer in the public subnets with an ACM certificate and HTTP redirecting to HTTPS; a target group whose health check hits /health with sensible thresholds — explain each number; a rolling deployment that never drops below 2 healthy tasks; and the database password injected from Secrets Manager, not as a plain environment variable.\n\nThen give me a checklist of everything in my code that would break with 2 instances instead of 1 — in-memory state, local file writes, scheduled jobs that must run once, websocket assumptions — and tell me which ones my project actually has."},

  {"n": 12,
   "title": {"en": "Logs, metrics, and one alert", "he": "לוגים, מטריקות והתראה אחת"},
   "goal": {"en": "Structured logs in CloudWatch, the four numbers that matter on a dashboard, and one alarm that emails you.",
            "he": "לוגים מובנים ב-CloudWatch, ארבעת המספרים שחשובים בדשבורד, והתראה אחת ששולחת לך מייל."},
   "uses": ["Logs & monitoring", "Latency vs throughput", "Status codes", "Rate limiting"],
   "why": {"en": "Without this, your first real outage is discovered by a user. One working alert is worth more than a beautiful dashboard nobody opens.",
           "he": "בלי זה, התקלה האמיתית הראשונה שלך מתגלה על ידי משתמש. התראה אחת שעובדת שווה יותר מדשבורד יפה שאף אחד לא פותח."},
   "prompt": "Add observability to my ECS service.\n\n1. Structured JSON logging with a request id propagated through every log line for a request, shipped to CloudWatch Logs with a retention period (not forever — tell me the cost difference).\n2. A dashboard with exactly four things: p95 latency, error rate (5xx), request count, and healthy task count. Justify why these four and not others.\n3. One CloudWatch alarm that emails me via SNS when the 5xx rate exceeds a threshold for 5 minutes. Tell me what threshold to start with and why an alarm that fires too often is worse than none.\n\nAlso: what is the single most useful thing to log in MY app that a generic setup would miss?"},

  {"n": 13,
   "title": {"en": "Cost check, then tear it down", "he": "בדיקת עלויות, ואז מחיקה"},
   "goal": {"en": "Know what this costs per month, set a budget alert, then destroy everything you are not keeping.",
            "he": "לדעת כמה זה עולה לחודש, להגדיר התראת תקציב, ואז למחוק כל מה שאתה לא שומר."},
   "uses": ["The cloud", "Deploy", "Technical debt"],
   "why": {"en": "Knowing how to remove infrastructure is as much a skill as creating it, and it is the one nobody teaches.",
           "he": "לדעת איך להסיר תשתית היא מיומנות בדיוק כמו ליצור אותה, וזו היחידה שאף אחד לא מלמד."},
   "prompt": "Two things.\n\nFirst: itemise the monthly cost of everything I created — Fargate tasks, ALB, RDS, ElastiCache, NAT gateway, CloudWatch logs, data transfer. Show which line items cost money even with zero traffic, and set up an AWS Budgets alert that emails me if the month is on track to exceed $X.\n\nSecond: give me the exact command to destroy all of it, tell me what `terraform destroy` will NOT remove (ECR images, CloudWatch log groups, Secrets Manager secrets in their deletion window, S3 buckets with objects), and give me the commands to clean those up too. Then tell me how to verify in the console that nothing is still billing."},
 ]
}
