# -*- coding: utf-8 -*-
"""Deepening pass 4: Cloud & Shipping, Scale & Architecture.

DETAIL_FIX   - replaces the deep-dive text for every term in these two modules.
EXAMPLES_FIX - adds (or upgrades) the concrete example shown on the slide.
HE_FIX       - Hebrew corrections for term name / definition / why.
"""

DETAIL_FIX = {

# ================= Cloud & Shipping =================

"The cloud": {
 "en": "The cloud is a rental agreement with a meter attached. Nothing about it is magical: the machines are real, they sit in a warehouse in Dublin or Virginia, and a technician racked them. What changed is the unit of purchase. You buy a minute of a machine instead of a machine, and you order it through an API instead of a purchase order. That turns capacity from a procurement decision that took six weeks into one line of configuration, which is genuinely transformative. It also turns every line of configuration into a recurring cost, which is the part nobody plans for. Capacity you never use still runs, and the meter does not care whether a single person visited your site.\n\nA two-person team put a demo API behind a managed load balancer, with a NAT gateway so the private subnet could reach the internet, and a small Postgres. They budgeted for the compute: fourteen dollars a month, and the compute really was fourteen dollars. The first invoice was three hundred and forty. The load balancer bills about eighteen dollars a month whether anyone calls it or not. The NAT gateway bills a flat thirty-three plus four and a half cents per gigabyte processed, and a nightly sync job was pushing four hundred gigabytes out to a third-party API. A GPU instance left running after a weekend experiment added five hundred dollars the following month at roughly a dollar an hour. Nothing was hacked. Everything they created was still there, doing exactly what they had asked for.\n\nAn agent will cheerfully provision infrastructure it learned from a tutorial written by someone with a corporate budget, and it will not mention the monthly cost, because nothing in the code says what anything costs. The question to ask before you apply anything is: what does this bill if zero users show up? Set a billing alert on day one, before the first deploy, not after the first invoice. And when you delete an experiment, delete it in the console, service by service — the compute is the cheap part, and the things left behind are never the things you remember creating.",
 "he": "הענן הוא הסכם שכירות עם מונה. אין בו שום דבר קסום: המכונות אמיתיות, הן יושבות במחסן בדבלין או בווירג׳יניה, וטכנאי הרכיב אותן במדף. מה שהשתנה זו יחידת הקנייה. אתה קונה דקה של מכונה במקום מכונה, ומזמין אותה דרך API במקום דרך הזמנת רכש. זה הופך קיבולת מהחלטת רכש שלקחה שישה שבועות לשורת קונפיגורציה אחת, וזה באמת משנה הכל. זה גם הופך כל שורת קונפיגורציה לעלות חוזרת, וזה החלק שאף אחד לא מתכנן. קיבולת שלא השתמשת בה עדיין רצה, ולמונה לא אכפת אם בן אדם אחד נכנס לאתר.\n\nצוות של שניים שם API של דמו מאחורי מאזן עומסים מנוהל, עם NAT gateway כדי שהרשת הפרטית תגיע לאינטרנט, ועוד Postgres קטן. הם תקצבו את הקומפיוט: ארבעה עשר דולר בחודש, והקומפיוט באמת עלה ארבעה עשר דולר. החשבונית הראשונה הייתה שלוש מאות וארבעים. מאזן העומסים מחייב בערך שמונה עשר דולר בחודש בין אם קוראים לו ובין אם לא. ה-NAT gateway מחייב שלושים ושלושה דולר קבועים ועוד ארבע וחצי סנט לכל ג׳יגה שעובר, וג׳וב סנכרון לילי דחף ארבע מאות ג׳יגה החוצה ל-API חיצוני. מכונת GPU שנשארה דולקת אחרי ניסוי של סוף שבוע הוסיפה חמש מאות דולר בחודש שאחרי, בערך דולר לשעה. אף אחד לא נפרץ. כל מה שהם יצרו עדיין היה שם, ועשה בדיוק את מה שביקשו ממנו.\n\nסוכן AI ירים לך בשמחה תשתית שלמד מטוטוריאל שכתב מישהו עם תקציב של חברה, והוא לא יזכיר את העלות החודשית, כי שום דבר בקוד לא אומר כמה משהו עולה. השאלה לשאול לפני שאתה מריץ apply היא: כמה זה מחייב אם אפס משתמשים יגיעו? תגדיר התראת חיוב ביום הראשון, לפני הדיפלוי הראשון, לא אחרי החשבונית הראשונה. וכשאתה מוחק ניסוי, תמחק אותו בקונסולה, שירות אחרי שירות — הקומפיוט הוא החלק הזול, והדברים שנשארים מאחור הם אף פעם לא הדברים שאתה זוכר שיצרת."},

"AWS / Azure / GCP": {
 "en": "All three sell the same six things: compute, storage, network, a managed database, identity, and a queue. Everything else in their console is one of those six with a marketing name on it. The differences that matter are not technical capability, they are naming, the shape of the pricing, and which managed services are actually good rather than merely present. Learning the primitives transfers between providers in an afternoon. Learning one provider's console does not transfer at all, and it is also the thing that takes six months. This is why experienced people sound bored about the provider question: they are choosing between three vendors of the same commodity, and they know the interesting decisions are elsewhere.\n\nA solo founder building a scheduling app spent eleven days on AWS getting a VPC, subnets, security groups, an IAM role, a task definition and a load balancer into a state where a container could serve traffic. The same app went live on Fly.io in about nine minutes with one command, and on Railway by connecting the repository. Two years and forty thousand users later it is still on that platform, costing around sixty dollars a month. The eleven days bought nothing except a vocabulary he could have learned later. The reverse case is real too: a team with compliance requirements, an existing enterprise agreement and a data-residency clause had no choice, and the eleven days were the job.\n\nAI agents were trained on a decade of AWS blog posts, so they reach for AWS reflexively and produce Terraform for a landing page. The useful counter-question is: what is the smallest host that serves this, and what would force me off it? For most projects the answer is a platform-as-a-service, and the forcing function is usually a specific managed service or a compliance requirement, not scale. Pick the boring host, keep your app in a container, and the migration you may never need stays cheap.",
 "he": "שלושתם מוכרים את אותם שישה דברים: קומפיוט, אחסון, רשת, מסד נתונים מנוהל, זהות, ותור. כל השאר בקונסולה שלהם הוא אחד מהשישה האלה עם שם שיווקי. ההבדלים שחשובים הם לא יכולת טכנית, אלא שמות, צורת התמחור, ואילו שירותים מנוהלים באמת טובים ולא רק קיימים. ללמוד את אבני הבסיס עובר בין ספקים תוך אחר צהריים. ללמוד את הקונסולה של ספק מסוים לא עובר בכלל, וזה גם מה שלוקח חצי שנה. בגלל זה אנשים מנוסים נשמעים משועממים משאלת הספק: הם בוחרים בין שלושה ספקים של אותה סחורה, והם יודעים שההחלטות המעניינות נמצאות במקום אחר.\n\nיזם סולו שבנה אפליקציית תיאום פגישות בילה אחד עשר ימים ב-AWS כדי להביא VPC, סאבנטים, security groups, תפקיד IAM, task definition ומאזן עומסים למצב שבו קונטיינר מצליח לשרת תעבורה. אותה אפליקציה עלתה לאוויר ב-Fly.io בתשע דקות בערך עם פקודה אחת, וב-Railway פשוט בחיבור הריפו. שנתיים וארבעים אלף משתמשים אחר כך היא עדיין שם, ועולה בערך שישים דולר בחודש. אחד עשר הימים לא קנו כלום חוץ מאוצר מילים שאפשר היה ללמוד אחר כך. גם המקרה ההפוך אמיתי: לצוות עם דרישות רגולציה, הסכם ארגוני קיים וסעיף מקום אחסון נתונים לא הייתה ברירה, ואחד עשר הימים היו בדיוק העבודה.\n\nסוכני AI אומנו על עשור של פוסטים מהבלוג של AWS, אז הם הולכים ל-AWS ברפלקס ומייצרים לך Terraform בשביל דף נחיתה. שאלת הנגד המועילה היא: מה ההוסטינג הכי קטן שמשרת את זה, ומה יכריח אותי לעזוב אותו? לרוב הפרויקטים התשובה היא פלטפורמה מנוהלת, ומה שמכריח לעזוב הוא בדרך כלל שירות מנוהל מסוים או דרישת רגולציה, לא סקייל. תבחר את ההוסטינג המשעמם, תשמור את האפליקציה בקונטיינר, וההגירה שאולי לעולם לא תצטרך נשארת זולה."},

"S3 / object storage": {
 "en": "Object storage gives up everything a filesystem promises — folders you can rename, partial edits, locking, a path that means something — and gets back three things in exchange: capacity with no practical ceiling, durability measured in eleven nines, and a URL for every item. There are no directories. The slashes in a key are characters in a name, not a tree. You cannot append to an object or change byte four hundred of it; you replace the whole thing. Once you accept that it is a key-value store whose values happen to be files, the whole model stops being surprising and the mistakes stop being mysterious.\n\nA marketplace let sellers upload product photos and wrote them to the server's local disk, serving them from a static folder. It worked perfectly for four months. Then traffic grew, a second instance came up behind a load balancer, and roughly half of all image requests started returning 404, because each instance only had the photos uploaded to itself. The fix looked simple and was not: eighteen thousand images had to be copied off two disks, deduplicated, and re-pointed. Worse, the previous deploy had already destroyed the first instance's disk, so around nine hundred images from the earliest months were gone with no backup. The whole incident traced back to one line choosing a local path.\n\nThe pattern to insist on with an agent is that the browser uploads directly to storage using a short-lived presigned URL, and your server only ever stores the key. If you see code where the file passes through your API, ask what happens to a 200MB video on a container with 512MB of memory. Then check two settings that AI-generated bucket configs get wrong constantly: the bucket must not be publicly listable, and a lifecycle rule should expire whatever does not need to live forever. Storage is cheap per gigabyte and you are going to keep it for years.",
 "he": "אחסון אובייקטים מוותר על כל מה שמערכת קבצים מבטיחה — תיקיות שאפשר לשנות להן שם, עריכה חלקית, נעילה, נתיב שיש לו משמעות — ומקבל בתמורה שלושה דברים: קיבולת בלי תקרה מעשית, עמידות שנמדדת באחת עשרה תשיעיות, וכתובת URL לכל פריט. אין תיקיות. הלוכסנים במפתח הם תווים בשם, לא עץ. אי אפשר להוסיף לסוף אובייקט או לשנות בו את בייט ארבע מאות; מחליפים את כולו. ברגע שמקבלים שזה מאגר מפתח-ערך שהערכים שלו במקרה הם קבצים, המודל מפסיק להפתיע והטעויות מפסיקות להיות מסתוריות.\n\nמרקטפלייס אפשר למוכרים להעלות תמונות מוצר, וכתב אותן לדיסק המקומי של השרת והגיש אותן מתיקייה סטטית. זה עבד מצוין ארבעה חודשים. ואז התעבורה גדלה, אינסטנס שני עלה מאחורי מאזן עומסים, ובערך חצי מהבקשות לתמונות התחילו להחזיר 404, כי לכל אינסטנס היו רק התמונות שהועלו אליו. התיקון נראה פשוט ולא היה: שמונה עשר אלף תמונות היו צריכות לעבור משני דיסקים, לעבור ניכוי כפילויות, ולקבל הפניה מחדש. גרוע מזה, הדיפלוי הקודם כבר השמיד את הדיסק של האינסטנס הראשון, אז בערך תשע מאות תמונות מהחודשים הראשונים נעלמו בלי גיבוי. כל האירוע התחקה לשורה אחת שבחרה נתיב מקומי.\n\nהדפוס שכדאי להתעקש עליו מול סוכן AI הוא שהדפדפן מעלה ישירות לאחסון עם presigned URL קצר-טווח, והשרת שלך שומר רק את המפתח. אם אתה רואה קוד שבו הקובץ עובר דרך ה-API שלך, תשאל מה קורה לווידאו של 200MB על קונטיינר עם 512MB זיכרון. ואז תבדוק שתי הגדרות שקונפיגורציות באקט שנוצרו על ידי AI טועות בהן כל הזמן: אסור שיהיה אפשר להציג את רשימת הקבצים בבאקט באופן ציבורי, וצריך כלל lifecycle שמוחק את מה שלא צריך לחיות לנצח. אחסון זול לג׳יגה ואתה הולך לשמור אותו שנים."},

"EC2 / VM vs Lambda / serverless": {
 "en": "The real question is who owns the idle time. On a virtual machine you rent the box, and every second nobody is using it is a second you paid for. With serverless the provider owns the box, packs many customers onto it, and charges you per invocation and per gigabyte-second of memory while your code is actually running. That is the whole difference, and every other property follows from it: the cold start exists because the provider is allowed to put your function to sleep, and the predictable latency of a VM exists because nobody is allowed to put it to sleep.\n\nA webhook receiver handling about thirty thousand calls a month costs somewhere near twenty cents on Lambda and would cost fifteen to thirty dollars on the smallest always-on instance. That is a hundredfold difference and the choice is obvious. Now change one number: an image-processing endpoint doing two million invocations a month at two seconds and 1GB each is roughly sixty-seven dollars of duration plus four of requests, while a single well-used small instance handling the same steady load runs around thirty. The crossover is not about scale, it is about the shape of the traffic. Spiky and mostly idle favours serverless; steady and constant favours a machine. The other trap is state: a colleague's Lambda held a database connection per instance, and a traffic spike opened nine hundred connections against a Postgres configured for a hundred, taking down an application that had nothing to do with the spike.\n\nAgents default to whichever pattern dominated their training data and rarely flag the constraints. Before accepting serverless, ask three things: how long can a single execution run, does anything here need a filesystem or a long-lived connection, and what is the p99 including a cold start. If the answer involves a background job that runs for four minutes, a WebSocket, or a connection pool, you want a machine — or at least a connection proxy in front of the database.",
 "he": "השאלה האמיתית היא של מי זמן הסרק. במכונה וירטואלית אתה שוכר את הקופסה, וכל שנייה שאף אחד לא משתמש בה היא שנייה ששילמת עליה. בסרברלס הספק הוא בעל הקופסה, דוחס עליה הרבה לקוחות, ומחייב אותך לפי קריאה ולפי ג׳יגה-שנייה של זיכרון בזמן שהקוד שלך באמת רץ. זה כל ההבדל, וכל תכונה אחרת נגזרת ממנו: הקולד-סטארט (cold start) קיים כי לספק מותר להרדים את הפונקציה שלך, וההשהיה הצפויה של מכונה וירטואלית קיימת כי לאף אחד לא מותר להרדים אותה.\n\nמקלט webhook שמטפל בערך בשלושים אלף קריאות בחודש עולה משהו כמו עשרים סנט ב-Lambda, והיה עולה חמישה עשר עד שלושים דולר על האינסטנס הקטן ביותר שרץ תמיד. זה פי מאה וההחלטה ברורה. עכשיו תשנה מספר אחד: נקודת קצה לעיבוד תמונות עם שני מיליון קריאות בחודש, שתי שניות ו-1GB לכל אחת, היא בערך שישים ושבעה דולר של זמן ריצה ועוד ארבעה של בקשות, בעוד שאינסטנס קטן אחד מנוצל היטב שמטפל באותו עומס קבוע עולה בערך שלושים. נקודת החיתוך היא לא סקייל, היא צורת התעבורה. קפיצות עם הרבה סרק מתאימות לסרברלס; עומס קבוע ורציף מתאים למכונה. המלכודת השנייה היא סטייט: ל-Lambda של חבר היה חיבור למסד נתונים לכל אינסטנס, וקפיצת תעבורה פתחה תשע מאות חיבורים מול Postgres שמוגדר למאה, והפילה אפליקציה אחרת לגמרי שלא הייתה קשורה לקפיצה.\n\nסוכנים בוחרים כברירת מחדל את הדפוס ששלט בנתוני האימון שלהם, ולעיתים רחוקות מציינים את המגבלות. לפני שאתה מקבל סרברלס, תשאל שלושה דברים: כמה זמן ריצה בודדת יכולה לרוץ, האם משהו כאן צריך מערכת קבצים או חיבור ארוך-טווח, ומה ה-p99 כולל קולד-סטארט. אם התשובה כוללת ג׳וב רקע שרץ ארבע דקות, WebSocket, או pool של חיבורים — אתה רוצה מכונה, או לפחות פרוקסי חיבורים לפני מסד הנתונים."},

"Container / Docker": {
 "en": "A container is a written description of an environment that lives in version control next to the code it runs. That is the actual innovation. Isolation existed before, and virtual machines gave you more of it. What was new is that the environment became a file you can read, diff, review and roll back — the same operating system version, the same system libraries, the same locale, the same entrypoint, on your laptop and on the server and in CI. The image is built once and the identical bytes run everywhere, which is why the phrase \"works on my machine\" stopped being a defence.\n\nA team spent three days on a bug where date formatting was one day off for some customers and not others. The production containers were built on a base image with a different default timezone than the developers' machines, and a date was being formatted before conversion to UTC. Once the Dockerfile pinned the timezone explicitly, the bug was gone and — more importantly — could never come back silently, because the setting was now a reviewed line in a file. The same team later cut their image from 1.2GB to 180MB with a multi-stage build, which took the deploy from four minutes to fifty seconds and removed the compiler toolchain from the machine facing the internet.\n\nGenerated Dockerfiles have a few predictable flaws. They copy the whole source before installing dependencies, which destroys layer caching and makes every build reinstall everything. They use `latest` as a tag, so a rebuild three months from now silently gets a different language runtime. They run as root, which means a remote code execution is a root execution. And they ship the build toolchain into production. Ask for a multi-stage build, a pinned base image, a non-root user, and a .dockerignore — then confirm that the container actually starts with no network access to your local machine, because that is when the missing environment variable shows up.",
 "he": "קונטיינר הוא תיאור כתוב של סביבה שחי בבקרת גרסאות לצד הקוד שהוא מריץ. זו החדשנות האמיתית. בידוד היה קיים לפני כן, ומכונות וירטואליות נתנו יותר ממנו. מה שהיה חדש הוא שהסביבה הפכה לקובץ שאפשר לקרוא, להשוות, לעבור עליו בסקירה ולחזור ממנו אחורה — אותה גרסת מערכת הפעלה, אותן ספריות מערכת, אותו locale, אותה נקודת כניסה, על הלפטופ שלך ועל השרת וב-CI. האימג׳ נבנה פעם אחת ואותם בתים בדיוק רצים בכל מקום, ובגלל זה ״אצלי זה עובד״ הפסיק להיות טיעון.\n\nצוות בילה שלושה ימים על באג שבו פורמט תאריך היה יום אחד קדימה לחלק מהלקוחות ולא לאחרים. הקונטיינרים בפרודקשן נבנו על בסיס אימג׳ עם אזור זמן ברירת מחדל שונה מזה שעל המחשבים של המפתחים, והתאריך עבר פורמט לפני ההמרה ל-UTC. ברגע שה-Dockerfile קיבע את אזור הזמן במפורש, הבאג נעלם — וחשוב מזה, הוא לא יכול לחזור בשקט, כי ההגדרה היא עכשיו שורה מתועדת בקובץ שעוברת סקירה. אותו צוות אחר כך הוריד את האימג׳ מ-1.2GB ל-180MB עם בילד רב-שלבי, מה שקיצר את הדיפלוי מארבע דקות לחמישים שניות והוציא את כלי הקומפילציה מהמכונה שחשופה לאינטרנט.\n\nל-Dockerfile שנוצר על ידי AI יש כמה פגמים צפויים. הוא מעתיק את כל קוד המקור לפני התקנת התלויות, מה שהורס את הקאש של השכבות וגורם לכל בילד להתקין הכל מחדש. הוא משתמש בתגית latest, אז בילד מחדש בעוד שלושה חודשים יקבל בשקט ריצת שפה אחרת. הוא רץ כ-root, כלומר הרצת קוד מרחוק היא הרצה כ-root. והוא שולח את כלי הבילד לפרודקשן. תבקש בילד רב-שלבי, אימג׳ בסיס מקובע, משתמש שאינו root, וקובץ .dockerignore — ואז תוודא שהקונטיינר באמת עולה בלי גישת רשת למחשב המקומי שלך, כי אז מתגלה משתנה הסביבה החסר."},

"Deploy": {
 "en": "Deployment is a risk-management problem wearing a technical costume. The goal is not to never break production — you will break production — it is to make each break small, obvious within minutes, and reversible in one action. Everything considered good practice here follows from that single sentence. Deploy small changes because a small change has a small blast radius. Deploy often because rehearsed procedures do not fail at 2am. Keep the previous version warm because undoing is faster than diagnosing. Separate deploying code from releasing a feature, using a flag, because then a bad feature does not require a bad rollback.\n\nAn e-commerce team shipped once every three weeks, batching around forty merged changes per release. One Thursday checkout started failing for customers paying in euros. It took four hours to find the cause among forty changes, and the rollback also reverted a fix that three other teams had already built on. Revenue lost that afternoon was in the tens of thousands. They moved to deploying on every merge to main, behind a rolling update that never drops below two healthy instances, with a one-command rollback. The next incident was found in eleven minutes, because there was only one change to suspect, and reverted in ninety seconds.\n\nThe question to ask an agent that has just written a deploy pipeline is not \"does it deploy\" but \"how do I undo this, and how long does it take\". If the answer involves rebuilding an image, you do not have a rollback, you have a second deploy. Also check what happens to requests already in flight while instances are being replaced, and whether a database migration in the same release can be reversed — a deploy you can roll back but a migration you cannot is not a rollback at all, and dropping a column in the same release that stops writing to it is the classic way to discover this.",
 "he": "דיפלוי הוא בעיה של ניהול סיכונים בתחפושת טכנית. המטרה היא לא אף פעם לא לשבור את הפרודקשן — אתה תשבור את הפרודקשן — אלא לגרום לכל שבירה להיות קטנה, ברורה תוך דקות, והפיכה בפעולה אחת. כל מה שנחשב פרקטיקה טובה בתחום נגזר מהמשפט הזה. לעשות דיפלוי לשינויים קטנים, כי לשינוי קטן יש רדיוס פגיעה קטן. לעשות דיפלוי לעיתים קרובות, כי תהליכים מתורגלים לא נכשלים בשתיים בלילה. להשאיר את הגרסה הקודמת חמה, כי לבטל מהיר יותר מלאבחן. להפריד בין דיפלוי של קוד לבין שחרור של פיצ׳ר, עם פיצ׳ר-פלאג, כי אז פיצ׳ר גרוע לא מחייב רולבק גרוע.\n\nצוות מסחר אלקטרוני שחרר פעם בשלושה שבועות, וצבר בערך ארבעים שינויים לכל שחרור. יום חמישי אחד הצ׳קאאוט התחיל להיכשל ללקוחות ששילמו ביורו. לקח ארבע שעות למצוא את הסיבה בין ארבעים שינויים, והרולבק גם ביטל תיקון ששלושה צוותים אחרים כבר בנו מעליו. ההכנסות שאבדו באותו אחר צהריים היו בעשרות אלפים. הם עברו לדיפלוי בכל מיזוג ל-main, מאחורי עדכון מתגלגל שלא יורד מתחת לשני אינסטנסים תקינים, עם רולבק בפקודה אחת. התקלה הבאה נמצאה תוך אחת עשרה דקות, כי היה רק שינוי אחד לחשוד בו, ובוטלה תוך תשעים שניות.\n\nהשאלה לשאול סוכן AI שזה עתה כתב לך תהליך דיפלוי היא לא ״האם זה עושה דיפלוי״ אלא ״איך אני מבטל את זה, וכמה זמן זה לוקח״. אם התשובה כוללת בנייה מחדש של אימג׳, אין לך רולבק, יש לך דיפלוי שני. תבדוק גם מה קורה לבקשות שכבר באוויר בזמן שמחליפים אינסטנסים, והאם מיגרציה של מסד נתונים באותו שחרור ניתנת להיפוך — דיפלוי שאפשר להחזיר אחורה עם מיגרציה שאי אפשר הוא בכלל לא רולבק, ומחיקת עמודה באותו שחרור שבו מפסיקים לכתוב אליה היא הדרך הקלאסית לגלות את זה."},

"CI/CD": {
 "en": "CI is a machine that disagrees with you on a schedule. Its value is not that it saves typing — you could run the tests yourself — it is that the checks become unskippable and identical for everyone, including you at midnight, including the agent that just opened a pull request. A pipeline is also the only honest definition of \"done\" a team ever writes down. Whatever the pipeline enforces is the real standard; everything else is a preference that people follow when they are not in a hurry, which is to say when it does not matter.\n\nA team added a linter to CI but left it non-blocking, because failing builds felt aggressive. Nine months later they had four thousand warnings and nobody read the output. Another team made a single check blocking from day one: the test suite must pass and coverage on changed lines must not drop. Their agent-generated pull requests started arriving with tests, because the author — human or not — could not merge without them. The pipeline did not make anyone a better engineer; it made one specific mistake impossible, which is all a guardrail is supposed to do. The same pipeline caught a dependency update that broke date parsing in a way no reviewer would have noticed reading the diff.\n\nWith an AI agent in the loop this matters more than it used to, because the volume of confident, plausible, untested code went up by an order of magnitude and your reading speed did not. Insist the pipeline runs on pull requests, not only on main, and that at least one check actually blocks the merge. Watch the runtime: a pipeline that takes twenty minutes will be bypassed, so cache dependencies and run the slow jobs in parallel. And keep deploy credentials in the CI provider's secret store, never in the repository — a token in a YAML file is a token in everyone's clone, and rotating it is a worse afternoon than setting it up properly.",
 "he": "CI הוא מכונה שחולקת עליך באופן קבוע. הערך שלו הוא לא שהוא חוסך הקלדה — אתה יכול להריץ את הבדיקות בעצמך — אלא שהבדיקות הופכות לבלתי ניתנות לדילוג וזהות לכולם, כולל אותך בחצות, כולל הסוכן שזה עתה פתח pull request. תהליך CI הוא גם ההגדרה הכנה היחידה של ״סיימנו״ שצוות אי פעם כותב. מה שהתהליך אוכף הוא הסטנדרט האמיתי; כל השאר הוא העדפה שאנשים מקיימים כשהם לא ממהרים, כלומר כשזה לא משנה.\n\nצוות הוסיף לינטר ל-CI אבל השאיר אותו לא חוסם, כי בילד שנכשל הרגיש להם אגרסיבי. תשעה חודשים אחר כך היו להם ארבעת אלפים אזהרות ואף אחד לא קרא את הפלט. צוות אחר הפך בדיקה אחת לחוסמת מהיום הראשון: חבילת הבדיקות חייבת לעבור, וכיסוי על השורות שהשתנו לא יורד. ה-pull requests שהסוכן שלהם ייצר התחילו להגיע עם בדיקות, כי הכותב — אנושי או לא — לא יכול היה למזג בלעדיהן. התהליך לא הפך אף אחד למהנדס טוב יותר; הוא הפך טעות ספציפית אחת לבלתי אפשרית, וזה כל מה שמעקה אמור לעשות. אותו תהליך תפס עדכון תלות ששבר פענוח תאריכים בצורה שאף מבקר קוד לא היה מבחין בה בקריאת הדיף.\n\nעם סוכן AI בתהליך זה חשוב יותר מבעבר, כי כמות הקוד הבטוח-בעצמו, המשכנע והלא-בדוק גדלה בסדר גודל ומהירות הקריאה שלך לא. תתעקש שהתהליך ירוץ על pull requests, לא רק על main, ושלפחות בדיקה אחת באמת חוסמת מיזוג. תשים לב לזמן הריצה: תהליך שלוקח עשרים דקות ייעקף, אז תשמור קאש לתלויות ותריץ את הג׳ובים האיטיים במקביל. ותשמור הרשאות דיפלוי במאגר הסודות של ספק ה-CI, לעולם לא בריפו — טוקן בקובץ YAML הוא טוקן אצל כל מי ששיכפל את הריפו, והחלפה שלו היא אחר צהריים גרוע יותר מלהגדיר אותו נכון מלכתחילה."},

"Logs & monitoring": {
 "en": "You cannot debug what you cannot observe, and production is the one place you cannot attach a debugger. Logs are therefore the only evidence you will ever have about what actually happened, and they are written before the incident, by a version of you who did not know what was going to go wrong. That is the whole difficulty. The useful unit is not the message, it is the decision: which branch was taken, with what input, and why. \"Processing order\" tells you nothing. \"Rejected order 7c3f: coupon expired 2026-03-01, user 9f2c\" ends the investigation in one line.\n\nA payments integration started failing for roughly two percent of transactions. The logs said \"payment failed\" with no identifiers, no amounts and no provider response, which meant that finding a single affected transaction required cross-referencing support tickets by hand. Three engineers spent two days on it. The eventual cause was a provider returning a specific decline code for one card network, which a single logged field would have shown immediately. Afterwards they added a request id that travels from the web request into every log line and into the queue job, and the next incident of similar shape was diagnosed in six minutes by pasting one id into a search box.\n\nAgents generate console.log statements, which are strings; what you want is structured events, which are objects you can filter and count. Ask for a JSON logger with a correlation id, and give it explicit instruction about what never goes in a log: passwords, tokens, full card numbers, and personal data you would not want in a third-party search index. Then add exactly two alerts before you need them — error rate above a threshold, and the healthcheck failing — because an alert that fires on everything trains you to ignore it, and the silence of a system with no monitoring is indistinguishable from the silence of a system that nobody can reach.",
 "he": "אי אפשר לדבג מה שאי אפשר לראות, ופרודקשן הוא המקום היחיד שבו אי אפשר לחבר דיבאגר. לכן לוגים הם הראיה היחידה שאי פעם תהיה לך לגבי מה באמת קרה, והם נכתבו לפני האירוע, על ידי גרסה שלך שלא ידעה מה עומד להשתבש. זה כל הקושי. היחידה המועילה היא לא ההודעה, היא ההחלטה: איזה ענף נבחר, עם איזה קלט, ולמה. ״מעבד הזמנה״ לא אומר לך כלום. ״נדחתה הזמנה 7c3f: קופון פג ב-2026-03-01, משתמש 9f2c״ מסיים את החקירה בשורה אחת.\n\nאינטגרציית תשלומים התחילה להיכשל בערך בשני אחוזים מהעסקאות. הלוגים אמרו ״תשלום נכשל״ בלי מזהים, בלי סכומים ובלי תשובת הספק, כלומר כדי למצוא עסקה אחת שנפגעה היה צריך להצליב פניות תמיכה ידנית. שלושה מפתחים בילו על זה יומיים. הסיבה בסוף הייתה שהספק החזיר קוד דחייה מסוים לרשת כרטיסים אחת, מה ששדה אחד בלוג היה מראה מיד. אחר כך הם הוסיפו מזהה בקשה שנוסע מהבקשה בדפדפן לכל שורת לוג ולתוך ג׳וב התור, והתקלה הבאה מאותה צורה אובחנה תוך שש דקות בהדבקת מזהה אחד בתיבת חיפוש.\n\nסוכנים מייצרים שורות console.log, שהן מחרוזות; מה שאתה רוצה הוא אירועים מובנים, שהם אובייקטים שאפשר לסנן ולספור. תבקש לוגר JSON עם מזהה מתאם, ותן לו הוראה מפורשת מה לעולם לא נכנס ללוג: סיסמאות, טוקנים, מספרי כרטיס מלאים, ומידע אישי שלא היית רוצה באינדקס חיפוש של צד שלישי. ואז תוסיף בדיוק שתי התראות עוד לפני שתצטרך אותן — שיעור שגיאות מעל סף, ובדיקת בריאות שנכשלת — כי התראה שקופצת על הכל מאמנת אותך להתעלם ממנה, והשקט של מערכת בלי ניטור זהה לחלוטין לשקט של מערכת שאף אחד לא מצליח להגיע אליה."},

# ================= Scale & Architecture =================

"Scaling up vs out": {
 "en": "Scaling up is buying your way out of a problem with no code changes, and it works far better and for far longer than most people expect. Doubling the CPU and memory of a database is a fifteen-minute maintenance window and solves most growing pains up to a size that the majority of products never reach. It ends at a hard ceiling — there is a largest instance — and the last few steps before the ceiling are priced punitively, because at that point the provider knows you have no alternative. Scaling out has no ceiling, but it demands a property from your code that scaling up never asked for: any instance must be able to serve any request.\n\nA SaaS with growing report volumes moved from a 4-core database instance to a 16-core one and went from 90% CPU to 22% in an afternoon, for about four hundred dollars a month more. That bought them eighteen months. They spent those eighteen months adding indexes and caching, which turned out to cut the load by more than the hardware had. The counter-example is a team that jumped straight to three application instances to fix slow response times, and discovered their sessions were in process memory: users were randomly logged out on roughly two requests in three, and the incident lasted a full day because the fix was not a config change but a rewrite of authentication.\n\nWhen an agent proposes horizontal scaling, the question is not whether it will work but what in the current code assumes a single process. Search for in-memory caches, module-level variables holding user data, scheduled jobs that would now run on every instance at once, files written to local disk, and anything counting things in a local variable. Fix those first and scaling out becomes a number in a config file. And before either move, check whether the actual bottleneck is a missing index — a query that goes from 340ms to 2ms is cheaper than any machine.",
 "he": "סקייל אנכי הוא לקנות את הדרך החוצה מהבעיה בלי לשנות שורת קוד, וזה עובד הרבה יותר טוב והרבה יותר זמן ממה שרוב האנשים מצפים. להכפיל מעבד וזיכרון של מסד נתונים זה חלון תחזוקה של רבע שעה, והוא פותר את רוב כאבי הגדילה עד גודל שרוב המוצרים לעולם לא מגיעים אליו. זה נגמר בתקרה קשיחה — יש אינסטנס הכי גדול — והצעדים האחרונים לפני התקרה מתומחרים בעונשין, כי בנקודה הזו הספק יודע שאין לך אלטרנטיבה. לסקייל אופקי אין תקרה, אבל הוא דורש מהקוד שלך תכונה שסקייל אנכי מעולם לא ביקש: כל אינסטנס חייב להיות מסוגל לשרת כל בקשה.\n\nחברת SaaS עם נפח דוחות שגדל עברה ממסד נתונים עם 4 ליבות לאחד עם 16 ליבות וירדה מ-90% מעבד ל-22% תוך אחר צהריים, בערך ארבע מאות דולר בחודש יותר. זה קנה להם שמונה עשר חודשים. את שמונה עשר החודשים האלה הם בילו בהוספת אינדקסים וקאשינג, שבסוף הורידו את העומס יותר ממה שהחומרה הורידה. הדוגמה ההפוכה היא צוות שקפץ ישר לשלושה אינסטנסים של האפליקציה כדי לתקן זמני תגובה איטיים, וגילה שהסשנים שלהם יושבים בזיכרון של התהליך: משתמשים הועפו החוצה באופן אקראי בערך בשתיים מכל שלוש בקשות, והתקלה נמשכה יום שלם כי התיקון לא היה שינוי קונפיגורציה אלא שכתוב של ההזדהות.\n\nכשסוכן AI מציע סקייל אופקי, השאלה היא לא האם זה יעבוד אלא מה בקוד הנוכחי מניח תהליך יחיד. תחפש קאשים בזיכרון, משתנים ברמת המודול שמחזיקים מידע משתמש, ג׳ובים מתוזמנים שעכשיו ירוצו על כל האינסטנסים בבת אחת, קבצים שנכתבים לדיסק מקומי, וכל דבר שסופר משהו במשתנה מקומי. תתקן את אלה קודם וסקייל אופקי הופך למספר בקובץ קונפיגורציה. ולפני שני המהלכים, תבדוק אם צוואר הבקבוק האמיתי הוא אינדקס חסר — שאילתה שיורדת מ-340ms ל-2ms זולה מכל מכונה."},

"Load balancer": {
 "en": "A load balancer turns many machines into one address, and in doing so quietly becomes the place where several important decisions live: which instances are considered healthy, how connections are spread, where TLS terminates, and how long a slow response is allowed to hang before it is cut off. Most people set it up once and never look again, which is a shame, because the single most consequential setting in the whole system is usually sitting in it — the health check. The balancer's entire job is to skip broken instances, and it can only do that as well as your health check describes brokenness.\n\nAn API had a health check on `GET /` that returned 200 if the process was alive. Their database credentials expired during a rotation, and every instance began returning 500 for every real request while cheerfully reporting healthy. The balancer kept sending traffic to all of them for fifty minutes, because from its point of view nothing was wrong. A health check that actually opened a database connection and pinged Redis would have marked every instance unhealthy, and the alert would have fired in under a minute. The counterweight is equally real: a health check that is too strict, or that calls a third-party API, will take your whole fleet out of rotation because someone else had an outage.\n\nThe practical rule is that the health check should test the dependencies this instance needs in order to serve, and nothing further away than that. Cache its result for a few seconds so the check itself does not become load. When an agent sets up a balancer, verify three things beyond the routing: that idle and request timeouts are longer than your slowest legitimate endpoint, that connection draining is on so a deploy does not cut off in-flight requests, and that sticky sessions are off — if your app needs them, you have a state problem the balancer is only hiding.",
 "he": "מאזן עומסים הופך הרבה מכונות לכתובת אחת, ותוך כדי כך הופך בשקט למקום שבו חיות כמה החלטות חשובות: אילו אינסטנסים נחשבים תקינים, איך מפזרים חיבורים, איפה מסתיים TLS, וכמה זמן מותר לתגובה איטית להיתקע לפני שהיא נחתכת. רוב האנשים מגדירים אותו פעם אחת ולא מסתכלים שוב, וחבל, כי ההגדרה הכי משמעותית בכל המערכת בדרך כלל יושבת שם — בדיקת הבריאות. כל התפקיד של המאזן הוא לדלג על אינסטנסים שבורים, והוא יכול לעשות את זה רק כמו שבדיקת הבריאות שלך מתארת שבירה.\n\nל-API הייתה בדיקת בריאות על `GET /` שהחזירה 200 אם התהליך חי. פרטי ההתחברות למסד הנתונים פגו במהלך החלפה, וכל אינסטנס התחיל להחזיר 500 לכל בקשה אמיתית, בזמן שדיווח בשמחה שהוא תקין. המאזן המשיך לשלוח תעבורה לכולם במשך חמישים דקות, כי מבחינתו שום דבר לא היה בסדר. בדיקת בריאות שבאמת פותחת חיבור למסד הנתונים ועושה ping ל-Redis הייתה מסמנת את כל האינסטנסים כלא תקינים, וההתראה הייתה קופצת תוך פחות מדקה. המשקל הנגדי אמיתי באותה מידה: בדיקת בריאות מחמירה מדי, או כזו שקוראת ל-API של צד שלישי, תוציא לך את כל הצי מהמחזור כי למישהו אחר הייתה תקלה.\n\nהכלל המעשי הוא שבדיקת הבריאות צריכה לבדוק את התלויות שהאינסטנס הזה צריך כדי לשרת, ולא שום דבר רחוק מזה. תשמור את התוצאה שלה בקאש לכמה שניות כדי שהבדיקה עצמה לא תהפוך לעומס. כשסוכן AI מגדיר מאזן עומסים, תוודא שלושה דברים מעבר לניתוב: שהטיים-אאוטים ארוכים יותר מנקודת הקצה הלגיטימית האיטית ביותר שלך, ש-connection draining דלוק כדי שדיפלוי לא יחתוך בקשות באוויר, ושדביקות סשן (sticky sessions) כבויה — אם האפליקציה שלך צריכה אותה, יש לך בעיית סטייט שהמאזן רק מסתיר."},

"Stateless": {
 "en": "Stateless does not mean there is no state. It means the state does not live inside the process. It lives in the database, in a shared cache like Redis, or in the request itself — somewhere every instance can reach equally, so that no request is tied to the machine that happened to handle the previous one. Once you have that property, a large number of hard things become trivial. You can add instances, kill instances, deploy by replacing every instance, run the same code in a container and in a lambda, and restart anything at any time without anyone noticing. Almost every scaling technique assumes it as a precondition.\n\nA team ran a rate limiter as a counter in a module-level variable. It worked in testing with one process. In production with four instances the effective limit was four times what anyone intended, and scaling to eight during a sale doubled it again — which they discovered when a scraper pulled their entire catalogue. The same code base kept an in-memory cache of feature flags, so turning a flag off took effect on one instance immediately and on the others whenever they next restarted, producing an hour of customers seeing two different checkout flows depending on which server answered.\n\nThe things to grep for are short and specific: module-level variables that are assigned after startup, `new Map()` or `{}` used as a cache, uploads written to a local path, `setInterval` doing scheduled work, and any in-memory session store. Each of them is correct with one process and a bug with two. When an agent suggests an in-memory cache because it is faster — and it is faster — the question is what happens when two instances disagree, and how long that disagreement lasts. If the answer is \"until restart\", it belongs in Redis with a TTL, not in the process.",
 "he": "סטייטלס לא אומר שאין סטייט. זה אומר שהסטייט לא חי בתוך התהליך. הוא חי במסד הנתונים, בקאש משותף כמו Redis, או בבקשה עצמה — במקום שכל אינסטנס מגיע אליו באותה מידה, כך שאף בקשה לא קשורה למכונה שבמקרה טיפלה בקודמת. ברגע שיש לך את התכונה הזו, הרבה מאוד דברים קשים הופכים לטריוויאליים. אפשר להוסיף אינסטנסים, להרוג אינסטנסים, לעשות דיפלוי בהחלפת כל האינסטנסים, להריץ את אותו קוד בקונטיינר וב-lambda, ולהפעיל מחדש כל דבר בכל רגע בלי שאף אחד ישים לב. כמעט כל טכניקת סקייל מניחה את זה כתנאי מקדים.\n\nצוות הריץ הגבלת קצב כמונה במשתנה ברמת המודול. זה עבד בבדיקות עם תהליך אחד. בפרודקשן עם ארבעה אינסטנסים המגבלה בפועל הייתה פי ארבעה ממה שמישהו התכוון, וסקייל לשמונה במהלך מבצע הכפיל אותה שוב — מה שהם גילו כששואב נתונים משך להם את כל הקטלוג. אותו קוד החזיק גם קאש בזיכרון של פיצ׳ר-פלאגים, אז כיבוי פלאג נכנס לתוקף באינסטנס אחד מיד ובאחרים רק כשהם עלו מחדש, מה שייצר שעה שבה לקוחות ראו שני מסלולי צ׳קאאוט שונים תלוי איזה שרת ענה.\n\nהדברים לחפש קצרים וספציפיים: משתנים ברמת המודול שמקבלים ערך אחרי העלייה, `new Map()` או `{}` שמשמשים כקאש, העלאות שנכתבות לנתיב מקומי, `setInterval` שעושה עבודה מתוזמנת, וכל מאגר סשנים בזיכרון. כל אחד מהם נכון עם תהליך אחד ובאג עם שניים. כשסוכן AI מציע קאש בזיכרון כי זה מהיר יותר — וזה באמת מהיר יותר — השאלה היא מה קורה כששני אינסטנסים לא מסכימים, וכמה זמן חוסר ההסכמה הזה נמשך. אם התשובה היא ״עד להפעלה מחדש״, זה שייך ל-Redis עם TTL, לא לתהליך."},

"Queue / worker": {
 "en": "A queue separates accepting work from doing it, and that single separation buys three things at once: responses stay fast because the request returns as soon as the job is recorded, traffic spikes stop being outages because the queue absorbs them and the workers drain at their own pace, and retries become free because a job that fails is simply still in the queue. The cost is that you now owe the user an answer about something that has not finished yet, which means a status they can see, and a plan for jobs that fail forever.\n\nA reporting endpoint built a PDF inside the request. It took eight seconds, which was tolerable until a customer clicked it four times and their browser gave up at thirty seconds while four PDFs were still being built. At month-end, forty customers did this at once and the web process ran out of memory, taking down the entire application — including login for everyone else. Moving PDF generation to a queue made the endpoint return in 40ms with a job id, kept the web tier at flat memory usage during month-end, and confined a genuinely slow operation to workers that could be scaled independently. The one new problem was jobs that failed on corrupt input and retried forever until someone added a dead-letter queue and stopped retrying after five attempts.\n\nAI-generated queue code usually forgets three things. It does not set a maximum retry count, so a permanently broken job retries until the end of time. It does not make the job idempotent, so a retry after a partial success sends the email twice. And it passes whole objects into the job instead of an id, so the worker processes a snapshot of data that was already stale when it was enqueued. Ask for a job that takes an id, re-reads current state, is safe to run twice, and gives up into a dead-letter queue — then check that someone will actually look at that queue.",
 "he": "תור מפריד בין קבלת עבודה לבין ביצוע שלה, וההפרדה האחת הזו קונה שלושה דברים בבת אחת: תגובות נשארות מהירות, כי הבקשה חוזרת ברגע שהמשימה נרשמה; קפיצות תעבורה מפסיקות להיות תקלות, כי התור בולע אותן והוורקרים מרוקנים אותו בקצב שלהם; וניסיונות חוזרים הופכים לחינם, כי משימה שנכשלה פשוט עדיין נמצאת בתור. המחיר הוא שאתה עכשיו חייב למשתמש תשובה על משהו שעוד לא הסתיים, כלומר סטטוס שהוא יכול לראות, ותוכנית למשימות שנכשלות לנצח.\n\nנקודת קצה של דוחות בנתה PDF בתוך הבקשה. זה לקח שמונה שניות, מה שהיה נסבל עד שלקוח לחץ ארבע פעמים והדפדפן שלו ויתר אחרי שלושים שניות בזמן שארבעה PDF עדיין נבנו. בסוף החודש ארבעים לקוחות עשו את זה בבת אחת ותהליך ה-web נגמר לו הזיכרון, והפיל את כל האפליקציה — כולל ההתחברות לכל השאר. העברת יצירת ה-PDF לתור גרמה לנקודת הקצה לחזור תוך 40ms עם מזהה משימה, שמרה על צריכת זיכרון שטוחה בשכבת ה-web בסוף החודש, ותחמה פעולה שהיא באמת איטית לוורקרים שאפשר לעשות להם סקייל בנפרד. הבעיה החדשה היחידה הייתה משימות שנכשלו על קלט פגום וניסו שוב לנצח, עד שמישהו הוסיף dead-letter queue והפסיק לנסות אחרי חמישה ניסיונות.\n\nקוד תורים שנוצר על ידי AI בדרך כלל שוכח שלושה דברים. הוא לא מגדיר מספר ניסיונות מקסימלי, אז משימה שבורה לצמיתות מנסה שוב עד סוף הזמן. הוא לא הופך את המשימה לאידמפוטנטית, אז ניסיון חוזר אחרי הצלחה חלקית שולח את המייל פעמיים. והוא מעביר אובייקטים שלמים לתוך המשימה במקום מזהה, אז הוורקר מעבד תמונת מצב של נתונים שכבר היו ישנים כשהם נכנסו לתור. תבקש משימה שמקבלת מזהה, קוראת מחדש את המצב הנוכחי, בטוחה להרצה כפולה, ומוותרת לתוך dead-letter queue — ואז תוודא שמישהו באמת יסתכל על התור הזה."},

"Idempotency": {
 "en": "Distributed systems cannot distinguish between a request that failed and a response that got lost on the way back. From the caller's side those two situations look identical: silence. So the only safe assumption is that anything you expose may be delivered twice, or five times, and that the second delivery may arrive while the first is still running. Idempotency is how you make that assumption harmless. The operation carries a key, the server records the key with its result, and a repeat of the same key returns the stored result instead of doing the work again.\n\nA payment provider's webhook fired twice within four hundred milliseconds during one of their own retries — normal, documented behaviour. The receiving code created an order row on each call, so a customer got two shipments for one payment, and the discrepancy was not caught until a warehouse count three weeks later. The refund, the return shipping and the support time cost far more than the item. The fix was a unique constraint on the provider's event id plus an insert that ignores conflicts, which is about two lines, and it made the bug structurally impossible rather than merely unlikely. The same pattern applies inbound: a checkout button double-clicked on a slow connection is the same problem arriving from a browser instead of a server.\n\nThe mental test is simple. For every endpoint that writes, ask what happens if it runs twice with identical input. If the answer is \"one extra row\", \"one extra charge\" or \"one extra email\", it needs a key. Agents are good at writing the happy path and reliably omit this, because nothing in the specification mentions duplicates. Say explicitly: accept an Idempotency-Key header, store it with the response, and enforce uniqueness in the database rather than with a check-then-insert in application code — two concurrent requests will both pass that check, and only the database can settle the race.",
 "he": "מערכות מבוזרות לא יכולות להבחין בין בקשה שנכשלה לבין תשובה שאבדה בדרך חזרה. מצד הקורא שתי הסיטואציות נראות זהות: שקט. אז ההנחה הבטוחה היחידה היא שכל דבר שאתה חושף עלול להימסר פעמיים, או חמש פעמים, ושהמסירה השנייה עלולה להגיע בזמן שהראשונה עדיין רצה. אידמפוטנטיות היא איך שהופכים את ההנחה הזו לבלתי מזיקה. הפעולה נושאת מפתח, השרת רושם את המפתח יחד עם התוצאה, וחזרה על אותו מפתח מחזירה את התוצאה השמורה במקום לבצע את העבודה שוב.\n\nwebhook של ספק תשלומים ירה פעמיים בתוך ארבע מאות מילישניות באחד הניסיונות החוזרים שלו — התנהגות נורמלית ומתועדת. הקוד שקיבל אותו יצר שורת הזמנה בכל קריאה, אז לקוח קיבל שני משלוחים על תשלום אחד, והפער לא נתפס עד ספירת מלאי במחסן שלושה שבועות אחר כך. הזיכוי, משלוח ההחזרה וזמן התמיכה עלו הרבה יותר מהמוצר עצמו. התיקון היה אילוץ ייחודיות על מזהה האירוע של הספק ועוד הוספה שמתעלמת מהתנגשות, כלומר בערך שתי שורות, והוא הפך את הבאג לבלתי אפשרי מבנית ולא רק לא סביר. אותו דפוס תקף גם בכיוון הנכנס: כפתור צ׳קאאוט שנלחץ פעמיים בחיבור איטי הוא בדיוק אותה בעיה שמגיעה מדפדפן במקום משרת.\n\nהמבחן המחשבתי פשוט. לכל נקודת קצה שכותבת, תשאל מה קורה אם היא תרוץ פעמיים עם אותו קלט בדיוק. אם התשובה היא ״עוד שורה אחת״, ״עוד חיוב אחד״ או ״עוד מייל אחד״ — היא צריכה מפתח. סוכנים טובים בכתיבת המסלול המאושר ובאופן עקבי משמיטים את זה, כי שום דבר באפיון לא מזכיר כפילויות. תגיד במפורש: לקבל כותרת Idempotency-Key, לשמור אותה עם התשובה, ולאכוף ייחודיות במסד הנתונים ולא בבדיקה-ואז-הוספה בקוד האפליקציה — שתי בקשות מקבילות יעברו את הבדיקה הזו, ורק מסד הנתונים יכול להכריע את המרוץ."},

"Monolith vs microservices": {
 "en": "Splitting a system does not reduce its complexity, it changes the currency the complexity is paid in. Function calls that could not fail become network calls that can. A single database transaction becomes a distributed one you must now reason about by hand. A stack trace that told you everything becomes four log files in three services that you have to correlate. In exchange you get independent deployment, independent scaling, and the ability for teams to work without coordinating. Those are real benefits, and they are almost entirely organisational: microservices solve a people problem, and they solve it by adding a technical one.\n\nA four-person startup split their product into nine services because they expected to grow. Adding a field to the user profile then touched three services and three deploys that had to happen in a specific order. Local development needed docker-compose with nine containers and about 6GB of memory, and onboarding a new developer took a week. After fourteen months they merged it back into one application and shipped features roughly three times faster with the same headcount. The opposite story also exists: a company with sixty engineers pushing one deployable had a release train where one team's bad merge blocked everyone else for two days, and splitting out the three highest-churn areas fixed it.\n\nThe honest signal for splitting is not scale, it is deploy contention — different parts of the system need to be released on different schedules by different people. Until that hurts, a modular monolith with clear internal boundaries gives you most of the benefit and none of the network. When an agent proposes a service-per-noun architecture for a project with one developer, ask which of these services will ever be deployed separately from the others. If the answer is none, you have just bought distributed-systems problems with no distributed-systems benefit.",
 "he": "פיצול מערכת לא מקטין את המורכבות שלה, הוא משנה את המטבע שבו משלמים עליה. קריאות פונקציה שלא יכלו להיכשל הופכות לקריאות רשת שכן. טרנזקציה אחת במסד נתונים הופכת לטרנזקציה מבוזרת שעכשיו אתה צריך לנתח ידנית. stack trace שסיפר לך הכל הופך לארבעה קבצי לוג בשלושה שירותים שצריך להצליב. בתמורה אתה מקבל דיפלוי עצמאי, סקייל עצמאי, ויכולת של צוותים לעבוד בלי לתאם. אלה יתרונות אמיתיים, והם כמעט לגמרי ארגוניים: מיקרו-סרוויסים פותרים בעיה של אנשים, והם פותרים אותה בהוספת בעיה טכנית.\n\nסטארטאפ של ארבעה אנשים פיצל את המוצר שלו לתשעה שירותים כי הם ציפו לגדול. הוספת שדה לפרופיל המשתמש אז נגעה בשלושה שירותים ובשלושה דיפלויים שהיו חייבים לקרות בסדר מסוים. פיתוח מקומי דרש docker-compose עם תשעה קונטיינרים ובערך 6GB זיכרון, וקליטת מפתח חדש לקחה שבוע. אחרי ארבעה עשר חודשים הם איחדו הכל בחזרה לאפליקציה אחת ושחררו פיצ׳רים בערך פי שלושה מהר יותר עם אותו מספר אנשים. גם הסיפור ההפוך קיים: בחברה עם שישים מפתחים שדוחפים ליחידת דיפלוי אחת היה רכבת שחרורים שבה מיזוג גרוע של צוות אחד חסם את כל השאר ליומיים, והוצאת שלושת האזורים עם הכי הרבה שינויים פתרה את זה.\n\nהסימן הכן לפיצול הוא לא סקייל, הוא תחרות על הדיפלוי — חלקים שונים של המערכת צריכים לצאת בלוחות זמנים שונים על ידי אנשים שונים. עד שזה כואב, מונוליט מודולרי עם גבולות פנימיים ברורים נותן לך את רוב התועלת ואפס רשת. כשסוכן AI מציע ארכיטקטורה של שירות לכל ישות בפרויקט עם מפתח אחד, תשאל איזה מהשירותים האלה אי פעם יעבור דיפלוי בנפרד מהאחרים. אם התשובה היא אף אחד, זה עתה קנית בעיות של מערכות מבוזרות בלי שום יתרון של מערכות מבוזרות."},

"Rate limiting": {
 "en": "A rate limit is a statement about fairness and survival: no single caller may consume the capacity that belongs to everyone. It is usually framed as protection from attackers, but the most common thing a rate limit saves you from is a bug — a retry loop with no backoff, a cron that fires every second instead of every minute, a customer's integration that polls your API in a while-true. Your own code is the most frequent offender, because it has credentials and no reason to be suspicious of itself.\n\nA startup exposed a public search endpoint with no limit. A single scraper ran it at four hundred requests per second for six hours, which pushed their database to saturation and made the product unusable for every paying customer that night. The database autoscaled, so the technical symptom was mild and the financial one was not: the bill for that month was about nine hundred dollars above normal. A limit of sixty requests per minute per IP, which no real user ever approaches, would have turned the whole event into a line in a log. The same team had earlier burned through a third-party translation quota in a morning because a failed request retried instantly in a loop — two thousand dollars, spent by their own code in about ninety minutes.\n\nImplement it in a shared store, not in process memory, or each instance enforces its own private limit. Return 429 with a Retry-After header, because a client that is told when to come back will, and a client that is only rejected will hammer harder. Limit by user or API key where you can and by IP only as a fallback, since one office shares an address. And when an agent writes a client for someone else's API, check that its retry logic has exponential backoff and a ceiling — the fastest way to get your key banned is a well-meaning retry loop that treats 429 as a reason to try again immediately.",
 "he": "הגבלת קצב היא אמירה על הוגנות והישרדות: אף קורא בודד לא רשאי לצרוך את הקיבולת ששייכת לכולם. בדרך כלל מציגים אותה כהגנה מפני תוקפים, אבל הדבר הנפוץ ביותר שהגבלת קצב מצילה ממנו הוא באג — לולאת ניסיונות חוזרים בלי השהיה, cron שרץ כל שנייה במקום כל דקה, אינטגרציה של לקוח שעושה פולינג ל-API שלך בלולאה אינסופית. הקוד שלך עצמו הוא החשוד הכי תכוף, כי יש לו הרשאות ואין לו סיבה לחשוד בעצמו.\n\nסטארטאפ חשף נקודת קצה ציבורית לחיפוש בלי הגבלה. שואב נתונים אחד הריץ אותה בארבע מאות בקשות לשנייה במשך שש שעות, מה שהביא את מסד הנתונים לרוויה והפך את המוצר לבלתי שמיש לכל לקוח משלם באותו ערב. מסד הנתונים עשה סקייל אוטומטי, אז הסימפטום הטכני היה מתון והכספי לא: החשבון של אותו חודש היה בערך תשע מאות דולר מעל הרגיל. הגבלה של שישים בקשות לדקה לכל IP, שאף משתמש אמיתי לא מתקרב אליה, הייתה הופכת את כל האירוע לשורה בלוג. אותו צוות קודם לכן שרף מכסת תרגום של צד שלישי בבוקר אחד, כי בקשה שנכשלה ניסתה שוב מיד בלולאה — אלפיים דולר, שהקוד שלהם עצמו הוציא בערך בתשעים דקות.\n\nתממש את זה במאגר משותף, לא בזיכרון התהליך, אחרת כל אינסטנס אוכף מגבלה פרטית משלו. תחזיר 429 עם כותרת Retry-After, כי לקוח שאומרים לו מתי לחזור יחזור אז, ולקוח שרק נדחה ילחץ חזק יותר. תגביל לפי משתמש או מפתח API היכן שאפשר, ולפי IP רק כגיבוי, כי משרד שלם חולק כתובת אחת. וכשסוכן AI כותב לקוח ל-API של מישהו אחר, תבדוק שללוגיקת הניסיונות החוזרים יש השהיה מעריכה ותקרה — הדרך המהירה ביותר לקבל חסימה למפתח היא לולאת ניסיונות עם כוונות טובות שמתייחסת ל-429 כאל סיבה לנסות שוב מיד."},

"Single point of failure": {
 "en": "Redundancy is neither free nor automatically correct. Two of everything doubles the cost and introduces the hardest problem in the field — keeping copies in agreement — and a badly built failover mechanism causes more outages than the failure it was meant to survive. So the mature version of this discipline is not eliminating every single point of failure. It is knowing where each one is, deciding on purpose which are acceptable, and making sure that when one does fail you find out from an alert rather than from a customer.\n\nA company ran a redundant web tier across three availability zones, load balanced, auto-scaled, thoroughly engineered. All of it talked to one Postgres instance in one zone with no replica, because that had been the temporary setup two years earlier. The instance's underlying host failed on a Tuesday morning and the product was completely down for two hours and forty minutes while a restore from the nightly backup ran — which also meant nine hours of data loss for anything written since the snapshot. The engineering around the web tier had been careful and entirely irrelevant. A managed database with automated failover would have cost about ninety dollars more per month.\n\nThe cheapest exercise here takes ten minutes and no code. List every component the request path touches: DNS, CDN, load balancer, app, database, cache, the auth provider, the payment provider, the email service. For each, answer what happens if it disappears right now, and how you would know. The results are usually uncomfortable and often cheap to fix — a read replica, a second region for DNS, a graceful degradation path when the cache is cold. An agent will never raise this, because nothing about it appears in the code it is looking at.",
 "he": "יתירות היא לא חינם ולא אוטומטית נכונה. שניים מכל דבר מכפילים את העלות ומכניסים את הבעיה הקשה ביותר בתחום — לשמור על עותקים שמסכימים ביניהם — ומנגנון גיבוי שבנוי גרוע גורם ליותר תקלות מהתקלה שהוא אמור לשרוד. אז הגרסה הבוגרת של התחום הזה היא לא לחסל כל נקודת כשל יחידה. היא לדעת איפה כל אחת מהן נמצאת, להחליט במכוון אילו מהן מקובלות, ולוודא שכשאחת באמת נופלת אתה מגלה את זה מהתראה ולא מלקוח.\n\nחברה הריצה שכבת web מיותרת בשלושה אזורי זמינות, מאחורי מאזן עומסים, עם סקייל אוטומטי, מהונדס לעילא. כל זה דיבר עם מופע Postgres אחד באזור אחד בלי שכפול, כי ככה זה הוגדר זמנית לפני שנתיים. השרת הפיזי שמתחת לאותו מופע נפל ביום שלישי בבוקר והמוצר היה מושבת לגמרי שעתיים וארבעים דקות בזמן ששחזור מהגיבוי הלילי רץ — מה שגם אמר תשע שעות של אובדן נתונים לכל מה שנכתב מאז התצלום. כל ההנדסה סביב שכבת ה-web הייתה זהירה ולגמרי לא רלוונטית. מסד נתונים מנוהל עם מעבר אוטומטי לגיבוי היה עולה בערך תשעים דולר יותר בחודש.\n\nהתרגיל הזול ביותר כאן לוקח עשר דקות ואפס קוד. תרשום כל רכיב שמסלול הבקשה נוגע בו: DNS, CDN, מאזן עומסים, האפליקציה, מסד הנתונים, הקאש, ספק ההזדהות, ספק התשלומים, שירות המיילים. לכל אחד, תענה מה קורה אם הוא נעלם עכשיו, ואיך היית יודע. התוצאות בדרך כלל לא נוחות ולעיתים קרובות זולות לתיקון — עותק קריאה, אזור שני ל-DNS, מסלול התדרדרות מבוקרת כשהקאש קר. סוכן AI לעולם לא יעלה את זה מעצמו, כי שום דבר מזה לא מופיע בקוד שהוא מסתכל עליו."},

"Technical debt": {
 "en": "Debt is not bad code. It is a conscious decision to move fast now and pay later, which is frequently the correct decision, because a perfect system that ships in eighteen months earns nothing and teaches you nothing. The hardcoded value, the copy-pasted function, the missing test on a path you are about to replace anyway — all of these are reasonable trades. Debt becomes dangerous at the moment it stops being a decision and becomes the accumulated residue of decisions nobody remembers making. The interest is not paid in guilt; it is paid in the extra hours every future change costs, and that number compounds quietly.\n\nA team shipped a billing feature in four days by hardcoding three pricing tiers across eleven files. Two months later, adding a fourth tier meant finding all eleven — they found nine. Two customers were billed on the wrong tier for five weeks, which was found by a customer and not by them, and the cleanup took nine days. The original shortcut saved perhaps two days. Contrast that with a different shortcut by the same team: skipping an admin UI and editing a config file by hand for the first year. That debt cost nothing, because it was isolated in one place, touched nobody else's work, and was replaced in an afternoon when it finally mattered.\n\nAI changes the arithmetic. Generating two thousand lines of plausible code takes a minute and reading them takes an hour, so debt now accumulates faster than anyone's capacity to review it. The practical defence is to refuse to merge what you cannot read, and to notice the specific smell of agent debt: the same logic implemented three slightly different ways in three files, because each generation started fresh. Deleting code is still the only real repayment. Ask what can be removed before asking what should be added — the fastest way to pay down debt is to have less code to owe it on.",
 "he": "חוב טכני הוא לא קוד גרוע. הוא החלטה מודעת לזוז מהר עכשיו ולשלם אחר כך, וזו לעיתים קרובות ההחלטה הנכונה, כי מערכת מושלמת שיוצאת בעוד שמונה עשר חודשים לא מרוויחה כלום ולא מלמדת אותך כלום. הערך הקשיח בקוד, הפונקציה שהועתקה, הבדיקה החסרה על מסלול שאתה ממילא עומד להחליף — כל אלה עסקאות סבירות. החוב הופך למסוכן ברגע שהוא מפסיק להיות החלטה והופך למשקע מצטבר של החלטות שאף אחד לא זוכר שקיבל. הריבית לא משולמת באשמה; היא משולמת בשעות הנוספות שכל שינוי עתידי עולה, והמספר הזה מצטבר בשקט.\n\nצוות שחרר פיצ׳ר חיוב בארבעה ימים על ידי הטמעה קשיחה של שלוש רמות תמחור באחד עשר קבצים. חודשיים אחר כך, הוספת רמה רביעית דרשה למצוא את כל אחד עשר — הם מצאו תשעה. שני לקוחות חויבו ברמה הלא נכונה במשך חמישה שבועות, מה שהתגלה על ידי לקוח ולא על ידם, והניקוי לקח תשעה ימים. קיצור הדרך המקורי חסך אולי יומיים. תשווה את זה לקיצור דרך אחר של אותו צוות: לוותר על ממשק ניהול ולערוך קובץ קונפיגורציה ידנית בשנה הראשונה. החוב הזה לא עלה כלום, כי הוא היה מבודד במקום אחד, לא נגע בעבודה של אף אחד אחר, והוחלף תוך אחר צהריים כשזה סוף סוף היה חשוב.\n\nAI משנה את החשבון. לייצר אלפיים שורות של קוד משכנע לוקח דקה ולקרוא אותן לוקח שעה, אז חוב מצטבר עכשיו מהר יותר מהיכולת של מישהו לסקור אותו. ההגנה המעשית היא לסרב למזג מה שאתה לא מצליח לקרוא, ולזהות את הריח הספציפי של חוב מסוכן: אותה לוגיקה ממומשת בשלוש דרכים קצת שונות בשלושה קבצים, כי כל ייצור התחיל מאפס. מחיקת קוד היא עדיין הפירעון האמיתי היחיד. תשאל מה אפשר להוריד לפני שאתה שואל מה להוסיף — הדרך המהירה ביותר להחזיר חוב היא שיהיה פחות קוד שחייבים עליו."},
}


# =====================================================
# Concrete examples. cap is bilingual; code stays English.
# =====================================================

EXAMPLES_FIX = {

"The cloud": {"cap": {"en": "The bill is what you left running, not what you used",
                      "he": "החשבון הוא מה שהשארת דולק, לא מה שהשתמשת בו"},
 "code": "# the $14 you planned for:\nt4g.small  x1  730h x $0.0168/h  =  $12.26\n\n# the $326 you did not:\nALB                730h x $0.0225/h   =  $16.43  # idle or not\nNAT gateway        730h x $0.045/h    =  $32.85  # + data\nNAT data processed 400 GB x $0.045    =  $18.00\nEgress to internet 400 GB x $0.09     =  $36.00  # every night\ng4dn.xlarge        504h x $0.526/h    = $265.10  # weekend test, still on\n\n# find yours before the invoice does:\naws ec2 describe-instances --filters Name=instance-state-name,Values=running \\\n  --query 'Reservations[].Instances[].[InstanceId,InstanceType,LaunchTime]' --output table\naws ec2 describe-addresses --query 'Addresses[?!AssociationId]'  # unattached IPs, billed\naws ce get-cost-and-usage --time-period Start=2026-08-01,End=2026-09-01 \\\n  --granularity MONTHLY --metrics UnblendedCost --group-by Type=DIMENSION,Key=SERVICE"},

"AWS / Azure / GCP": {"cap": {"en": "Same container, three vendors, one PaaS",
                              "he": "אותו קונטיינר, שלושה ספקים, ופלטפורמה אחת"},
 "code": "# GCP - one command, it builds and runs your container\ngcloud run deploy api --source . --region europe-west1 --allow-unauthenticated\n\n# Azure - same idea, different nouns\naz containerapp up -n api -g my-rg --source . --ingress external\n\n# AWS - the same result needs a VPC, subnets, an ALB, a task definition,\n# an IAM execution role and a service. Copilot hides most of it:\ncopilot init --app shop --name api --type 'Load Balanced Web Service' --deploy\n\n# ...or skip all three while the app is small:\nfly launch --now            # reads your Dockerfile, gives you a URL\n\n# the portability that matters is not the provider - it is this file:\n#   Dockerfile  + 12-factor config from env vars = you can leave any of them"},

"EC2 / VM vs Lambda / serverless": {"cap": {"en": "Run the arithmetic before you pick",
                                            "he": "לעשות את החשבון לפני שבוחרים"},
 "code": "# Lambda: $0.20 per 1M requests + $0.0000166667 per GB-second\n\n# A) webhook receiver - 30k calls/mo, 200ms, 256MB\n#    30_000 x 0.2s x 0.25GB = 1,500 GB-s  -> $0.025 + $0.006  =  ~$0.03/mo\n#    same thing on a t4g.micro running 24/7                   =  ~$6.13/mo\n\n# B) image processing - 2M calls/mo, 2s, 1024MB\n#    2_000_000 x 2s x 1GB  = 4,000,000 GB-s -> $66.67 + $0.40 =  ~$67/mo\n#    one busy t4g.medium doing the same steady load           =  ~$24.53/mo\n\n# the crossover is traffic SHAPE, not size:\n#   spiky + mostly idle  -> serverless\n#   steady + constant    -> a machine\n\n# and check these before choosing serverless:\n#   max execution time?  a filesystem?  a DB pool?  p99 with a cold start?"},

"Scaling up vs out": {"cap": {"en": "Up is a config line. Out is a code audit.",
                              "he": "אנכי זה שורת קונפיגורציה. אופקי זו ביקורת קוד."},
 "code": "# UP - no code changes, 15 min of downtime, hard ceiling later\naws rds modify-db-instance --db-instance-identifier prod \\\n  --db-instance-class db.r6g.4xlarge --apply-immediately   # 4 -> 16 vCPU\n\n# OUT - one number in a file...\nreplicas: 3\n\n# ...and this is what that number breaks. grep before you scale:\nrg 'new Map\\(|= \\{\\}' src/ -g '!*.test.*'   # module-level caches\nrg 'setInterval|node-cron'                    # cron now runs 3x at once\nrg 'fs\\.write|\\./uploads'                     # local disk per instance\nrg 'express-session' -A3                      # MemoryStore = random logouts\n\n# and before either one, check the actual bottleneck:\nEXPLAIN ANALYZE SELECT ... ;   # a missing index beats both, for free"},

"Monolith vs microservices": {"cap": {"en": "The same feature, before and after the split",
                                      "he": "אותו פיצ׳ר, לפני הפיצול ואחרי"},
 "code": "// MONOLITH - one process, one transaction, one stack trace\nawait db.$transaction(async (tx) => {\n  const order = await tx.order.create({ data })\n  await tx.stock.decrement({ where: { sku }, by: qty })   // both, or neither\n})\n\n// MICROSERVICES - the same two lines, now over the network\nconst order = await orders.create(data)                   // may time out\ntry {\n  await fetch(INVENTORY_URL, { method: 'POST', body, signal: AbortSignal.timeout(2000) })\n} catch (e) {\n  await orders.markPendingStock(order.id)   // no rollback exists. you own this now.\n  await outbox.enqueue('stock.decrement', { sku, qty, orderId: order.id })\n}\n// + retries, + idempotency, + a saga to undo it, + tracing across both\n// decides it: will these two ever be DEPLOYED separately, by different people?"},

"Single point of failure": {"cap": {"en": "Ten minutes, no code: list it and price it",
                                    "he": "עשר דקות, בלי קוד: לרשום ולתמחר"},
 "code": "component        redundant?   if it dies right now        how I'd find out\n---------------  -----------  --------------------------  ------------------\nDNS              yes (4 NS)   nothing                     -\nCDN              yes          slower, still up            latency alert\nload balancer     yes (3 AZ)   nothing                     -\napp instances    yes (x3)     one third of capacity       healthcheck alert\nPostgres         NO  <-- here total outage + data loss     a customer calls\nRedis (sessions) NO  <-- here everyone logged out          a customer calls\nStripe           n/a          no checkout                 their status page\n\n# check the one that matters, right now:\naws rds describe-db-instances --db-instance-identifier prod \\\n  --query 'DBInstances[].[MultiAZ,BackupRetentionPeriod,LatestRestorableTime]'\n# [false, 1, ...]  -> up to 24h of data loss, ~$90/mo to fix"},

"Technical debt": {"cap": {"en": "Interest, measured in files you must not miss",
                           "he": "ריבית, נמדדת בקבצים שאסור לפספס"},
 "code": "# the 4-day shortcut: three tiers, hardcoded\nrg -n \"'(free|pro|team)'\" src/ | wc -l\n47        # across 11 files\n\n# adding a 4th tier means finding all 11. they found 9.\n# two customers billed wrong for 5 weeks.\n\n# the same shortcut, isolated - costs nothing:\n# config/pricing.json is edited by hand. one file. no admin UI.\n\n# the agent-debt smell: same idea, generated three times\nrg -n 'function (formatPrice|priceLabel|toDisplayPrice)' src/\nsrc/billing/format.ts:12\nsrc/ui/cart.tsx:88\nsrc/emails/receipt.ts:5      # three impls, two of them round differently\n# repayment is deletion, not refactoring: keep one, import it everywhere"},
}


# =====================================================
# Hebrew corrections. Only terms whose Hebrew was wrong,
# stiff, or used a word Israeli developers do not say.
# =====================================================

HE_FIX = {

# "דלי" is a literal translation of bucket that nobody says; "פריסה" -> "דיפלוי".
"S3 / object storage": {
 "d": {"he": "באקט (bucket) לקבצים — תמונות, העלאות, גיבויים — שנגיש דרך כתובת URL. לא מסד נתונים ולא דיסק."},
 "w": {"he": "אף פעם לא לשמור העלאות על הדיסק של השרת. זה נעלם בדיפלוי הבא או ברגע שיש אינסטנס שני."}},

# "cold start" left bare in Hebrew; "מחויבת תמיד" reads like a translation error.
"EC2 / VM vs Lambda / serverless": {
 "w": {"he": "סרברלס זול כשאין עומס, ומשלם על זה בקולד-סטארט (cold start). מכונה וירטואלית צפויה — ומחויבת גם כשהיא לא עושה כלום."}},

# "התרופה המילולית" is not Hebrew anyone says.
"Container / Docker": {
 "w": {"he": "זו בדיוק התשובה ל״אצלי זה עובד״ — כי הסביבה עצמה נשלחת יחד עם הקוד."}},

# Israeli developers say "דיפלוי", not "פריסה".
"Deploy": {
 "t": {"he": "דיפלוי (Deploy)"},
 "d": {"he": "לקחת את הגרסה החדשה ולהפוך אותה לזו שהמשתמשים מגיעים אליה."},
 "w": {"he": "דיפלויים קטנים ותכופים בטוחים יותר מגדולים ונדירים. פחות שינויים = פחות לחפש כשמשהו נשבר."}},

# "דחיפה"/"בנייה"/"פריסה" -> what people actually say; "בטוח בעצמו" needed a hyphen to parse.
"CI/CD": {
 "d": {"he": "אוטומציה שרצה בכל פוש: התקנה, בדיקות, בילד, ואם הכל ירוק — דיפלוי."},
 "w": {"he": "זה המעקה שמונע מקומיט בטוח-בעצמו של AI להגיע לפרודקשן בלי בדיקות."}},

# "אינו ניתן לתיקון" is stiff; "תרשום" is the wrong verb for logging.
"Logs & monitoring": {
 "w": {"he": "בלי לוגים, באג בפרודקשן הוא באג שאי אפשר לתקן. תוציא ללוג את הקלט של כל דבר שאי אפשר לשחזר מקומית."}},

# "חסר מצב" is a dictionary word; the term used in speech is "סטייטלס".
"Scaling up vs out": {
 "w": {"he": "אנכי הוא תיקון בלחיצה עם תקרה. אופקי הוא בלי תקרה, אבל מחייב אותך להיות סטייטלס."}},

"Stateless": {
 "t": {"he": "סטייטלס (Stateless)"},
 "w": {"he": "התכונה היחידה שמאפשרת סקייל אופקי. דוחפים את הסטייט למסד הנתונים או ל-Redis."}},

# "עובד" for worker reads as a person; everyone says "וורקר".
"Queue / worker": {
 "t": {"he": "תור / וורקר (worker)"},
 "d": {"he": "במקום לעשות עבודה איטית בתוך הבקשה, שמים משימה בתור ווורקר מטפל בה אחר כך."},
 "w": {"he": "מיילים, עיבוד וידאו, הפקת דוחות. המשתמש מקבל תגובה מיידית והעבודה עדיין קורית."}},

# "מיקרו-שירותים" is not what anyone says; "ממירים" is the wrong verb.
"Monolith vs microservices": {
 "t": {"he": "מונוליט מול מיקרו-סרוויסים"},
 "d": {"he": "אפליקציה אחת שעושים לה דיפלוי, מול הרבה שירותים קטנים שמדברים דרך הרשת."},
 "w": {"he": "מיקרו-סרוויסים מחליפים מורכבות של קוד במורכבות של רשת. תתחיל כמונוליט. כמעט תמיד."}},

# "המוות שלו" is a literal translation; "בסיס נתונים" -> "מסד נתונים" (consistent with the rest of the course).
"Single point of failure": {
 "d": {"he": "כל רכיב יחיד שנפילתו מפילה את כל המערכת."},
 "w": {"he": "בדרך כלל מסד הנתונים. בדרך כלל אף אחד לא שם לב עד התקלה האמיתית הראשונה."}},

"Technical debt": {
 "w": {"he": "AI הופך צבירת חוב לקלה מדי. מחיקת קוד היא עדיין הדרך היחידה להחזיר אותו."}},
}
