# -*- coding: utf-8 -*-
"""Widening pass 2: richer deep-dives, missing examples and Hebrew fixes
for the Data, Languages and Memory modules.

DETAIL_FIX   -> replaces DETAIL entries wholesale (3 paragraphs, ~300-380 words)
EXAMPLES_FIX -> adds/overrides EXAMPLES entries
HE_FIX       -> targeted Hebrew corrections for t / d / w
"""

DETAIL_FIX = {

# ============================== DATA ==============================

"Database": {
 "en": "A database is not a place to put data. It is a set of promises about what happens when things go wrong: that a write either landed completely or not at all, that two people writing in the same instant cannot interleave into nonsense, that a power cut halfway through leaves a consistent picture rather than a torn one. Those promises are the product. Storage itself is the easy part — every filesystem already does storage.\n\nTake a small booking tool that kept appointments in appointments.json, rewritten in full on every save. It was correct for four months with one receptionist. The day a second person started, two saves landed thirty milliseconds apart: the second had read the file before the first wrote it, so it wrote back a picture of the world that did not contain the first booking. No error appeared, the JSON stayed valid, and one appointment simply evaporated. Nobody found out until a customer arrived for a slot that no longer existed. Postgres would have refused to lose it — the second writer would have waited its turn, or been told the row had changed underneath it.\n\nWhen an agent scaffolds a project, the fastest thing it can reach for is a file or an in-process array, and it will, unless you say otherwise. So ask two questions on day one: where does this data live after the process restarts, and what happens when two requests write to it at the same moment. If the answer is a file, a global variable, or we will add a database later, you are building on the version that fails quietly. Switching to a real database at the start costs an hour. Switching after a hundred functions have been written against a file costs a week — and you will not be able to tell which of the records you already have were corrupted along the way.",
 "he": "דאטהבייס הוא לא מקום לשים בו נתונים. הוא אוסף הבטחות לגבי מה קורה כשמשהו משתבש: שכתיבה או נכנסה במלואה או בכלל לא, ששני אנשים שכותבים באותו רגע לא יכולים להשתרבב אחד לשני לג׳יבריש, ושהפסקת חשמל באמצע משאירה תמונה עקבית ולא תמונה קרועה. ההבטחות האלה הן המוצר. האחסון עצמו הוא החלק הקל — כל מערכת קבצים כבר יודעת לאחסן.\n\nקח כלי קטן לזימון תורים ששמר פגישות ב-appointments.json, ונכתב מחדש במלואו בכל שמירה. הוא היה תקין ארבעה חודשים עם פקידה אחת. ביום שבו הצטרפה פקידה שנייה, שתי שמירות נחתו בהפרש של שלושים מילישניות: השנייה קראה את הקובץ לפני שהראשונה כתבה, ולכן כתבה בחזרה תמונת עולם שלא הכילה את הפגישה הראשונה. שום שגיאה לא הופיעה, ה-JSON נשאר תקין, ופגישה אחת פשוט התאדתה. אף אחד לא גילה עד שלקוח הגיע לתור שכבר לא היה קיים. פוסטגרס היה מסרב לאבד אותה — הכותב השני היה ממתין לתורו, או מקבל הודעה שהשורה השתנתה מתחתיו.\n\nכשסוכן AI מקים פרויקט, הדבר המהיר ביותר עבורו הוא לשמור לקובץ או למערך בזיכרון התהליך, וזה מה שהוא יעשה אם לא תגיד אחרת. אז תשאל שתי שאלות כבר ביום הראשון: איפה הנתונים האלה חיים אחרי שהתהליך עולה מחדש, ומה קורה כששתי בקשות כותבות אליהם באותו רגע. אם התשובה היא קובץ, משתנה גלובלי, או ״נוסיף דאטהבייס אחר כך״ — אתה בונה על הגרסה שנכשלת בשקט. מעבר לדאטהבייס אמיתי בהתחלה עולה שעה. מעבר אחרי שנכתבו מאה פונקציות מול קובץ עולה שבוע — ולא תוכל לדעת אילו מהרשומות שכבר יש לך נפגמו בדרך."},

"SQL vs NoSQL": {
 "en": "The real difference is not tables versus documents. It is where the shape of your data is enforced. SQL puts the rules in one place that the database owns and applies to every writer, forever, including the script someone runs by hand at midnight. NoSQL moves those rules into every piece of code that touches the data, which means they hold exactly as long as every developer and every agent remembers them.\n\nA sales team's CRM stored 40,000 customer documents in MongoDB over three years. Nothing enforced the shape, so the shape drifted. Phone was a string in the 2023 documents, an array of strings after someone added second numbers, and an object with type and value after a rewrite. Country lived at the top level in some documents and under address in others, sometimes capitalised. When finance asked for revenue by country, the query returned 11,000 customers instead of 40,000 — the rest simply did not match the field path. The fix was a 300-line normalisation script and two days of manually deciding what the ambiguous rows had meant.\n\nDefault to Postgres. It is the boring answer and it is right for almost everything an AI-assisted builder ships, because the constraint you did not write is the one that saves you. Reach for a document store when the data genuinely has no stable shape — raw event payloads, scraped pages, third-party blobs you only ever read whole. The question to put to an agent that suggests Mongo for your app: which of my entities has a shape that will really differ row to row? If the honest answer is none, you are trading away foreign keys, unique constraints and joins in exchange for being allowed to misspell a field name without anyone stopping you. For almost any product with users, orders and payments in it, that is a bad trade made on the first day and paid for on the four hundredth.",
 "he": "ההבדל האמיתי הוא לא טבלאות מול מסמכים. הוא איפה נאכפת הצורה של הנתונים שלך. SQL שם את החוקים במקום אחד שהדאטהבייס מחזיק ומחיל על כל כותב, לתמיד, כולל הסקריפט שמישהו מריץ ידנית בחצות. NoSQL מעביר את החוקים האלה לכל פיסת קוד שנוגעת בנתונים, כלומר הם מחזיק בדיוק כל עוד כל מפתח וכל סוכן זוכר אותם.\n\nמערכת CRM של צוות מכירות שמרה 40,000 מסמכי לקוח במונגו לאורך שלוש שנים. שום דבר לא אכף את הצורה, ולכן הצורה נסחפה. phone היה מחרוזת במסמכים מ-2023, מערך של מחרוזות אחרי שמישהו הוסיף מספר שני, ואובייקט עם type ו-value אחרי שכתוב. country ישב ברמה העליונה בחלק מהמסמכים ותחת address באחרים, לפעמים באות גדולה. כשהכספים ביקשו הכנסות לפי מדינה, הקווירי החזיר 11,000 לקוחות במקום 40,000 — השאר פשוט לא התאימו לנתיב השדה. התיקון היה סקריפט נרמול של 300 שורות ויומיים של החלטות ידניות מה השורות המעורפלות בעצם אמרו.\n\nברירת המחדל היא פוסטגרס. זו התשובה המשעממת והיא הנכונה כמעט לכל מה שבונה עם AI משחרר, כי האילוץ שלא כתבת הוא זה שמציל אותך. לך לדוקיומנט סטור כשלנתונים באמת אין צורה יציבה — פיילודים גולמיים של אירועים, דפים שנגרדו, בלובים של צד שלישי שאתה רק קורא בשלמותם. השאלה שצריך לשאול סוכן שמציע לך מונגו: לאיזו ישות אצלי הצורה באמת משתנה משורה לשורה? אם התשובה הכנה היא ״לאף אחת״, אתה מוותר על מפתחות זרים, אילוצי ייחודיות וג׳וינים בתמורה לזכות לכתוב שם שדה עם שגיאת כתיב בלי שאף אחד יעצור אותך. כמעט לכל מוצר שיש בו משתמשים, הזמנות ותשלומים, זו עסקה גרועה שנעשית ביום הראשון ומשלמים עליה ביום הארבע מאות."},

"Schema": {
 "en": "A schema is the only validation that cannot be forgotten. Checks written in application code live on the paths that call them; a database constraint applies to every writer that ever existed — your API, the admin panel, the background job, the agent's new endpoint, and the person pasting an UPDATE into a console. Its second job is communication: a well-named schema tells the next reader what the system believes about the world, which fields are optional, which must be unique, and what has to exist before what.\n\nA subscription product stored prices in a column typed double precision because that is what the scaffolding generated. For eighteen months the invoices were right to the cent. Then a plan changed to 19.99 with a 3-for-2 discount, and the stored total came out 39.980000000000004. It rendered as 39.98, it summed in reports as 39.980000000000004, and the monthly revenue report disagreed with Stripe by a few cents — which took a finance analyst three days to chase, because a few cents looks like a rounding convention, not a bug. The column should have been integer cents, or numeric. A CHECK constraint and the right type would have made the wrong value unrepresentable.\n\nAgents write permissive schemas. Left alone they will give you text columns that allow anything, nullable everywhere because nullable never fails an insert, and no unique constraint because a unique constraint can make a seed script crash. Read the CREATE TABLE before you accept it, and ask of each column: can this really be empty, can two rows really share this value, and is this type able to represent a value that is nonsense. Money as a float, a date as text, a status as free text instead of a constrained set — each of those is a support ticket that has not happened yet.",
 "he": "סכמה היא האימות היחיד שאי אפשר לשכוח. בדיקות שכתובות בקוד האפליקציה חיות רק בנתיבים שקוראים להן; אילוץ בדאטהבייס חל על כל כותב שהיה אי פעם — ה-API שלך, פאנל האדמין, הג׳וב ברקע, האנדפוינט החדש שהסוכן הוסיף, והאדם שמדביק UPDATE לקונסול. התפקיד השני שלה הוא תקשורת: סכמה עם שמות טובים מספרת לקורא הבא במה המערכת מאמינה לגבי העולם, אילו שדות אופציונליים, מה חייב להיות ייחודי, ומה חייב להתקיים לפני מה.\n\nמוצר מנויים שמר מחירים בעמודה מטיפוס double precision, כי זה מה שהסקאפולדינג ייצר. שמונה עשר חודשים החשבוניות היו נכונות עד האגורה. ואז תוכנית השתנתה ל-19.99 עם הנחת 3 ב-2, והסכום שנשמר יצא 39.980000000000004. זה הוצג כ-39.98, הסתכם בדוחות כ-39.980000000000004, ודוח ההכנסות החודשי לא הסכים עם סטרייפ בכמה אגורות — מה שלקח לאנליסטית כספים שלושה ימים לרדוף אחריו, כי כמה אגורות נראות כמו מוסכמת עיגול ולא כמו באג. העמודה הייתה צריכה להיות integer של סנטים, או numeric. אילוץ CHECK והטיפוס הנכון היו הופכים את הערך השגוי לבלתי ניתן לייצוג.\n\nסוכנים כותבים סכמות מתירניות. אם לא תתערב תקבל עמודות text שמקבלות הכל, nullable בכל מקום כי nullable אף פעם לא מפיל INSERT, ובלי אילוץ ייחודיות כי אילוץ ייחודיות עלול להפיל סקריפט seed. תקרא את ה-CREATE TABLE לפני שאתה מאשר אותו, ותשאל על כל עמודה: האם זה באמת יכול להיות ריק, האם שתי שורות באמת יכולות לחלוק את הערך הזה, והאם הטיפוס הזה מסוגל לייצג ערך שהוא שטות. כסף כ-float, תאריך כטקסט, סטטוס כטקסט חופשי במקום קבוצה סגורה — כל אחד מאלה הוא פנייה לתמיכה שעוד לא קרתה."},

"Query": {
 "en": "You describe what you want; the database decides how to get it. That separation is the whole power of SQL and also the reason performance can collapse overnight without anyone touching the code — the planner simply looked at the current size and distribution of the data and chose a different strategy than it chose last month.\n\nAn internal orders page ran a single query: filter by customer email, sort by date, take twenty. With 500 rows in the table it answered in 80 milliseconds and nobody thought about it again. At 50,000 rows it took nine seconds and the page started timing out. The code had not changed. EXPLAIN ANALYZE gave the answer in one line: Seq Scan on orders. There was an index on email, but the query filtered on lower(email) because someone had made the search case-insensitive, and an index on email cannot answer a question about lower(email). The database read all 50,000 rows, lowercased every one, then sorted the survivors. An index on lower(email) brought it back to four milliseconds.\n\nThe habit worth building is cheap: for anything on a page a user waits for, put EXPLAIN ANALYZE in front of the query once and read the first line. Seq Scan on a large table means it is reading everything. An agent will write queries that are correct and never tell you they are slow, because at development-time row counts everything is instant — a hundred seed rows hide every mistake of this kind. Before you ship, load a realistic number of rows, run the page, and look at the plan for the two or three queries that matter. That is a ten-minute exercise that catches the single most common cause of a site falling over. And when a page that was fine last month is suddenly slow with no deploy behind it, the plan is the first place to look, not the code.",
 "he": "אתה מתאר מה אתה רוצה; הדאטהבייס מחליט איך להשיג את זה. ההפרדה הזו היא כל הכוח של SQL וגם הסיבה שביצועים יכולים לקרוס בן לילה בלי שאף אחד נגע בקוד — הפלאנר פשוט הסתכל על הגודל והפיזור הנוכחיים של הנתונים ובחר אסטרטגיה אחרת מזו שבחר בחודש שעבר.\n\nדף הזמנות פנימי הריץ קווירי אחד: לסנן לפי אימייל של לקוח, למיין לפי תאריך, לקחת עשרים. עם 500 שורות בטבלה הוא ענה ב-80 מילישניות ואף אחד לא חשב עליו שוב. ב-50,000 שורות הוא לקח תשע שניות והדף התחיל ליפול בטיים-אאוט. הקוד לא השתנה. EXPLAIN ANALYZE נתן את התשובה בשורה אחת: Seq Scan on orders. היה אינדקס על email, אבל הקווירי סינן לפי lower(email) כי מישהו הפך את החיפוש לחסר רגישות לאותיות גדולות, ואינדקס על email לא יכול לענות על שאלה לגבי lower(email). הדאטהבייס קרא את כל 50,000 השורות, הוריד לאותיות קטנות כל אחת מהן, ואז מיין את מה שנשאר. אינדקס על lower(email) החזיר את זה לארבע מילישניות.\n\nההרגל ששווה לפתח זול: לכל דבר בדף שמשתמש ממתין לו, תשים EXPLAIN ANALYZE לפני הקווירי פעם אחת ותקרא את השורה הראשונה. Seq Scan על טבלה גדולה אומר שהוא קורא הכל. סוכן יכתוב קווריז נכונים ולעולם לא יגיד לך שהם איטיים, כי בכמויות השורות של סביבת הפיתוח הכל מיידי — מאה שורות seed מסתירות כל טעות מהסוג הזה. לפני שאתה עולה לאוויר, תטען כמות שורות ריאליסטית, תריץ את הדף, ותסתכל על הפלאן של שניים-שלושה הקווריז שחשובים. זה תרגיל של עשר דקות שתופס את הגורם הנפוץ ביותר לנפילת אתר. וכשדף שהיה תקין בחודש שעבר פתאום איטי בלי שום דיפלוי מאחוריו, הפלאן הוא המקום הראשון להסתכל בו, לא הקוד."},

"Index": {
 "en": "An index is a pre-sorted copy of one or more columns, kept up to date on every write, that lets the database jump straight to the rows it needs instead of reading the table. The trade is explicit: you are spending disk space and write speed to buy read speed. Every insert, update and delete has to maintain every index on that table.\n\nBoth halves of that trade show up in practice. A support dashboard filtered tickets by assignee and sorted by created_at. On 100,000 rows it took 340 milliseconds; a composite index on (assignee_id, created_at DESC) took it to 2 milliseconds, because the index already holds the rows in exactly the order the query asks for, so there is nothing left to sort. The other half: an events table on the same system had accumulated nine indexes, added one at a time by people fixing one report each. A nightly bulk import that used to load 40,000 rows a minute had dropped to 6,000, because each row now meant ten writes instead of one. Dropping four indexes nobody's queries used restored it.\n\nThe rule to carry: index what you filter by and sort by, in that order, and only for queries you actually run. When an agent tells you a page is slow and proposes adding indexes, ask which specific query each index serves — an index that does not match the leading columns of a real WHERE clause is pure cost. And ask what it will do to writes on a table that takes heavy inserts. The highest-value version of this skill is unglamorous: look at the two or three slowest queries, add the two or three indexes that match them, and measure again. Not index everything and hope. Then look again in a few months, because the plan the database chooses is a function of how much data you had on the day it chose.",
 "he": "אינדקס הוא עותק ממוין מראש של עמודה אחת או יותר, שמתעדכן בכל כתיבה, ומאפשר לדאטהבייס לקפוץ ישר לשורות שהוא צריך במקום לקרוא את הטבלה. העסקה מפורשת: אתה משלם במקום בדיסק ובמהירות כתיבה כדי לקנות מהירות קריאה. כל INSERT, UPDATE ו-DELETE חייב לתחזק כל אינדקס על הטבלה הזו.\n\nשני הצדדים של העסקה מופיעים בשטח. דשבורד תמיכה סינן קריאות לפי מטפל ומיין לפי created_at. על 100,000 שורות זה לקח 340 מילישניות; אינדקס מורכב על (assignee_id, created_at DESC) הוריד את זה ל-2 מילישניות, כי האינדקס כבר מחזיק את השורות בדיוק בסדר שהקווירי מבקש, ולא נשאר מה למיין. הצד השני: טבלת events באותה מערכת צברה תשעה אינדקסים, שנוספו אחד-אחד על ידי אנשים שתיקנו דוח אחד כל אחד. ייבוא לילי בבאטצ׳ים שפעם טען 40,000 שורות בדקה ירד ל-6,000, כי כל שורה עכשיו פירושה עשר כתיבות במקום אחת. מחיקת ארבעה אינדקסים שאף קווירי לא השתמש בהם החזירה את המצב לקדמותו.\n\nהכלל שכדאי לקחת: לאנדקס את מה שמסננים לפיו וממיינים לפיו, בסדר הזה, ורק לקווריז שבאמת רצים. כשסוכן אומר לך שדף איטי ומציע להוסיף אינדקסים, תשאל איזה קווירי ספציפי כל אינדקס משרת — אינדקס שלא מתאים לעמודות הפותחות של WHERE אמיתי הוא עלות נטו. ותשאל מה זה יעשה לכתיבות בטבלה שמקבלת הרבה INSERTים. הגרסה הכי שווה של המיומנות הזו היא לא זוהרת: להסתכל על שניים-שלושה הקווריז האיטיים ביותר, להוסיף את שניים-שלושה האינדקסים שמתאימים להם, ולמדוד שוב. לא לאנדקס הכל ולקוות. ואז להסתכל שוב בעוד כמה חודשים, כי הפלאן שהדאטהבייס בוחר הוא פונקציה של כמות הנתונים שהייתה ביום שבו הוא בחר."},

"Migration": {
 "en": "A migration turns a schema change from an event into an artifact. It is a numbered file, reviewed like code, applied in the same order in every environment, and recorded so it never runs twice. That is what keeps your laptop, staging and production describing the same world — and it is why the bug you reproduce locally is the same bug that happens live.\n\nA team added a not-null status column to orders. In staging someone did it by hand in a GUI, on a table with 900 rows, and it took no time at all. The migration that later ran against production hit 12 million rows, rewrote the whole table to fill the default, and held an exclusive lock for four minutes. Checkout returned 500s for those four minutes, at nine in the evening. The safe version is three migrations, not one: add the column as nullable, backfill it in batches while the app keeps running, then add the not-null constraint once the data is already clean. The difference between four minutes of downtime and zero was entirely in the shape of the change, not in the change itself.\n\nWhen you let an agent change your schema, the thing to insist on is that the change arrives as a new file in the migrations folder and never as an edit to a file that has already run somewhere. Production applied 0007 and will never look at it again, so editing 0007 means your laptop and production now disagree silently. Two questions are worth asking about every migration before it runs: does this lock a big table, and can I undo it. Adding a column and adding an index concurrently are cheap. Renaming a column, changing a type, and dropping anything are the ones that need a plan and a deploy window.",
 "he": "מיגרציה הופכת שינוי סכמה מאירוע לארטיפקט. היא קובץ ממוספר, עובר ריוויו כמו קוד, מורץ באותו סדר בכל סביבה, ונרשם כדי שלא ירוץ פעמיים. זה מה ששומר על המחשב שלך, הסטייג׳ינג והפרודקשן מתארים את אותו עולם — ובגלל זה הבאג שאתה משחזר מקומית הוא אותו באג שקורה באוויר.\n\nצוות הוסיף עמודת status עם NOT NULL לטבלת orders. בסטייג׳ינג מישהו עשה את זה ידנית בממשק גרפי, על טבלה של 900 שורות, וזה לקח אפס זמן. המיגרציה שרצה אחר כך בפרודקשן פגשה 12 מיליון שורות, כתבה מחדש את כל הטבלה כדי למלא את ברירת המחדל, והחזיקה נעילה בלעדית ארבע דקות. הצ׳קאאוט החזיר 500 בארבע הדקות האלה, בתשע בערב. הגרסה הבטוחה היא שלוש מיגרציות ולא אחת: להוסיף את העמודה כ-nullable, למלא אותה בבאטצ׳ים בזמן שהאפליקציה ממשיכה לרוץ, ואז להוסיף את אילוץ ה-NOT NULL כשהנתונים כבר נקיים. ההבדל בין ארבע דקות השבתה לאפס היה כולו בצורת השינוי, לא בשינוי עצמו.\n\nכשאתה נותן לסוכן לשנות לך את הסכמה, הדבר שצריך להתעקש עליו הוא שהשינוי מגיע כקובץ חדש בתיקיית המיגרציות ולעולם לא כעריכה של קובץ שכבר רץ אי שם. הפרודקשן הריץ את 0007 ולא יסתכל עליו שוב, אז עריכה של 0007 אומרת שהמחשב שלך והפרודקשן חלוקים בשקט. שתי שאלות שוות שאילה על כל מיגרציה לפני שהיא רצה: האם זה נועל טבלה גדולה, והאם אפשר לבטל. הוספת עמודה והוספת אינדקס עם CONCURRENTLY הן זולות. שינוי שם של עמודה, שינוי טיפוס, וכל מחיקה — אלה שצריכות תוכנית וחלון דיפלוי."},

"Transaction": {
 "en": "A transaction is a promise that the outside world never sees a half-finished change. Either every write inside it becomes visible at the same instant, or none of them does. That is what makes multi-step operations safe to crash in the middle of, which matters because every deploy, every timeout and every out-of-memory kill is a crash in the middle of something.\n\nThe cost is that other work can queue behind it. A refund flow wrapped three steps in one transaction: insert a refunds row, call Stripe over HTTP, update the order status. Stripe normally answered in 200 milliseconds, so nobody noticed. One afternoon Stripe got slow and answered in eight seconds. Each refund now held its locks on the orders row for eight seconds, the connection pool of twenty filled with refunds that were doing nothing but waiting on a network call, and the entire site stopped serving — including pages that had nothing to do with refunds. The fix was not a bigger pool. It was moving the HTTP call outside the transaction: write the intent, commit, call Stripe, then record the result in a second short transaction.\n\nTwo rules make this concrete. Keep transactions short and keep network calls out of them — a transaction should touch the database and nothing else. And use one wherever two writes only make sense together: debit and credit, create-order and decrement-stock, delete-user and delete-their-files. An agent will often write those two statements one after another with no transaction at all, because the code reads fine and works every time you test it. The failure only shows up when the process dies between the two lines, which happens for real, on a schedule you do not control. Ask explicitly: which writes in this function must not be able to happen separately.",
 "he": "טרנזקציה היא הבטחה שהעולם החיצוני לעולם לא רואה שינוי חצי-גמור. או שכל הכתיבות שבתוכה הופכות גלויות באותו רגע, או שאף אחת מהן לא. זה מה שהופך פעולות רב-שלביות לבטוחות לקריסה באמצע, וזה חשוב כי כל דיפלוי, כל טיים-אאוט וכל הרג על חוסר זיכרון הם קריסה באמצע משהו.\n\nהמחיר הוא שעבודה אחרת עלולה להצטבר מאחוריה. תהליך זיכוי עטף שלושה שלבים בטרנזקציה אחת: להכניס שורת refunds, לקרוא לסטרייפ ב-HTTP, לעדכן את סטטוס ההזמנה. סטרייפ בדרך כלל ענה ב-200 מילישניות, אז אף אחד לא שם לב. אחר צהריים אחד סטרייפ נהיה איטי וענה בשמונה שניות. כל זיכוי החזיק עכשיו את הנעילות שלו על שורת ההזמנה שמונה שניות, ה-connection pool של עשרים התמלא בזיכויים שלא עשו כלום חוץ מלחכות לקריאת רשת, וכל האתר הפסיק לשרת — כולל דפים שאין להם שום קשר לזיכויים. הפתרון לא היה pool גדול יותר. הוא היה להוציא את קריאת ה-HTTP מחוץ לטרנזקציה: לכתוב את הכוונה, לעשות COMMIT, לקרוא לסטרייפ, ואז לרשום את התוצאה בטרנזקציה קצרה שנייה.\n\nשני כללים הופכים את זה למעשי. תשמור על טרנזקציות קצרות ותוציא מהן קריאות רשת — טרנזקציה צריכה לגעת בדאטהבייס ובכלום אחר. ותשתמש באחת בכל מקום ששתי כתיבות הגיוניות רק ביחד: חיוב וזיכוי, יצירת הזמנה והורדת מלאי, מחיקת משתמש ומחיקת הקבצים שלו. סוכן יכתוב לא פעם את שתי הפקודות האלה אחת אחרי השנייה בלי טרנזקציה בכלל, כי הקוד נקרא בסדר ועובד בכל בדיקה שתעשה. הכישלון מתגלה רק כשהתהליך מת בין שתי השורות, וזה קורה באמת, בלוח זמנים שאתה לא שולט בו. תשאל במפורש: אילו כתיבות בפונקציה הזו חייבות לא להיות מסוגלות לקרות בנפרד."},

"ORM": {
 "en": "An ORM maps rows to objects so you can write your language instead of SQL. It hides the SQL, and hiding a cost never removes it. Everything the ORM does still becomes queries; you have simply stopped seeing how many and what shape.\n\nThe canonical failure is the N+1. An orders page loaded 100 orders in one query, then looped over them to attach each buyer's name. Ordinary-looking code, four lines, no loop over the database in sight — and 101 round trips to Postgres. Locally, with the database on the same machine, each round trip cost 0.4 milliseconds and the page rendered in 60. In production the database was a separate instance, each round trip cost 11 milliseconds of network, and the same page took 1.2 seconds. Nothing was slow; there was just a great deal of it. Replacing the loop with one eager-load option produced two queries and 40 milliseconds. The code barely changed; the number of conversations did.\n\nSo treat an ORM as a convenience layer you can always see through. Turn on query logging in development — every mainstream ORM has a one-line switch — and load a page. If the log shows the same statement repeated with different ids, you have found an N+1, and you have found it before a user did. This is worth doing specifically on AI-written code, because an agent optimises for code that reads naturally, and the loop-and-fetch pattern reads more naturally than the eager-load one. The useful prompt is not make this faster, it is show me the SQL this endpoint executes and how many statements it runs. Once you can see the count, the fix is usually one argument. The same applies to writes: an ORM that saves a hundred records one at a time inside a loop is the same mistake wearing different clothes.",
 "he": "ORM ממפה שורות לאובייקטים כדי שתכתוב בשפה שלך במקום SQL. הוא מסתיר את ה-SQL, והסתרת עלות אף פעם לא מבטלת אותה. כל מה שה-ORM עושה עדיין הופך לקווריז; פשוט הפסקת לראות כמה ובאיזו צורה.\n\nהכישלון הקלאסי הוא N+1. דף הזמנות טען 100 הזמנות בקווירי אחד, ואז רץ עליהן בלולאה כדי לצרף את שם הקונה לכל אחת. קוד שנראה רגיל לגמרי, ארבע שורות, בלי שום לולאה על הדאטהבייס באופק — ו-101 נסיעות הלוך-חזור לפוסטגרס. מקומית, כשהדאטהבייס על אותה מכונה, כל נסיעה עלתה 0.4 מילישניות והדף רונדר ב-60. בפרודקשן הדאטהבייס היה אינסטנס נפרד, כל נסיעה עלתה 11 מילישניות של רשת, ואותו דף לקח 1.2 שניות. שום דבר לא היה איטי; פשוט היה ממנו המון. החלפת הלולאה באופציית eager load אחת ייצרה שני קווריז ו-40 מילישניות. הקוד כמעט לא השתנה; מספר השיחות כן.\n\nאז תתייחס ל-ORM כשכבת נוחות שאתה תמיד יכול להסתכל דרכה. תדליק לוג של קווריז בסביבת הפיתוח — לכל ORM מרכזי יש מתג של שורה אחת — ותטען דף. אם הלוג מראה את אותה פקודה חוזרת עם מזהים שונים, מצאת N+1, ומצאת אותו לפני שמשתמש מצא. זה שווה במיוחד על קוד שנכתב על ידי AI, כי סוכן מייעל לקוד שנקרא טבעי, ותבנית ״לולאה ושליפה״ נקראת טבעי יותר מתבנית ה-eager load. הפרומפט המועיל הוא לא ״תעשה את זה מהיר יותר״, אלא ״תראה לי את ה-SQL שהאנדפוינט הזה מריץ וכמה פקודות הוא שולח״. ברגע שרואים את המספר, התיקון הוא בדרך כלל ארגומנט אחד. אותו דבר נכון לכתיבות: ORM ששומר מאה רשומות אחת-אחת בתוך לולאה הוא בדיוק אותה טעות בבגדים אחרים."},
}

# ============================== LANGS ==============================

DETAIL_FIX.update({

"Typed vs untyped": {
 "en": "A type is a claim about a value that a machine checks before the program runs. Saying qty is a number is not documentation — it is a proof obligation, and the compiler refuses to build until every path satisfies it. Untyped languages let every value be anything and find out at the moment the operation actually happens, which is usually in front of a user.\n\nA checkout page took quantity from a form field. Form fields are strings. The total function multiplied quantity by price, and JavaScript multiplication happily coerces, so \"2\" times 10 gave 20 and everything looked right for months. Then a discount feature added the values instead of multiplying in one branch: \"2\" plus 10 produced the string \"210\", which was stored as an amount, which became a 210-shekel line on a real invoice. TypeScript would not have compiled that function — the string would have been rejected at the form boundary, where a one-line parse fixes it. The bug survived code review precisely because the line looked correct.\n\nThe cost-benefit shifts with how long the code lives and who edits it. For a script you run once, types are ceremony. For anything an agent will keep editing, they are the cheapest safety net you can buy, because they turn a whole family of AI mistakes — a renamed field, a function called with arguments in the wrong order, a value that can be null — into build errors instead of runtime surprises. The practical move is to start a project in TypeScript rather than adding it later, and to treat a red squiggle in agent-written code as a real finding rather than a configuration annoyance. When an agent suggests silencing an error with any or a type assertion, that is the moment to ask what the actual type is, because the checker has just found something true.",
 "he": "טיפוס הוא טענה לגבי ערך שמכונה בודקת לפני שהתוכנית רצה. לומר ש-qty הוא מספר זה לא תיעוד — זו חובת הוכחה, והקומפיילר מסרב לבנות עד שכל מסלול מקיים אותה. שפות בלי טיפוסים מרשות לכל ערך להיות כל דבר, ומגלות ברגע שהפעולה באמת קורית, שזה בדרך כלל מול משתמש.\n\nדף צ׳קאאוט לקח כמות משדה בטופס. שדות בטופס הם מחרוזות. פונקציית הסכום הכפילה כמות במחיר, וכפל בג׳אווהסקריפט עושה המרה בשמחה, אז \"2\" כפול 10 נתן 20 והכל נראה תקין במשך חודשים. ואז פיצ׳ר הנחות חיבר את הערכים במקום להכפיל באחד הענפים: \"2\" ועוד 10 ייצר את המחרוזת \"210\", שנשמרה כסכום, שהפכה לשורה של 210 שקלים בחשבונית אמיתית. טייפסקריפט לא היה מקמפל את הפונקציה הזו — המחרוזת הייתה נדחית בגבול הטופס, שם פענוח של שורה אחת מתקן אותה. הבאג שרד ריוויו בדיוק כי השורה נראתה נכונה.\n\nהכדאיות משתנה לפי כמה זמן הקוד חי ומי עורך אותו. לסקריפט שרץ פעם אחת, טיפוסים הם טקס. לכל דבר שסוכן ימשיך לערוך, הם רשת הביטחון הזולה ביותר שאפשר לקנות, כי הם הופכים משפחה שלמה של טעויות AI — שדה ששונה שמו, פונקציה שנקראת עם ארגומנטים בסדר הפוך, ערך שיכול להיות null — לשגיאות בילד במקום להפתעות בזמן ריצה. המהלך המעשי הוא להתחיל פרויקט בטייפסקריפט ולא להוסיף אותו אחר כך, ולהתייחס לקו אדום בקוד שסוכן כתב כממצא אמיתי ולא כמטרד קונפיגורציה. כשסוכן מציע להשתיק שגיאה עם any או עם type assertion, זה הרגע לשאול מה הטיפוס האמיתי, כי הבודק בדיוק מצא משהו נכון."},

"Compiled vs interpreted": {
 "en": "This is a question about feedback loops and about where the work happens. A compiler reads your whole program first, checks it, and produces a machine-code binary; you pay minutes up front and the running program is fast and self-contained. An interpreter reads and executes as it goes; you pay a little on every run and get to change a line and see the result immediately, with no build step between you and the answer.\n\nA data team needed to reshape an 8-million-row CSV every night. The first version was 40 lines of Python written in twenty minutes; it ran in 90 seconds. That was fine. When the file grew to 60 million rows the same script took 11 minutes and started colliding with the morning reports, so someone rewrote it in Go. The Go version ran in 50 seconds — and took two days to write, including learning how the CSV library handled quoted fields. Both decisions were correct at the time they were made. What made the second one correct was a measurement, not a preference.\n\nThe modern picture is blurrier than the labels suggest: JavaScript is interpreted but compiles hot code paths while running, Python has an optional compile step for native extensions, Java compiles to bytecode and then again at runtime. Which is why the useful framing for a builder is not which category the language belongs to, but two practical consequences. First, when do my mistakes get caught — a compiled, typed language tells you at build time, an interpreted one at the moment that line executes, possibly at 3am. Second, what deployment looks like: a Go or Rust binary is one file with nothing else needed, while a Python or Node app carries a runtime version and a dependency tree that must match on the server. Most AI-built apps land on interpreted stacks, and that is a reasonable default — just do not let performance become a debate. Profile first, then decide whether the bottleneck is the language at all.",
 "he": "זו שאלה על לולאות משוב ועל איפה העבודה קורית. קומפיילר קורא את כל התוכנית מראש, בודק אותה, ומייצר בינארי בקוד מכונה; אתה משלם דקות מראש והתוכנית שרצה מהירה ועצמאית. אינטרפרטר קורא ומריץ תוך כדי; אתה משלם קצת בכל הרצה ומקבל את היכולת לשנות שורה ולראות תוצאה מיד, בלי שלב בילד בינך לבין התשובה.\n\nצוות דאטה היה צריך לעבד מחדש CSV של 8 מיליון שורות כל לילה. הגרסה הראשונה הייתה 40 שורות פייתון שנכתבו בעשרים דקות; היא רצה ב-90 שניות. זה היה בסדר גמור. כשהקובץ גדל ל-60 מיליון שורות אותו סקריפט לקח 11 דקות והתחיל להתנגש בדוחות הבוקר, אז מישהו שכתב אותו בגו. גרסת הגו רצה ב-50 שניות — ולקחה יומיים לכתוב, כולל ללמוד איך ספריית ה-CSV מטפלת בשדות במרכאות. שתי ההחלטות היו נכונות ברגע שהתקבלו. מה שהפך את השנייה לנכונה היה מדידה, לא העדפה.\n\nהתמונה המודרנית מטושטשת יותר מהתוויות: ג׳אווהסקריפט מפורשת אבל מקמפלת נתיבים חמים תוך כדי ריצה, לפייתון יש שלב קומפילציה אופציונלי להרחבות נייטיב, וג׳אווה מקמפלת לבייטקוד ואז שוב בזמן ריצה. ולכן המסגור המועיל לבונה הוא לא לאיזו קטגוריה השפה שייכת, אלא שתי תוצאות מעשיות. ראשית, מתי הטעויות שלי נתפסות — שפה מקומפלת ומטופסת אומרת לך בזמן בילד, מפורשת אומרת ברגע שהשורה הזו מתבצעת, אולי בשלוש לפנות בוקר. שנית, איך נראה הדיפלוי: בינארי של גו או ראסט הוא קובץ אחד שלא צריך כלום מסביב, בעוד אפליקציית פייתון או נוד גוררת גרסת ראנטיים ועץ תלויות שחייב להתאים בשרת. רוב האפליקציות שנבנות עם AI נוחתות על סטאקים מפורשים, וזו ברירת מחדל סבירה — רק אל תיתן לביצועים להיות ויכוח. קודם פרופיילינג, ואז תחליט אם צוואר הבקבוק הוא בכלל השפה."},

"JavaScript / TypeScript": {
 "en": "JavaScript is the only language with a guaranteed runtime on every device on earth, because every browser ships one. That accident of history, not any merit of the language, is why it spread to servers, build tools, desktop apps and phones. TypeScript is the correction layer on top: it adds type checking at authoring time and then erases itself completely, so what runs in production is plain JavaScript with no runtime cost at all.\n\nThe real benefit of one language on both sides is sharing the pieces that must agree. A team had a validateOrder function used by the React form and by the Node API, so the rules could not drift apart — until a Date object went through JSON.stringify on its way to the server, arrived as the string 2026-03-04T10:00:00.000Z, and the shared function called getFullYear on it. In the browser it worked, because the object was still an object. On the server it threw. That is the characteristic JavaScript bug: the boundary between environments is invisible, so the same code behaves differently on the two sides of a wire. A typed shared schema, parsed at the boundary, turns it into a compile error instead.\n\nFor someone building with an agent, this ecosystem is the path of least resistance and that is mostly good — the largest body of examples, the widest library coverage, the best AI accuracy. Two things to hold onto. Start in TypeScript, even for a prototype, because converting later is a project and starting is a config file. And keep an eye on how many packages arrive: the Node ecosystem's culture of tiny modules means an innocent install can pull in 800 transitive dependencies, each one a future security update and a possible breakage. Ask an agent to justify a dependency the same way you would ask a colleague, and read the lock file diff before you accept it.",
 "he": "ג׳אווהסקריפט היא השפה היחידה עם ראנטיים מובטח בכל מכשיר על פני כדור הארץ, כי כל דפדפן מגיע עם אחד. התאונה ההיסטורית הזו, ולא איזו מעלה של השפה, היא הסיבה שהיא התפשטה לשרתים, לכלי בילד, לאפליקציות דסקטופ ולטלפונים. טייפסקריפט היא שכבת התיקון מעליה: היא מוסיפה בדיקת טיפוסים בזמן כתיבה ואז מוחקת את עצמה לגמרי, כך שמה שרץ בפרודקשן הוא ג׳אווהסקריפט רגילה בלי שום עלות ריצה.\n\nהיתרון האמיתי בשפה אחת בשני הצדדים הוא שיתוף החלקים שחייבים להסכים. לצוות אחד הייתה פונקציית validateOrder שמשמשת גם את טופס הריאקט וגם את ה-API בנוד, כך שהחוקים לא יכלו להיפרד — עד שאובייקט Date עבר דרך JSON.stringify בדרך לשרת, הגיע כמחרוזת 2026-03-04T10:00:00.000Z, והפונקציה המשותפת קראה עליו getFullYear. בדפדפן זה עבד, כי האובייקט עדיין היה אובייקט. בשרת זה זרק שגיאה. זה הבאג האופייני של ג׳אווהסקריפט: הגבול בין הסביבות בלתי נראה, ולכן אותו קוד מתנהג אחרת בשני צדי החוט. סכמה מטופסת משותפת, שמפרסרים בגבול, הופכת את זה לשגיאת קומפילציה.\n\nלמי שבונה עם סוכן, האקוסיסטם הזה הוא נתיב ההתנגדות הנמוכה וזה בעיקר טוב — הכי הרבה דוגמאות, הכיסוי הרחב ביותר של ספריות, והדיוק הגבוה ביותר של ה-AI. שני דברים לזכור. תתחיל בטייפסקריפט, גם לפרוטוטייפ, כי המרה אחר כך היא פרויקט והתחלה היא קובץ קונפיגורציה. ותשים לב כמה חבילות נכנסות: תרבות המודולים הזעירים של נוד אומרת שהתקנה תמימה יכולה לגרור 800 תלויות עקיפות, שכל אחת מהן היא עדכון אבטחה עתידי ושבירה אפשרית. תבקש מסוכן להצדיק תלות בדיוק כמו שהיית מבקש מעמית, ותקרא את הדיף של קובץ ה-lock לפני שאתה מאשר."},

"Python": {
 "en": "Python optimises for the distance between having an idea and seeing a result. The language is readable and forgiving, but the real asset is the ecosystem: for most problems involving data, files, scripting, automation or models, someone has already solved the hard eighty percent and published it.\n\nThat leverage is concrete. A finance team spent a day a month reconciling two exported spreadsheets by hand. The replacement was 30 lines of pandas: read both files, normalise the date columns, merge on invoice id, print the rows that appear in one and not the other. It ran in four seconds and has run every month since. Nothing about that script is clever — the value was entirely in a library that already knew how to join two tables and handle three date formats. The flip side is the same looseness pointing the other way: in a 40-file Python service, a helper that returned a dictionary on success and None on failure worked for a year, until a new caller forgot to check, and a nightly job started writing empty records instead of failing loudly.\n\nSo pick Python when the task is shaped like process this, call that, analyse these — and add the discipline the language will not impose on you. Type hints plus a checker such as mypy or pyright give you most of what TypeScript gives, but only if you turn them on, and an agent will not add them unprompted. Pin your dependencies in a requirements or lock file rather than letting pip resolve whatever is newest that day; Python projects break far more often from an environment drifting than from a code change. And keep a virtual environment per project, because the alternative is one global set of packages that every project on the machine silently fights over.",
 "he": "פייתון ממטבת את המרחק בין רעיון לתוצאה על המסך. השפה קריאה וסלחנית, אבל הנכס האמיתי הוא האקוסיסטם: לרוב הבעיות שקשורות לדאטה, קבצים, סקריפטים, אוטומציה או מודלים, מישהו כבר פתר את שמונים האחוזים הקשים ופרסם את זה.\n\nהמינוף הזה מוחשי. צוות כספים בזבז יום בחודש על התאמה ידנית בין שני קבצי אקסל מיוצאים. התחליף היה 30 שורות pandas: לקרוא את שני הקבצים, לנרמל את עמודות התאריך, למזג לפי מזהה חשבונית, ולהדפיס את השורות שמופיעות באחד ולא בשני. זה רץ בארבע שניות ורץ כל חודש מאז. אין שום דבר חכם בסקריפט הזה — הערך היה כולו בספרייה שכבר ידעה לחבר שתי טבלאות ולהתמודד עם שלושה פורמטים של תאריך. הצד השני הוא אותה גמישות בכיוון ההפוך: בשירות פייתון של 40 קבצים, פונקציית עזר שהחזירה מילון בהצלחה ו-None בכישלון עבדה שנה, עד שקורא חדש שכח לבדוק, וג׳וב לילי התחיל לכתוב רשומות ריקות במקום ליפול ברעש.\n\nאז תבחר בפייתון כשהמשימה בנויה כמו ״תעבד את זה, תקרא לזה, תנתח את אלה״ — ותוסיף את המשמעת שהשפה לא תכפה עליך. רמזי טיפוסים יחד עם בודק כמו mypy או pyright נותן לך את רוב מה שטייפסקריפט נותנת, אבל רק אם תדליק אותם, וסוכן לא יוסיף אותם מיוזמתו. תקבע את התלויות בקובץ requirements או lock במקום לתת ל-pip לפתור את מה שהכי חדש באותו יום; פרויקטי פייתון נשברים הרבה יותר מסביבה שנסחפת מאשר משינוי קוד. ותשמור על סביבה וירטואלית לכל פרויקט, כי החלופה היא אוסף חבילות גלובלי אחד שכל הפרויקטים על המכונה נלחמים עליו בשקט."},

"Go / Rust / Java / C#": {
 "en": "These languages exist because at some point the cost of a mistake exceeds the cost of ceremony. Each buys you something specific by asking more of you up front. Go buys simplicity and fast, self-contained services: few features, one obvious way to do things, a single binary you copy to a server. Rust buys memory safety without a garbage collector, so there are no pauses and no whole class of crashes — paid for with the strictest compiler in mainstream use. Java and C# buy thirty years of tooling, libraries, and people who know how to run a large system for a decade.\n\nThe cost is real and worth a concrete example. A small team needed a thumbnail service and chose Rust for speed. The service is genuinely excellent: 4 milliseconds per image, 60MB of memory, no pauses. It also took three weeks, most of that spent learning why the compiler would not allow an image buffer to be used in two places at once. The Node version a colleague wrote as a stopgap took four hours, used 400MB, and was fast enough for the actual traffic, which was eleven images a minute. Rust was the better program and the worse decision.\n\nFor someone building with AI, the practical use of these names is recognition rather than adoption. Seeing Go in a repo tells you to expect a small, service-shaped codebase with explicit error handling on every line. Seeing Java or C# tells you there is a framework, a build system and a set of conventions you should follow rather than invent — and that an agent's idiomatic-looking suggestion may ignore all three, because it pattern-matched on a tutorial instead of on this project. You choose a language far more often by what your team, your libraries and your hiring pool already speak than by merit, and that is a legitimate engineering reason rather than a compromise.",
 "he": "השפות האלה קיימות כי בשלב מסוים מחיר הטעות עולה על מחיר הטקס. כל אחת מהן קונה משהו ספציפי בתמורה לדרישה גדולה יותר ממך מראש. גו קונה פשטות ושירותים מהירים ועצמאיים: מעט פיצ׳רים, דרך אחת ברורה לעשות דברים, בינארי אחד שמעתיקים לשרת. ראסט קונה בטיחות זיכרון בלי גרבג׳ קולקשן, כך שאין פאוזות ואין משפחה שלמה של קריסות — ומשלמים על זה בקומפיילר המחמיר ביותר בשימוש נרחב. ג׳אווה ו-C# קונות שלושים שנה של כלים, ספריות ואנשים שיודעים להריץ מערכת גדולה במשך עשור.\n\nהמחיר אמיתי ושווה דוגמה מוחשית. צוות קטן היה צריך שירות תמונות ממוזערות ובחר בראסט בגלל המהירות. השירות באמת מצוין: 4 מילישניות לתמונה, 60 מגה זיכרון, בלי פאוזות. הוא גם לקח שלושה שבועות, שרובם הלכו על ללמוד למה הקומפיילר לא מרשה להשתמש בבאפר תמונה בשני מקומות בו-זמנית. גרסת הנוד שעמית כתב כפתרון ביניים לקחה ארבע שעות, השתמשה ב-400 מגה, והייתה מהירה מספיק לתעבורה האמיתית, שהייתה אחת עשרה תמונות בדקה. ראסט הייתה התוכנית הטובה יותר וההחלטה הגרועה יותר.\n\nלמי שבונה עם AI, השימוש המעשי בשמות האלה הוא זיהוי ולא אימוץ. גו ברפו אומר לך לצפות לקוד קטן בצורת שירות עם טיפול מפורש בשגיאות בכל שורה. ג׳אווה או C# אומרות לך שיש פריימוורק, מערכת בילד ומערכת מוסכמות שכדאי לעקוב אחריהן ולא להמציא — ושהצעה של סוכן שנראית אידיומטית עלולה להתעלם משלושתן, כי היא התאימה תבנית לטוטוריאל ולא לפרויקט הזה. בוחרים שפה הרבה יותר לפי מה שהצוות, הספריות ומאגר הגיוס שלך כבר מדברים מאשר לפי מעלות, וזו סיבה הנדסית לגיטימית ולא פשרה."},

"Package manager": {
 "en": "A package manager solves a problem that sounds trivial and is not: making the same set of code appear on two different machines, including the dependencies of your dependencies, and the dependencies of those. Your project declares what it wants; the tool works out a tree that satisfies everyone and writes down exactly what it installed.\n\nThat written-down part is the lock file, and it is the whole point. A team had stripe at caret 12.1.0 in package.json. On a developer laptop, installed in March, that resolved to 12.1.0. CI ran a fresh install in June and got 12.9.0, which had changed a default from automatic payment methods to explicit ones. Tests passed, because the test suite mocked Stripe. Production started declining cards. Nobody had changed a line of code; the caret had quietly allowed a different library. The fix was two words: npm ci in CI instead of npm install, which installs exactly the locked tree and fails loudly if package.json and the lock file disagree.\n\nSo commit the lock file — package-lock.json, pnpm-lock.yaml, poetry.lock, Cargo.lock, go.sum — always, including on a small project. It is what makes a build today and a build in a year produce the same thing, and it is what lets you answer the question which version was running when this broke. When an agent installs something, check what actually arrived: read the diff on the lock file, not just on package.json. A one-line dependency addition that changes 2,000 lines of lock file has brought in a great deal more than one library, and that is worth knowing before it reaches production rather than after. It is also worth running your package manager's audit command on a schedule rather than only when something breaks, because a dependency with a known vulnerability never announces itself — it simply sits there until somebody else finds it first. That check is built into npm, pip and cargo, and it takes seconds.",
 "he": "מנהל חבילות פותר בעיה שנשמעת טריוויאלית ואיננה: לגרום לאותו אוסף קוד להופיע על שתי מכונות שונות, כולל התלויות של התלויות שלך, והתלויות שלהן. הפרויקט מצהיר מה הוא רוצה; הכלי מחשב עץ שמספק את כולם ורושם בדיוק מה הותקן.\n\nהחלק ה״רושם״ הזה הוא קובץ ה-lock, והוא כל העניין. לצוות אחד היה stripe עם גגון 12.1.0 ב-package.json. על מחשב של מפתח, שהותקן במרץ, זה נפתר ל-12.1.0. ה-CI הריץ התקנה נקייה ביוני וקיבל 12.9.0, שבה השתנתה ברירת מחדל מאמצעי תשלום אוטומטיים לאמצעים מפורשים. הטסטים עברו, כי סוויטת הבדיקות עשתה mock לסטרייפ. הפרודקשן התחיל לדחות כרטיסים. אף אחד לא שינה שורת קוד; הגגון פשוט הרשה בשקט ספרייה אחרת. התיקון היה שתי מילים: npm ci ב-CI במקום npm install, שמתקין בדיוק את העץ הנעול ונופל ברעש אם package.json וקובץ ה-lock לא מסכימים.\n\nאז תעשה קומיט לקובץ ה-lock — package-lock.json, pnpm-lock.yaml, poetry.lock, Cargo.lock, go.sum — תמיד, גם בפרויקט קטן. זה מה שגורם לבילד היום ולבילד בעוד שנה לייצר את אותו דבר, וזה מה שמאפשר לך לענות על השאלה איזו גרסה רצה כשזה נשבר. כשסוכן מתקין משהו, תבדוק מה באמת נכנס: תקרא את הדיף של קובץ ה-lock, לא רק של package.json. הוספת תלות של שורה אחת שמשנה 2,000 שורות בקובץ ה-lock הביאה הרבה יותר מספרייה אחת, וזה שווה לדעת לפני שזה מגיע לפרודקשן ולא אחרי. שווה גם להריץ את פקודת ה-audit של מנהל החבילות שלך באופן קבוע ולא רק כשמשהו נשבר, כי תלות עם חולשת אבטחה ידועה אף פעם לא מכריזה על עצמה — היא פשוט יושבת שם עד שמישהו אחר מוצא אותה קודם. הבדיקה הזו מובנית ב-npm, ב-pip וב-cargo, והיא לוקחת שניות."},

"Dependency": {
 "en": "Adding a dependency is outsourcing a decision to a stranger, permanently. You inherit their bugs, their security holes, their breaking changes, their view of how the problem should be modelled, and their eventual decision to stop maintaining it. None of that shows up on the day you install it, which is exactly what makes the decision feel free.\n\nThe cost is measurable. A Next.js project had 14 direct dependencies and 1,190 packages in node_modules. When a prototype-pollution advisory landed against a utility library four levels deep, nothing the team had written was involved, but the upgrade path went through a package that required a major version bump of a framework plugin, which required a newer Node, which broke the Docker image. Two days of work, for a library nobody on the team had chosen or read. Meanwhile a different corner of the same repo had pulled in a 40KB package to check whether a string was a valid email — a regex and three lines would have done it, owned forever, with no advisory feed attached.\n\nThe test is not can this library do it. It is would I rather own this code or own this relationship. For something you could write in twenty lines and fully understand, owning the code is almost always cheaper. For cryptography, dates and time zones, parsing, or anything a protocol defines, owning the relationship is obviously right — those are the places where your twenty lines will be wrong in ways you cannot see. Agents lean heavily toward installing, because an import is the shortest answer to almost any prompt. When a new one appears in a diff, ask three questions: what does this actually do for us, how many packages came with it, and when was it last released. A library last published four years ago is not stable, it is abandoned.",
 "he": "הוספת תלות היא מיקור-חוץ של החלטה לזר, לצמיתות. אתה יורש את הבאגים שלו, את חורי האבטחה שלו, את השינויים השוברים שלו, את התפיסה שלו איך למדל את הבעיה, ואת ההחלטה העתידית שלו להפסיק לתחזק. שום דבר מזה לא מופיע ביום ההתקנה, ובדיוק בגלל זה ההחלטה מרגישה חינם.\n\nהעלות מדידה. לפרויקט Next.js היו 14 תלויות ישירות ו-1,190 חבילות ב-node_modules. כשהתפרסמה התרעת אבטחה על prototype pollution בספריית עזר ארבע רמות פנימה, שום דבר שהצוות כתב לא היה מעורב, אבל מסלול השדרוג עבר דרך חבילה שדרשה קפיצת מייג׳ר של פלאגין לפריימוורק, שדרשה נוד חדש יותר, ששברה את אימג׳ הדוקר. יומיים עבודה, בשביל ספרייה שאף אחד בצוות לא בחר ולא קרא. במקביל, פינה אחרת באותו רפו גררה חבילה של 40 קילובייט כדי לבדוק אם מחרוזת היא אימייל תקין — רג׳קס ושלוש שורות היו עושים את זה, בבעלות מלאה, בלי פיד התרעות מצורף.\n\nהמבחן הוא לא ״האם הספרייה הזו יודעת לעשות את זה״. הוא ״האם אני מעדיף להחזיק את הקוד הזה או את מערכת היחסים הזו״. למשהו שיכולת לכתוב בעשרים שורות ולהבין לגמרי, להחזיק את הקוד כמעט תמיד זול יותר. לקריפטוגרפיה, לתאריכים ואזורי זמן, לפרסינג, או לכל דבר שפרוטוקול מגדיר, להחזיק את מערכת היחסים ברור שנכון — שם עשרים השורות שלך יהיו שגויות בדרכים שלא תראה. סוכנים נוטים חזק להתקנה, כי ייבוא הוא התשובה הקצרה ביותר כמעט לכל פרומפט. כשתלות חדשה מופיעה בדיף, תשאל שלוש שאלות: מה זה באמת עושה בשבילנו, כמה חבילות הגיעו איתה, ומתי היא שוחררה לאחרונה. ספרייה שפורסמה לאחרונה לפני ארבע שנים היא לא יציבה, היא נטושה."},

"Framework vs library": {
 "en": "You call a library; a framework calls you. That inversion is the whole distinction, and it decides who owns the structure of your application. A library is a drawer of tools you reach into when you want something. A framework is a building with the rooms already laid out — routing here, data loading there, this file name means this thing — and your job is to fill them in. That is enormous leverage when its decisions match your problem, and a permanent tax when they do not.\n\nA team building an internal tool chose a full-stack framework and had authentication, routing, server rendering and a deploy pipeline working in one afternoon. Nine months later they needed a login flow that redirected through a customer's own identity provider and returned to a per-tenant subdomain. The framework had exactly one opinion about where sessions live, and it was not compatible. Two weeks went into fighting the routing layer, ending in a bespoke middleware that the next framework upgrade broke again. The same feature on a plain server with a routing library would have been two days — but those two days would have been spent on that first afternoon, and on every afternoon after it.\n\nThe honest way to evaluate a framework is not the tutorial. It is to find an application built with it that is three years old and much larger than yours, and look at what the awkward parts look like. That is what you are signing up for. For AI-assisted work there is a second, sharper consideration: agents are dramatically better inside popular frameworks, because the conventions are in the training data and the right answer is usually the conventional one. A mainstream framework you do not love will often produce better agent output than a hand-rolled structure you designed yourself. Just know which of your requirements sit outside its opinions before you commit, because those are the ones that cost weeks.",
 "he": "אתה קורא לספרייה; פריימוורק קורא לך. ההיפוך הזה הוא כל ההבחנה, והוא קובע מי מחזיק במבנה של האפליקציה. ספרייה היא מגירת כלים שאתה שולח אליה יד כשאתה רוצה משהו. פריימוורק הוא בניין שהחדרים בו כבר מסודרים — ניתוב פה, טעינת נתונים שם, שם הקובץ הזה אומר את הדבר הזה — והתפקיד שלך הוא למלא אותם. זה מינוף עצום כשההחלטות שלו מתאימות לבעיה שלך, ומס קבוע כשלא.\n\nצוות שבנה כלי פנימי בחר פריימוורק פול-סטאק וקיבל הזדהות, ניתוב, רינדור בשרת וצינור דיפלוי עובדים תוך אחר צהריים אחד. תשעה חודשים אחר כך הם נזקקו לתהליך התחברות שמפנה דרך ספק הזהויות של הלקוח וחוזר לסאב-דומיין נפרד לכל טננט. לפריימוורק הייתה בדיוק דעה אחת על איפה סשנים חיים, והיא לא הייתה תואמת. שבועיים הלכו על מאבק בשכבת הניתוב, שהסתיים במידלוור מותאם שהשדרוג הבא של הפריימוורק שבר שוב. אותו פיצ׳ר בשרת רגיל עם ספריית ניתוב היה לוקח יומיים — אבל היומיים האלה היו מושקעים כבר באותו אחר צהריים ראשון, ובכל אחר צהריים שאחריו.\n\nהדרך הכנה להעריך פריימוורק היא לא הטוטוריאל. היא למצוא אפליקציה שנבנתה איתו, בת שלוש שנים וגדולה משלך בהרבה, ולהסתכל איך נראים החלקים המסורבלים. זה מה שאתה קונה. לעבודה עם AI יש שיקול שני וחד יותר: סוכנים טובים בהרבה בתוך פריימוורקים פופולריים, כי המוסכמות נמצאות בדאטה של האימון והתשובה הנכונה היא בדרך כלל המוסכמת. פריימוורק מיינסטרים שאתה לא מאוהב בו יפיק לא פעם פלט סוכן טוב יותר ממבנה שהמצאת בעצמך. רק תדע אילו מהדרישות שלך יושבות מחוץ לדעות שלו לפני שאתה מתחייב, כי אלה אלה שעולות שבועות."},
})

# ============================== MEMORY ==============================

DETAIL_FIX.update({

"RAM vs disk": {
 "en": "There is a hierarchy, and each step down it is roughly a thousand times slower and a thousand times more durable: processor cache, RAM, SSD, network, another continent. RAM is where your program thinks; disk and the database are where it remembers. Almost all performance work is moving data up this hierarchy, and almost all data-loss incidents are someone assuming a value was one level lower than it really was.\n\nA scheduling app kept logged-in sessions in a JavaScript Map, because that is the shortest thing that works and it works perfectly on a laptop. Two things then happened. Deploys went out most afternoons, and every deploy restarted the process and logged out every user mid-task — support read it as a mysterious bug for weeks because it only ever happened between 2pm and 5pm. Then traffic grew and a second instance went up behind a load balancer. Now half the requests reached a process that had never seen your session, so users were logged out at random even without a deploy. Moving the sessions into Redis, a dozen lines, fixed both at once.\n\nThe rule is simple and worth applying without exception: anything you would be upset to lose, and anything a second copy of your server would need to know, does not live in a variable. It lives in a database, a cache server, or a file store. When an agent writes a counter, a queue, a rate limiter, an upload buffer or a session store, its first instinct is an in-process object, and the code will pass every test you run on one machine. Ask directly: what happens to this on restart, and what happens if there are two of us. Those two questions catch the entire category before it becomes a production mystery that only appears at deploy time.",
 "he": "יש היררכיה, וכל צעד מטה בה איטי בערך פי אלף ועמיד בערך פי אלף: מטמון המעבד, RAM, SSD, רשת, יבשת אחרת. ב-RAM התוכנית שלך חושבת; בדיסק ובדאטהבייס היא זוכרת. כמעט כל עבודת ביצועים היא הזזת נתונים למעלה בהיררכיה הזו, וכמעט כל אירוע של אובדן נתונים הוא מישהו שהניח שערך נמצא רמה אחת נמוך יותר ממה שהוא באמת.\n\nאפליקציית זימון תורים שמרה סשנים מחוברים ב-Map בג׳אווהסקריפט, כי זה הדבר הקצר ביותר שעובד וזה עובד מושלם על לפטופ. ואז קרו שני דברים. דיפלויים יצאו כמעט כל אחר צהריים, וכל דיפלוי הפעיל מחדש את התהליך וניתק כל משתמש באמצע משימה — התמיכה קראה לזה באג מסתורי במשך שבועות כי זה קרה רק בין שתיים לחמש. אחר כך התעבורה גדלה ועלה אינסטנס שני מאחורי לואד בלאנסר. עכשיו חצי מהבקשות הגיעו לתהליך שמעולם לא ראה את הסשן שלך, אז משתמשים נותקו באקראי גם בלי דיפלוי. העברת הסשנים ל-Redis, תריסר שורות, פתרה את שניהם בבת אחת.\n\nהכלל פשוט ושווה להחיל אותו בלי חריגים: כל דבר שהיית מתעצבן לאבד, וכל דבר שעותק שני של השרת שלך צריך לדעת, לא חי במשתנה. הוא חי בדאטהבייס, בשרת מטמון, או באחסון קבצים. כשסוכן כותב מונה, תור, רייט לימיטר, באפר העלאות או מאגר סשנים, האינסטינקט הראשון שלו הוא אובייקט בתוך התהליך, והקוד יעבור כל בדיקה שתריץ על מכונה אחת. תשאל ישירות: מה קורה לזה בהפעלה מחדש, ומה קורה אם יש שניים מאיתנו. שתי השאלות האלה תופסות את כל הקטגוריה לפני שהיא הופכת לתעלומה בפרודקשן שמופיעה רק בזמן דיפלוי."},

"Stack & heap": {
 "en": "Both are memory; the difference is who decides when something can be thrown away. The stack is strictly ordered — the last thing in is the first thing out — so the machine always knows exactly when a local variable is finished with, and cleanup is free. The heap has no such order: objects there can outlive the function that created them, be pointed at from several places, and be released only when nobody is looking at them anymore. That is why the heap needs either a garbage collector or your explicit attention, and the stack needs neither.\n\nThis split produces the two most famous crashes, and they mean opposite things. A category tree walker recursed through children; an admin accidentally set a category's parent to one of its own descendants, creating a cycle. The walker kept adding frames until Node stopped it at about 11,000 deep with Maximum call stack size exceeded — the stack is deliberately small, around 1MB. Separately, a batch job read a 900MB export into an array of parsed objects and died with JavaScript heap out of memory, because Node's default heap ceiling is around 1.5 to 4GB depending on version. The first is a logic bug: something never terminates. The second is a volume bug: the work does terminate, but it does not fit.\n\nSo the message tells you which question to ask. Stack overflow means find the recursion that has no base case, or the cycle in your data — reaching for a bigger stack is almost always treating a symptom. Out of memory means stop loading the whole thing at once: stream the file, page the query, process in chunks of a thousand. When an agent writes code that loads all records and then filters, that is the pattern that passes on your 200-row test database and dies on the real one.",
 "he": "שניהם זיכרון; ההבדל הוא מי מחליט מתי אפשר לזרוק משהו. הסטאק מסודר בהחלט — האחרון שנכנס הוא הראשון שיוצא — ולכן המכונה תמיד יודעת בדיוק מתי סיימו עם משתנה מקומי, והניקוי הוא חינם. להיפ אין סדר כזה: אובייקטים שם יכולים לשרוד את הפונקציה שיצרה אותם, להיות מוצבעים מכמה מקומות, ולהשתחרר רק כשאף אחד לא מסתכל עליהם יותר. לכן ההיפ צריך גרבג׳ קולקשן או את תשומת הלב המפורשת שלך, והסטאק לא צריך אף אחד מהם.\n\nהפיצול הזה מייצר את שתי הקריסות המפורסמות ביותר, והן אומרות דברים הפוכים. קוד שעבר על עץ קטגוריות ירד רקורסיבית לילדים; אדמין הגדיר בטעות הורה של קטגוריה לאחד הצאצאים שלה עצמה, וייצר מעגל. הקוד המשיך להוסיף פריימים עד שנוד עצר אותו בסביבות עומק 11,000 עם Maximum call stack size exceeded — הסטאק קטן בכוונה, סביב מגה אחד. בנפרד, ג׳וב באטצ׳ קרא ייצוא של 900 מגה למערך של אובייקטים מפורסרים ומת עם JavaScript heap out of memory, כי תקרת ההיפ המוגדרת כברירת מחדל בנוד היא סביב 1.5 עד 4 ג׳יגה תלוי בגרסה. הראשונה היא באג לוגי: משהו לא מסתיים. השנייה היא באג נפח: העבודה כן מסתיימת, אבל היא לא נכנסת.\n\nאז ההודעה אומרת לך איזו שאלה לשאול. Stack overflow אומר תמצא את הרקורסיה בלי תנאי עצירה, או את המעגל בנתונים — להגדיל את הסטאק זה כמעט תמיד טיפול בסימפטום. Out of memory אומר תפסיק לטעון הכל בבת אחת: לעשות סטרימינג לקובץ, לעמד את הקווירי, לעבד בצ׳אנקים של אלף. כשסוכן כותב קוד שטוען את כל הרשומות ואז מסנן, זו התבנית שעוברת על דאטהבייס בדיקות של 200 שורות ומתה על האמיתי."},

"Garbage collection": {
 "en": "Automatic memory management trades a class of catastrophic bugs for a class of timing surprises. You will never free the same memory twice or read a pointer to something that no longer exists — those bugs simply cannot occur. In exchange, the runtime occasionally stops your program to work out what is still reachable and reclaim the rest, and it chooses the moment, not you.\n\nThat shows up as a shape in the latency graph rather than as an error. An API served a median of 12 milliseconds and a p99 of 40, which everyone was happy with. But roughly every 90 seconds a handful of requests took 700 to 1,100 milliseconds, and a customer complained about occasional freezes nobody could reproduce. The memory graph explained it: a sawtooth, climbing to about 3GB and dropping back, with each drop lining up exactly with the slow requests. The service was allocating a large temporary object per request, so the heap filled quickly and each major collection had a lot to walk. Allocating less per request — reusing a buffer instead of building a new one — cut the frequency of those pauses to nearly nothing, without any change to the garbage collector's settings.\n\nFor most applications the trade is an excellent one, and tuning the collector is almost never the right first move. The useful instinct is different: when a service shows periodic latency spikes that do not correlate with traffic, look at the memory graph before you look at the code. Sawtooth plus spikes means garbage collection; a staircase that only climbs means a leak. And when an agent proposes GC flags or a bigger heap to fix slowness, treat that as a signal to ask what is being allocated in the hot path instead. The flag hides the symptom for a while; the allocation is the actual finding.",
 "he": "ניהול זיכרון אוטומטי מחליף משפחה של באגים קטסטרופליים במשפחה של הפתעות תזמון. לעולם לא תשחרר את אותו זיכרון פעמיים ולא תקרא מצביע למשהו שכבר לא קיים — הבאגים האלה פשוט לא יכולים לקרות. בתמורה, הראנטיים עוצר מדי פעם את התוכנית כדי לחשב מה עדיין נגיש ולשחרר את השאר, והוא בוחר את הרגע, לא אתה.\n\nזה מופיע כצורה בגרף הלייטנסי ולא כשגיאה. API שירת חציון של 12 מילישניות ו-p99 של 40, ומזה כולם היו מרוצים. אבל בערך כל 90 שניות קומץ בקשות לקחו 700 עד 1,100 מילישניות, ולקוח התלונן על קפיאות מזדמנות שאף אחד לא הצליח לשחזר. גרף הזיכרון הסביר: שיני מסור, שמטפסות לסביבות 3 ג׳יגה ויורדות בחזרה, כשכל ירידה מתיישרת בדיוק עם הבקשות האיטיות. השירות הקצה אובייקט זמני גדול לכל בקשה, אז ההיפ התמלא מהר ולכל איסוף מלא היה הרבה על מה לעבור. להקצות פחות לכל בקשה — לעשות שימוש חוזר בבאפר במקום לבנות חדש — הוריד את תדירות הפאוזות כמעט לאפס, בלי שום שינוי בהגדרות ה-GC.\n\nלרוב האפליקציות זו עסקה מצוינת, וכוונון ה-GC כמעט אף פעם לא המהלך הראשון הנכון. האינסטינקט המועיל אחר: כששירות מראה קפיצות לייטנסי מחזוריות שלא מתואמות לתעבורה, תסתכל על גרף הזיכרון לפני שאתה מסתכל על הקוד. שיני מסור עם קפיצות אומרות גרבג׳ קולקשן; מדרגות שרק עולות אומרות ליק. וכשסוכן מציע דגלי GC או היפ גדול יותר כדי לפתור איטיות, תתייחס לזה כסימן לשאול מה מוקצה בנתיב החם במקום. הדגל מסתיר את הסימפטום לזמן מה; ההקצאה היא הממצא האמיתי."},

"Memory leak": {
 "en": "A leak is not memory escaping. It is memory you are still technically holding on to, which means the collector is behaving perfectly correctly — the bug is in what your code still references. Anything reachable from a live variable is, as far as the runtime is concerned, still wanted.\n\nThe symptom is a shape and a schedule. A Node API ran at a steady 300MB for the first few hours after each deploy, then climbed to 1.4GB and was killed by the container runtime — every night, between 2 and 3am, which happened to be however long it took to accumulate enough traffic. The memory graph was not a sawtooth but a staircase: it went up after each collection instead of back down. The cause was four lines of well-meaning code: a Map keyed by request id, used to correlate logs, written on every request and never deleted. In 14 hours that was 900,000 entries, each holding the whole request object, which held headers, body and a database connection reference. Swapping it for an LRU with a ceiling of 10,000 entries flattened the graph the same day.\n\nThe usual suspects are all collections that only ever grow: a cache with no maximum size, an array of event listeners nobody removes, a Map keyed by user id that outlives the users, a setInterval that is never cleared. The question to ask of any such structure in AI-written code is simply what removes entries from this, and the answer must not be nothing. And the habit that catches leaks before users do: after a deploy, look at the memory graph over a full day rather than the first ten minutes. Sawtooth is healthy. A staircase that never comes down is a crash with a date on it, and the only open question is which night.",
 "he": "ליק הוא לא זיכרון שבורח. הוא זיכרון שאתה עדיין טכנית מחזיק, כלומר ה-GC מתנהג נכון לחלוטין — הבאג הוא במה שהקוד שלך עדיין מפנה אליו. כל מה שנגיש ממשתנה חי הוא, מבחינת הראנטיים, עדיין רצוי.\n\nהסימפטום הוא צורה ולוח זמנים. API בנוד רץ על 300 מגה יציבים בשעות הראשונות אחרי כל דיפלוי, ואז טיפס ל-1.4 ג׳יגה ונהרג על ידי הקונטיינר — כל לילה, בין שתיים לשלוש, שזה במקרה הזמן שלקח לצבור מספיק תעבורה. גרף הזיכרון לא היה שיני מסור אלא מדרגות: הוא עלה אחרי כל איסוף במקום לרדת בחזרה. הסיבה הייתה ארבע שורות של קוד בכוונות טובות: Map ממופתח לפי מזהה בקשה, שנועד לקשר בין לוגים, נכתב בכל בקשה ולעולם לא נמחק. ב-14 שעות זה 900,000 רשומות, שכל אחת מחזיקה את אובייקט הבקשה השלם, שמחזיק כותרות, גוף, והפניה לחיבור דאטהבייס. החלפה ל-LRU עם תקרה של 10,000 רשומות יישרה את הגרף עוד באותו יום.\n\nהחשודים המיידיים הם תמיד אוספים שרק גדלים: מטמון בלי גודל מקסימלי, מערך מאזינים שאף אחד לא מסיר, Map ממופתח לפי מזהה משתמש ששורד את המשתמשים, setInterval שלעולם לא מנוקה. השאלה שצריך לשאול על כל מבנה כזה בקוד שנכתב על ידי AI היא פשוט ״מה מוחק מזה רשומות״, והתשובה לא יכולה להיות ״כלום״. וההרגל שתופס ליקים לפני שמשתמשים תופסים: אחרי דיפלוי, תסתכל על גרף הזיכרון לאורך יום שלם ולא בעשר הדקות הראשונות. שיני מסור זה בריא. מדרגות שלא יורדות זה קריסה עם תאריך, והשאלה הפתוחה היחידה היא באיזה לילה."},

"Latency vs throughput": {
 "en": "A highway can be wide or fast, and widening it does not shorten anyone's trip. Latency is how long one thing takes; throughput is how many things finish per second. They are genuinely different numbers, and almost every technique that raises the second one does so by making individual items wait.\n\nA notification service sent emails one at a time, each a separate API call, at about 50 per second. Batching them into groups of 500 pushed it to 2,000 per second, a fortyfold improvement — bought by having each message wait in a buffer for up to five seconds before its batch went out. For the nightly marketing run that was free money: ten million emails went from days to hours and nobody was waiting. Then the same batching path was reused for password-reset emails, and support started hearing that the reset link takes ages. It took five seconds, every time, by design. The correct system ran two paths: batched for bulk, immediate for anything a human is staring at a screen waiting for.\n\nSo decide which number your user actually experiences, per operation rather than per system. A person waiting for a page cares only about latency and will never notice your requests-per-second. A nightly job processing ten million rows cares only about throughput and will never notice that each row took 40 milliseconds. The same distinction explains why an average is a bad measure: report the median and the p95 or p99, because the average hides the tail, and the tail is what people complain about. When an agent proposes batching, queuing, a connection pool or parallelism to make something faster, ask which of the two numbers it is improving — and whether the one it is trading away is the one your user is sitting in front of.",
 "he": "כביש יכול להיות רחב או מהיר, והרחבה שלו לא מקצרת לאף אחד את הנסיעה. לייטנסי הוא כמה זמן לוקח דבר אחד; תפוקה היא כמה דברים מסתיימים בשנייה. אלה באמת שני מספרים שונים, וכמעט כל טכניקה שמעלה את השני עושה את זה בכך שהיא גורמת לפריטים בודדים לחכות.\n\nשירות התראות שלח מיילים אחד-אחד, כל אחד בקריאת API נפרדת, בערך 50 בשנייה. איגוד שלהם לבאטצ׳ים של 500 העלה את זה ל-2,000 בשנייה, שיפור פי ארבעים — שנקנה בכך שכל הודעה המתינה בבאפר עד חמש שניות לפני שהבאטצ׳ שלה יצא. להרצה השיווקית הלילית זה היה כסף חינם: עשרה מיליון מיילים ירדו מימים לשעות ואף אחד לא חיכה. ואז אותו מסלול באטצ׳ינג שימש גם למיילים של איפוס סיסמה, והתמיכה התחילה לשמוע שלינק האיפוס לוקח נצח. הוא לקח חמש שניות, כל פעם, בתכנון. המערכת הנכונה הריצה שני מסלולים: באטצ׳ לכמויות, מיידי לכל דבר שבן אדם בוהה במסך ומחכה לו.\n\nאז תחליט איזה מספר המשתמש שלך באמת חווה, לכל פעולה ולא לכל המערכת. אדם שמחכה לדף אכפת לו רק מלייטנסי ולעולם לא ישים לב לבקשות-לשנייה שלך. ג׳וב לילי שמעבד עשרה מיליון שורות אכפת לו רק מתפוקה ולעולם לא ישים לב שכל שורה לקחה 40 מילישניות. אותה הבחנה מסבירה למה ממוצע הוא מדד גרוע: תדווח חציון ו-p95 או p99, כי הממוצע מסתיר את הזנב, והזנב הוא מה שאנשים מתלוננים עליו. כשסוכן מציע באטצ׳ינג, תורים, connection pool או מקביליות כדי להאיץ משהו, תשאל איזה משני המספרים הוא משפר — ואם זה שהוא מוותר עליו הוא זה שהמשתמש שלך יושב מולו."},

"Big-O": {
 "en": "Big-O describes how the work grows as the input grows, and deliberately ignores constants — because at small sizes the constants are all that matter, and at large sizes only the shape of the growth does. O(1) means the size does not matter. O(n) means twice the data is twice the work. O(n²) means twice the data is four times the work, and ten times the data is a hundred times the work.\n\nThat last one is the trap, because it is invisible until it is not. A sync job compared two lists to find which records were new, using a filter with an includes check inside it — a loop inside a loop, though it only reads as one line. With 500 records on each side that is 250,000 comparisons and it finished in about 12 milliseconds; nobody thought about it for a year. A larger customer arrived with 20,000 records: 400 million comparisons, and the job took 45 seconds and started timing out against the API it was feeding. The fix was one line — build a Set from the second list first, then check membership — which turned it into 40,000 operations and 30 milliseconds. Same output, same code length, different shape.\n\nThe practical use of Big-O is prediction without an experiment: what happens at a hundred times this data. You do not need the formal version to get the benefit. Learn to notice a loop inside a loop over the same data, an includes or indexOf or find inside a loop, and a database query inside a loop — those three cover most of what actually bites. All of them look fine at development scale, which is why testing does not catch them. When an agent hands you a data-processing function, ask what it does at a hundred thousand items, and where the nested loop is.",
 "he": "Big-O מתאר איך העבודה גדלה כשהקלט גדל, ומתעלם בכוונה מקבועים — כי בגדלים קטנים רק הקבועים משנים, ובגדלים גדולים רק צורת הגדילה. O(1) אומר שהגודל לא משנה. O(n) אומר שפי שניים נתונים זה פי שניים עבודה. O(n²) אומר שפי שניים נתונים זה פי ארבע עבודה, ופי עשרה נתונים זה פי מאה עבודה.\n\nהאחרון הוא המלכודת, כי הוא בלתי נראה עד שהוא לא. ג׳וב סנכרון השווה שתי רשימות כדי למצוא אילו רשומות חדשות, בעזרת filter עם includes בתוכו — לולאה בתוך לולאה, גם אם זה נקרא כשורה אחת. עם 500 רשומות בכל צד זה 250,000 השוואות והוא סיים בערך ב-12 מילישניות; אף אחד לא חשב על זה שנה. לקוח גדול יותר הגיע עם 20,000 רשומות: 400 מיליון השוואות, והג׳וב לקח 45 שניות והתחיל ליפול בטיים-אאוט מול ה-API שהוא הזין. התיקון היה שורה אחת — לבנות Set מהרשימה השנייה קודם, ואז לבדוק שייכות — מה שהפך את זה ל-40,000 פעולות ו-30 מילישניות. אותו פלט, אותו אורך קוד, צורה אחרת.\n\nהשימוש המעשי ב-Big-O הוא חיזוי בלי ניסוי: מה קורה בפי מאה מהנתונים האלה. לא צריך את הגרסה הפורמלית כדי ליהנות מזה. תלמד לשים לב ללולאה בתוך לולאה על אותם נתונים, ל-includes או indexOf או find בתוך לולאה, ולקווירי לדאטהבייס בתוך לולאה — שלושת אלה מכסים את רוב מה שבאמת נושך. כולם נראים בסדר בקנה מידה של פיתוח, ובגלל זה בדיקות לא תופסות אותם. כשסוכן מגיש לך פונקציה שמעבדת נתונים, תשאל מה היא עושה במאה אלף פריטים, ואיפה הלולאה המקוננת."},

"Blocking vs async": {
 "en": "Waiting is not work. Async exists so that a program waiting for a disk, a database or a network can spend that time serving somebody else instead of standing still. Blocking code holds its thread while it waits; async code hands the thread back and picks up again when the answer arrives.\n\nThis matters most where there is only one thread to hold. A Node API added a feature that read a 40MB configuration file with readFileSync on each request — synchronous, simple, and correct. On a developer machine with a warm file cache it took 15 milliseconds and looked fine. In production it took 380 milliseconds, and because Node runs your code on a single thread, that was 380 milliseconds during which no other request could be served at all. The health-check endpoint, which touched nothing, started timing out. p95 across the whole service went from 90 milliseconds to 2.1 seconds, and every graph pointed at endpoints that were entirely innocent. Reading the file once at startup fixed it; the async version would also have fixed it.\n\nThe sneaky half is that CPU work blocks too, and there is no await to warn you. Parsing a 20MB JSON payload, hashing a password with a high cost factor, resizing an image, or looping a million times all hold the thread just as firmly as a synchronous read — and none of them look like blocking calls. The rule: in a request handler, never call anything ending in Sync, and move heavy CPU work to a queue or a worker. And when debugging a service where everything is slow at once rather than one endpoint, suspect a blocked event loop before you suspect the database. All-endpoints-slow is the signature of a blocked thread; one-endpoint-slow is usually a query. That one distinction will save you an afternoon the first time it happens.",
 "he": "המתנה היא לא עבודה. אסינכרוני קיים כדי שתוכנית שמחכה לדיסק, לדאטהבייס או לרשת תוכל לנצל את הזמן הזה לשרת מישהו אחר במקום לעמוד. קוד בלוקינג מחזיק את הת׳רד שלו בזמן ההמתנה; קוד אסינכרוני מחזיר את הת׳רד וממשיך כשהתשובה מגיעה.\n\nזה משנה הכי הרבה כשיש רק ת׳רד אחד להחזיק. API בנוד הוסיף פיצ׳ר שקרא קובץ קונפיגורציה של 40 מגה עם readFileSync בכל בקשה — סינכרוני, פשוט, ונכון. על מכונת פיתוח עם מטמון קבצים חם זה לקח 15 מילישניות ונראה בסדר. בפרודקשן זה לקח 380 מילישניות, ומכיוון שנוד מריץ את הקוד שלך על ת׳רד אחד, אלה היו 380 מילישניות שבהן אף בקשה אחרת לא יכלה להיות משורתת בכלל. אנדפוינט בדיקת הבריאות, שלא נגע בכלום, התחיל ליפול בטיים-אאוט. ה-p95 של כל השירות עלה מ-90 מילישניות ל-2.1 שניות, וכל הגרפים הצביעו על אנדפוינטים תמימים לגמרי. קריאת הקובץ פעם אחת בעלייה פתרה את זה; גם הגרסה האסינכרונית הייתה פותרת.\n\nהחצי הערמומי הוא שגם עבודת CPU חוסמת, ואין שם await שיזהיר אותך. פרסור פיילוד JSON של 20 מגה, האשינג של סיסמה עם cost factor גבוה, שינוי גודל תמונה, או לולאה של מיליון איטרציות — כולם מחזיק את הת׳רד באותה עוצמה כמו קריאה סינכרונית, ואף אחד מהם לא נראה כמו קריאה חוסמת. הכלל: במטפל בקשה, לעולם לא לקרוא למשהו שנגמר ב-Sync, ולהעביר עבודת CPU כבדה לתור או ל-worker. וכשמדבגים שירות שבו הכל איטי בבת אחת ולא אנדפוינט אחד, תחשוד באיוונט לופ חסום לפני שאתה חושד בדאטהבייס. ״כל האנדפוינטים איטיים״ היא החתימה של ת׳רד חסום; ״אנדפוינט אחד איטי״ זה בדרך כלל קווירי. ההבחנה הזו לבדה תחסוך לך אחר צהריים בפעם הראשונה שזה קורה."},

"Race condition": {
 "en": "A race is a bug in your assumptions about time. Your code reads a value, decides something based on it, and writes — and between the read and the write, reality changed. Nothing in the code is wrong when you read it line by line, which is exactly why races survive review.\n\nA shop sold concert tickets. The handler read the remaining count, checked it was above zero, and wrote count minus one. On a quiet Tuesday this is flawless. On sale day, two requests arrived four milliseconds apart for the last ticket: both read 1, both saw 1 is greater than 0, both wrote 0, and two people were sold the same seat. It happened eleven times that morning out of 9,000 orders — roughly one in eight hundred, which is invisible in testing and expensive in refunds and apologies. The same shape produces double charges when someone double-clicks Pay, and duplicate users when a signup is submitted twice. The fix was not a retry or a delay. It was to let the database decide in one statement: update the count where the count is still above zero, then check how many rows that actually changed. One request gets 1 and wins; the other gets 0 and is told it sold out.\n\nThe structural fixes are all versions of that idea: do the check and the change in one atomic operation, use a transaction with the right isolation, add a unique constraint so the database refuses the second one, or design the operation so that doing it twice is harmless and give it an idempotency key. Retrying makes races more likely, not less. This is a category an agent will almost never raise on its own, because read-check-write is the most natural way to express the logic. Ask it directly, on anything involving money, stock, or a limit: what happens if two of these run at the same millisecond.",
 "he": "רייס הוא באג בהנחות שלך לגבי זמן. הקוד שלך קורא ערך, מחליט משהו על בסיסו, וכותב — ובין הקריאה לכתיבה, המציאות השתנתה. שום דבר בקוד לא שגוי כשקוראים אותו שורה-שורה, ובדיוק בגלל זה רייסים שורדים ריוויו.\n\nחנות מכרה כרטיסים להופעה. המטפל קרא את הכמות שנותרה, בדק שהיא גדולה מאפס, וכתב כמות פחות אחת. ביום שלישי שקט זה מושלם. ביום המכירה, שתי בקשות הגיעו בהפרש של ארבע מילישניות על הכרטיס האחרון: שתיהן קראו 1, שתיהן ראו ש-1 גדול מ-0, שתיהן כתבו 0, ושני אנשים קנו את אותו מושב. זה קרה אחת עשרה פעמים באותו בוקר מתוך 9,000 הזמנות — בערך אחד לשמונה מאות, שזה בלתי נראה בבדיקות ויקר בזיכויים והתנצלויות. אותה צורה מייצרת חיוב כפול כשמישהו לוחץ פעמיים על ״שלם״, ומשתמשים כפולים כשטופס הרשמה נשלח פעמיים. הפתרון לא היה ניסיון חוזר או השהיה. הוא היה לתת לדאטהבייס להחליט בפקודה אחת: לעדכן את הכמות היכן שהכמות עדיין גדולה מאפס, ואז לבדוק כמה שורות באמת השתנו. בקשה אחת מקבלת 1 ומנצחת; השנייה מקבלת 0 ומקבלת הודעה שאזל.\n\nהתיקונים המבניים הם כולם גרסאות של הרעיון הזה: לעשות את הבדיקה ואת השינוי בפעולה אטומית אחת, להשתמש בטרנזקציה עם רמת בידוד מתאימה, להוסיף אילוץ ייחודיות כדי שהדאטהבייס ידחה את השנייה, או לתכנן את הפעולה כך שביצוע כפול לא מזיק ולתת לה מפתח אידמפוטנטיות. ניסיון חוזר הופך רייסים לסבירים יותר, לא פחות. זו קטגוריה שסוכן כמעט אף פעם לא יעלה מיוזמתו, כי ״לקרוא, לבדוק, לכתוב״ היא הדרך הכי טבעית לבטא את הלוגיקה. תשאל אותו ישירות, בכל דבר שנוגע לכסף, למלאי או למגבלה: מה קורה אם שניים מאלה רצים באותה מילישנייה."},
})


EXAMPLES_FIX = {

"SQL vs NoSQL": {"cap": {"en": "Same data, two contracts", "he": "אותם נתונים, שני חוזים"},
 "code": "-- SQL: the shape is declared once, the DB enforces it forever\nCREATE TABLE customers (\n  id      uuid PRIMARY KEY,\n  email   text NOT NULL UNIQUE,      -- two rows can never share one\n  country char(2) NOT NULL           -- always 'IL', never 'Israel'\n);\n\n// NoSQL: the shape is whatever the last writer felt like\n{ \"_id\": 1, \"email\": \"a@x.com\", \"country\": \"IL\" }\n{ \"_id\": 2, \"email\": \"a@x.com\", \"Country\": \"Israel\" }  // dupe + 2 spellings\n{ \"_id\": 3, \"address\": { \"country\": \"il\" } }            // 3rd field path\n\n// db.customers.find({ country: \"IL\" }) returns 1 of 3. Nothing errored."},

"Compiled vs interpreted": {"cap": {"en": "Same job, two feedback loops", "he": "אותה עבודה, שתי לולאות משוב"},
 "code": "# interpreted: no build step, error found only when the line runs\n$ python reshape.py orders.csv\nTraceback (most recent call last):\n  File \"reshape.py\", line 88, in <module>\n    total = row[\"qty\"] * row[\"prce\"]      # typo, found after 84s of work\nKeyError: 'prce'\n\n# compiled: the typo never reaches runtime\n$ go build ./...\n./reshape.go:88:29: row.prce undefined (type Order has no field prce)\n\n$ go build -o reshape && ./reshape orders.csv   # one binary, no runtime needed\n$ python reshape.py                             # needs python 3.11 + 14 packages"},

"JavaScript / TypeScript": {"cap": {"en": "Types erased at build; only JS ships", "he": "הטיפוסים נמחקים בבילד; רק JS עולה לאוויר"},
 "code": "// order.ts - what you write\nexport type Order = { id: string; qty: number; paidAt: Date }\nexport function isPaid(o: Order): boolean { return o.paidAt !== null }\n\n// order.js - what actually runs in production. Types are gone.\nexport function isPaid(o) { return o.paidAt !== null }\n\n// which is why this compiles and still breaks at runtime:\nconst o = await res.json() as Order   // \"as\" is a promise, not a check\no.paidAt.getFullYear()                // JSON has no Date -> it is a string\n\n// parse at the boundary instead of asserting:\nconst o = OrderSchema.parse(await res.json())   // zod: throws on bad shape"},

"Python": {"cap": {"en": "Pin the environment, or it drifts", "he": "לקבע את הסביבה, אחרת היא נסחפת"},
 "code": "# requirements.txt - pinned. reproducible in a year.\npandas==2.2.2\nrequests==2.32.3\n\n# NOT this - \"whatever is newest the day CI runs\"\n# pandas\n# requests\n\n$ python -m venv .venv && source .venv/bin/activate   # per project, always\n$ pip install -r requirements.txt\n$ pip freeze > requirements.txt    # record exactly what you got\n\n# type hints + a checker = most of what TypeScript gives you\ndef total(qty: int, price: float) -> float: return qty * price\n$ mypy reconcile.py\nreconcile.py:14: error: Argument 1 has incompatible type \"str\"; expected \"int\""},

"Go / Rust / Java / C#": {"cap": {"en": "How each one tells you something went wrong", "he": "איך כל אחת מהן אומרת לך שמשהו השתבש"},
 "code": "// Go - errors are values you must handle on the spot\nrow, err := db.GetOrder(id)\nif err != nil { return fmt.Errorf(\"get order %s: %w\", id, err) }\n\n// Rust - the compiler refuses to build until you deal with it\nlet row = db.get_order(id)?;        // ? propagates; ignoring it will not compile\n\n// C# / Java - exceptions thrown up the stack, caught somewhere above\nvar row = db.GetOrder(id);          // throws OrderNotFoundException\n\n// what a repo tells you at a glance:\ngo.mod          -> Go     : small service, explicit errors\nCargo.toml      -> Rust   : perf or systems work, steep review\npom.xml         -> Java   : enterprise, framework conventions rule\n*.csproj        -> C#     : same, Microsoft stack"},

"Dependency": {"cap": {"en": "14 direct, 1,190 actually installed", "he": "14 ישירות, 1,190 מותקנות בפועל"},
 "code": "$ npm ls --all | wc -l\n1190                      # 14 lines in package.json got you this\n\n$ npm audit\n# npm audit report\nminimist  <1.2.6\nSeverity: critical - Prototype Pollution\nfix available via `npm audit fix --force`\nWill install next@13.5.6, which is a breaking change\n\n$ npm view is-email-valid time.modified\n'2021-04-02T08:12:44.000Z'    # last release 4 years ago = abandoned\n\n// the 40KB dependency this replaces:\nconst ok = /^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$/.test(email)"},

"Framework vs library": {"cap": {"en": "Who owns the structure", "he": "מי מחזיק במבנה"},
 "code": "// LIBRARY - you own the file layout, you call it when you want\nimport { format } from 'date-fns'\nconst label = format(order.createdAt, 'dd/MM/yyyy')\n\n// FRAMEWORK - the folder IS the routing table; it calls you\napp/\n  layout.tsx                 <- called on every page, whether you like it or not\n  orders/\n    page.tsx                 <- becomes GET /orders\n    [id]/page.tsx            <- becomes GET /orders/:id\n    loading.tsx              <- rendered automatically while page.tsx awaits\n\n// the tax: your auth must live where the framework says sessions live.\n// the leverage: routing, SSR and code splitting cost you zero lines."},

"RAM vs disk": {"cap": {"en": "What a restart deletes", "he": "מה שהפעלה מחדש מוחקת"},
 "code": "// RAM: gone on every deploy, and invisible to the other instance\nconst sessions = new Map()\napp.post('/login', (req, res) => sessions.set(sid, user))\n\n// 14:05 deploy -> every user logged out mid-task\n// 2 instances   -> half the requests hit the one that never saw you\n\n// Disk/Redis: survives restarts, shared by every instance\nawait redis.set(`sess:${sid}`, JSON.stringify(user), 'EX', 86400)\n\n// rough cost of one read, same order of magnitude every time:\n// RAM   ~100ns | SSD ~100us (1,000x) | network ~1ms | cross-region ~100ms"},

"Garbage collection": {"cap": {"en": "A pause you can see in the graph", "he": "פאוזה שרואים בגרף"},
 "code": "$ node --trace-gc server.js\n[1] Scavenge 62.1 (69.0) -> 12.4 (69.0) MB, 1.2 ms      <- minor, harmless\n[1] Scavenge 63.8 (69.0) -> 13.1 (69.0) MB, 1.4 ms\n[1] Mark-Compact 2984.2 (3051.0) -> 402.7 (1180.0) MB, 912 ms  <- the spike\n\n# 912ms during which your process served nobody.\n# matches the p99 complaints exactly. memory graph = sawtooth:\n#   3GB /|  /|  /|      <- fills fast, big collection, drops back\n#        | / | / | /\n\n# the fix is allocating less per request, not a --max-old-space-size flag"},

"Latency vs throughput": {"cap": {"en": "Two paths, because two different users", "he": "שני מסלולים, כי שני משתמשים שונים"},
 "code": "// BULK path - throughput wins, 5s of waiting costs nothing\nqueue.add('marketing', msg, { batchSize: 500, flushAfterMs: 5000 })\n//   50/s -> 2,000/s\n\n// INTERACTIVE path - latency wins, a human is watching a spinner\nawait mailer.send(resetEmail)      // straight out, no batching\n\n// and measure the tail, never the average:\n//   avg 120ms   <- hides everything\n//   p50  90ms   p95 480ms   p99 2.1s   <- p99 is who files the ticket"},
}


# ============================== HEBREW FIXES ==============================
# Only terms whose Hebrew was wrong, awkward, or used a word Israeli devs
# do not actually say. Terms not listed here were already fine.

HE_FIX = {

# "מסד נתונים" is correct but nobody says it out loud; "דאטהבייס" is what
# is actually spoken, with the English kept in parentheses.
"Database": {
 "t": {"he": "דאטהבייס (Database)"}},

# "שאילתה" is the textbook word; developers say "קווירי".
"Query": {
 "t": {"he": "קווירי (Query)"},
 "w": {"he": "קווירי אחד כתוב רע יכול להפיל אתר שלם. זו סיבת התקלה הנפוצה ביותר."}},

# "יורה שאילתות" -> "קווריז", which is the plural people actually use.
"ORM": {
 "w": {"he": "נוח עד שהוא יורה בשקט 1,000 קווריז בלולאה. תלמד להסתכל על ה-SQL שהוא מייצר."}},

# "טיפוסית מול לא-טיפוסית" is not Hebrew anyone speaks. Developers say
# "עם טיפוסים / בלי טיפוסים".
"Typed vs untyped": {
 "t": {"he": "עם טיפוסים מול בלי טיפוסים"},
 "d": {"he": "שפות עם טיפוסים בודקות שמספר לא משמש כטקסט עוד לפני ההרצה. שפות בלי טיפוסים מגלות את זה בזמן ריצה."}},

# "מהודרת מול מפורשת" is purist Hebrew nobody uses; it is "קומפילציה" and
# "אינטרפרטר" in every Israeli team. "קובץ הרצה" -> "בינארי".
"Compiled vs interpreted": {
 "t": {"he": "קומפילציה מול אינטרפרטציה"},
 "d": {"he": "שפה מקומפלת (Go, Rust, C#) בונה בינארי קודם — מהיר להרצה. שפה מפורשת (Python, JS) מריצה את הקוד ישירות — מהיר לשינוי."}},

# "לקמט אותו ל-Git" means "to crumple it". The word is קומיט.
"Package manager": {
 "w": {"he": "קובץ ה-lock הוא מה שהופך את הבילד לניתן לשחזור. תמיד לעשות לו קומיט."}},

# "במשרה" is not how a job ad is referred to in Hebrew.
"Go / Rust / Java / C#": {
 "w": {"he": "לזהות אותן במודעת דרושים או ברפו מספר לך באיזה סוג צוות מדובר."}},

# "העלאת גרסה" -> "דיפלוי", which is the word actually used.
"RAM vs disk": {
 "w": {"he": "כל מה שאתה מחזיק ״במשתנה״ נעלם בכל דיפלוי. מצב שחשוב הולך לדאטהבייס."}},

# "מחסנית וערימה" is the academic translation; Israeli developers say
# "סטאק" and "היפ", and the English crash messages use those words too.
# The English "manually managed" is also misleading in a GC language.
"Stack & heap": {
 "t": {"he": "סטאק והיפ (Stack & heap)"},
 "d": {"he": "סטאק: קטן, מסודר, אוטומטי — משתנים מקומיים ושרשרת הקריאות. היפ: גדול, גמיש, אזור האובייקטים שה-GC מנקה."},
 "w": {"he": "״Stack overflow״ = פונקציה קראה לעצמה בלי סוף. ״Out of memory״ = ההיפ התמלא."}},

# "איסוף זבל" is not said out loud; it is "גרבג׳ קולקשן".
"Garbage collection": {
 "t": {"he": "גרבג׳ קולקשן (GC)"},
 "d": {"he": "הראנטיים משחרר אוטומטית זיכרון שאף אחד כבר לא מצביע אליו. חינם, אבל עוצר את התוכנית לרגע."},
 "w": {"he": "מסביר קפיצות לייטנסי אקראיות בשירות שאחרת נראה רגוע לגמרי."}},

# "דליפת זיכרון" is fine; "ליק" is what is said in a war room, so keep both.
"Memory leak": {
 "t": {"he": "ליק זיכרון (Memory leak)"}},

# "זמן תגובה מול תפוקה" loses the word developers actually use, and
# "אצוות" is not how batching is said.
"Latency vs throughput": {
 "t": {"he": "לייטנסי מול תפוקה (Throughput)"},
 "d": {"he": "לייטנסי: כמה זמן לוקחת בקשה אחת. תפוקה: כמה בקשות מטפלים בשנייה."},
 "w": {"he": "יש ביניהם מתח. באטצ׳ינג מעלה תפוקה ופוגע בלייטנסי. תבחר מה המשתמשים שלך מרגישים."}},

# "חוסם" alone is not the spoken term, and the geresh in "ת'רד" is a typo.
"Blocking vs async": {
 "t": {"he": "בלוקינג מול אסינכרוני"},
 "d": {"he": "קוד בלוקינג ממתין ותופס את הת׳רד. אסינכרוני מתחיל את העבודה ומטפל בתוצאה אחר כך, ובינתיים משרת אחרים."},
 "w": {"he": "קריאה חוסמת אחת בשרת Node מקפיאה את כל המשתמשים, לא רק את זה שממתין."}},

# "מצב מירוץ" is a literal translation; the term used in Israeli teams is
# "רייס קונדישן".
"Race condition": {
 "t": {"he": "רייס קונדישן (Race condition)"},
 "w": {"he": "משחזר פעם בשבוע, אף פעם לא אצלך. פותרים עם טרנזקציה או נעילה, לא עם ניסיון חוזר."}},

# "מסד הנתונים" and "מסד נתונים" are used interchangeably in this course;
# align the migration warning on the spoken word.
"Migration": {
 "w": {"he": "עריכה ידנית של הדאטהבייס בפרודקשן היא הדרך שבה סביבות מתפצלות ואף אחד לא מצליח לשחזר באג."}},
}
