# -*- coding: utf-8 -*-
"""Deepening pass 3: Cache, Auth & Security.

DETAIL_FIX / EXAMPLES_FIX / HE_FIX are merged over the base data at load time.
"""

DETAIL_FIX = {

 "Cache": {
  "en": "A cache is a bet: that the same question will be asked again soon, and that the answer will not have changed in between. You pay for the answer once — a database query, a third-party API call, a rendered page — and keep the result somewhere cheaper to reach: RAM, a file on disk, a server in Frankfurt, the user's own browser. Every cache is therefore two things at the same time. It is a speed layer, and it is a second copy of the truth that is allowed to be wrong. The whole craft is deciding how wrong, for how long, and who is likely to notice.\n\nA shop drops a product from 249 to 199. The price lives in Postgres, but the product page sits at the CDN edge for an hour, the price object sits in Redis for fifteen minutes, and the browser was told it may keep the page for ten. The database changes instantly; what customers see is a staircase. Some get 199 within seconds, some in fifteen minutes, some in an hour, and anyone who loaded the page just before the change keeps seeing 249 until their own copy expires. Support gets three tickets about a price that \"didn't update\". Nothing is broken. Four caches are each doing exactly what they were told.\n\nWhen an agent adds caching for you, the code is almost always correct and almost never complete: it stores, it reads, and nothing ever removes the entry when the underlying row changes. Ask two questions before you accept it. What goes into the key — does it include everything that can change the answer, the user id, the language, the currency? And what makes the entry go away: a TTL, a write path, or nothing at all? Then ask where it lives. A dictionary inside the process works beautifully on your laptop and quietly disagrees with itself the moment the app runs on two machines.",
  "he": "קאש הוא הימור: שאותה שאלה תישאל שוב בקרוב, ושהתשובה לא תשתנה בינתיים. אתה משלם על התשובה פעם אחת — שאילתה למסד, קריאה ל-API חיצוני, רינדור של דף — ושומר את התוצאה במקום זול יותר להגיע אליו: RAM, קובץ על הדיסק, שרת בפרנקפורט, הדפדפן של המשתמש עצמו. לכן כל קאש הוא שני דברים בו-זמנית. הוא שכבת מהירות, והוא עותק שני של האמת שמותר לו להיות שגוי. כל המלאכה היא להחליט כמה שגוי, לכמה זמן, ומי צפוי לשים לב.\n\nחנות מורידה מוצר מ-249 ל-199. המחיר יושב ב-Postgres, אבל דף המוצר יושב ב-CDN במשך שעה, אובייקט המחיר יושב ב-Redis חמש-עשרה דקות, ולדפדפן נאמר שמותר לו להחזיק את הדף עשר דקות. המסד משתנה מיד; מה שהלקוחות רואים הוא מדרגות. חלק מקבלים 199 תוך שניות, חלק אחרי רבע שעה, חלק אחרי שעה, ומי שטען את הדף רגע לפני השינוי ימשיך לראות 249 עד שהעותק שלו יפוג. התמיכה מקבלת שלוש פניות על מחיר ש״לא התעדכן״. שום דבר לא שבור. ארבעה קאשים עושים בדיוק את מה שאמרו להם.\n\nכשסוכן מוסיף לך קאש, הקוד כמעט תמיד נכון וכמעט אף פעם לא שלם: הוא שומר, הוא קורא, ושום דבר לא מוחק את הרשומה כשהשורה שמאחוריה משתנה. תשאל שתי שאלות לפני שאתה מקבל את זה. מה נכנס למפתח — האם הוא כולל כל מה שיכול לשנות את התשובה, מזהה המשתמש, השפה, המטבע? ומה גורם לרשומה להיעלם: TTL, מסלול הכתיבה, או כלום? ואז תשאל איפה זה חי. מילון בתוך התהליך עובד מצוין על הלפטופ שלך, ומתחיל לסתור את עצמו בשקט ברגע שהאפליקציה רצה על שתי מכונות."},

 "Hit / Miss": {
  "en": "Every cache lookup ends one of two ways. A hit: the copy was there, you return it, and the expensive work never happens. A miss: nothing was stored under that key, so you do the full work — query the database, call the API, render the page — and store the result so the next caller hits. Hit rate is simply the share of lookups that ended the first way, and it is the only number that tells you whether the cache is earning its place. A cache that never hits is not neutral. It is an extra network round trip plus a serialization step added to every single request, in exchange for nothing.\n\nA team adds caching to a product listing and the hit rate settles at 4%. The caching logic is perfect; the key is wrong. It was built as products:{categoryId}:{timestamp}, because somebody wanted freshness, and the timestamp comes from the current clock — so every request writes a brand-new entry that no one will ever read again. Redis fills with roughly 40,000 dead keys an hour and starts evicting the entries that would have been useful. The fix is deleting one segment of the key and controlling freshness with a TTL instead. Hit rate goes to 91% overnight and the listing endpoint drops from 340ms to 12ms.\n\nTwo failure modes are worth holding in your head. Anything in the key that varies per request but does not change the answer — a request id, a clock reading, a trace header — kills the cache silently. Anything missing from the key that does change the answer causes something far worse: user A being served user B's data. So make the agent state, out loud, exactly what goes into the key and why each part is there. Then measure. If the cache does not report a hit rate, a working cache and a broken one look identical in the code, and both look fine in review.",
  "he": "כל פנייה לקאש נגמרת באחת משתי דרכים. פגיעה (hit): העותק היה שם, אתה מחזיר אותו, והעבודה היקרה בכלל לא קורית. פספוס (miss): לא היה כלום תחת המפתח הזה, אז אתה עושה את כל העבודה — שאילתה למסד, קריאה ל-API, רינדור של הדף — ושומר את התוצאה כדי שהפונה הבא ייפגע. אחוז הפגיעות הוא פשוט החלק מהפניות שנגמרו בדרך הראשונה, וזה המספר היחיד שאומר לך אם הקאש מצדיק את קיומו. קאש שאף פעם לא פוגע הוא לא ניטרלי. הוא סבב רשת נוסף ועוד שלב סריאליזציה שנוספו לכל בקשה בודדת, בתמורה לכלום.\n\nצוות מוסיף קאש לרשימת מוצרים ואחוז הפגיעות מתייצב על 4%. לוגיקת הקאש מושלמת; המפתח שגוי. הוא נבנה כ-products:{categoryId}:{timestamp}, כי מישהו רצה טריות, והחותמת זמן מגיעה מהשעון הנוכחי — כך שכל בקשה כותבת רשומה חדשה לגמרי שאף אחד לעולם לא יקרא. Redis מתמלא בערך ב-40,000 מפתחות מתים בשעה ומתחיל לפנות דווקא את הרשומות שהיו מועילות. התיקון הוא מחיקה של מקטע אחד מהמפתח, ושליטה בטריות דרך TTL במקום. אחוז הפגיעות עולה ל-91% בן לילה ונקודת הקצה יורדת מ-340ms ל-12ms.\n\nשני כשלים ששווה להחזיק בראש. כל דבר במפתח שמשתנה מבקשה לבקשה אבל לא משנה את התשובה — מזהה בקשה, קריאת שעון, כותרת מעקב — הורג את הקאש בשקט. כל דבר שחסר במפתח ודווקא כן משנה את התשובה גורם למשהו גרוע בהרבה: משתמש א׳ מקבל את הנתונים של משתמש ב׳. אז תגרום לסוכן להגיד במפורש מה בדיוק נכנס למפתח ולמה כל חלק שם. ואז תמדוד. אם הקאש לא מדווח אחוז פגיעות, קאש עובד וקאש שבור נראים זהים בקוד, ושניהם נראים בסדר בביקורת."},

 "TTL": {
  "en": "TTL — time to live — is the one dial every cache has. You are not setting a performance number; you are signing a promise about staleness. A TTL of 300 seconds says: for the next five minutes I accept serving an answer that may already be out of date, in exchange for not doing this work again. Derive it from tolerance, never from a feeling. How wrong can this value be before a user is confused, a report is misleading, or someone loses money? A currency table can be a day old. A shopping cart cannot be thirty seconds old.\n\nA storefront caches exchange rates for 24 hours because rates \"barely move\". One afternoon the shekel moves 3% in two hours. For the rest of that day every order is priced off the morning's rate, and on roughly 1,400 orders averaging 300 the shop eats about 12,600 in margin it never sees on any dashboard, because nothing errored. The opposite failure is just as real: the same team later sets a 30-second TTL on the homepage feed, all 50,000 cached keys were written during the same deploy, so they all expire in the same second and 50,000 requests hit the database simultaneously. The site goes down at a moment of zero traffic change.\n\nSo two habits. Add jitter — a TTL of 300 plus a random 0 to 60 seconds — so expiries spread out instead of arriving as a wall. And where the platform supports it, prefer stale-while-revalidate: serve the slightly old copy immediately and refresh it in the background, which gives you a short effective freshness window without a latency spike on every expiry. When an agent writes a caching layer, it will pick a round number like 3600 with no reasoning attached. Replace it with a number you can justify in one sentence, and write that sentence next to it.",
  "he": "TTL — time to live — הוא החוגה היחידה שיש לכל קאש. אתה לא מגדיר מספר ביצועים; אתה חותם על הבטחה לגבי מידת היושן. TTL של 300 שניות אומר: בחמש הדקות הקרובות אני מקבל שמגישים תשובה שאולי כבר לא מעודכנת, בתמורה לכך שלא אעשה את העבודה הזאת שוב. תגזור אותו מסבילות, אף פעם לא מתחושה. כמה שגוי הערך הזה יכול להיות לפני שמשתמש מתבלבל, דוח מטעה, או מישהו מפסיד כסף? טבלת מטבעות יכולה להיות בת יום. עגלת קניות לא יכולה להיות בת שלושים שניות.\n\nחנות שומרת שערי המרה ל-24 שעות כי שערים ״כמעט לא זזים״. אחר צהריים אחד השקל זז ב-3% בתוך שעתיים. כל שאר היום כל הזמנה מתומחרת לפי שער הבוקר, ועל בערך 1,400 הזמנות בממוצע 300 החנות סופגת כ-12,600 ברווח שלא מופיע באף דשבורד, כי שום דבר לא נכשל. הכשל ההפוך אמיתי בדיוק באותה מידה: אותו צוות קובע אחר כך TTL של 30 שניות על פיד הבית, כל 50,000 המפתחות נכתבו באותו דיפלוי, אז כולם פגים באותה שנייה ו-50,000 בקשות מגיעות למסד בו-זמנית. האתר נופל בלי שום שינוי בתעבורה.\n\nלכן שני הרגלים. תוסיף ג׳יטר — TTL של 300 ועוד 0 עד 60 שניות אקראיות — כדי שהפקיעות יתפזרו במקום להגיע כקיר. ואיפה שהפלטפורמה תומכת, תעדיף stale-while-revalidate: להגיש מיד את העותק המעט ישן ולרענן אותו ברקע, מה שנותן חלון טריות קצר בלי קפיצת זמן תגובה בכל פקיעה. כשסוכן כותב שכבת קאש, הוא יבחר מספר עגול כמו 3600 בלי שום נימוק. תחליף אותו במספר שאתה יכול להצדיק במשפט אחד, ותכתוב את המשפט הזה לידו."},

 "Invalidation": {
  "en": "Invalidation is deliberately throwing away a cached copy because you know the underlying data changed — as opposed to waiting for a TTL to expire it for you. It sounds like the obviously correct approach, and it is the reason the old joke calls cache invalidation one of the two hard problems in computing. The difficulty is not deleting a key. The difficulty is knowing, at the moment of a write, every place in the system that is currently holding a copy derived from that data, and reaching all of them.\n\nA user edits their display name. The name is cached in Redis under user:88, but it is also baked into the cached comment list for every thread they posted in, the cached team roster, the rendered profile page held at 200 CDN edge locations, and the JSON the mobile app stored on the phone last week. The developer deletes user:88, confirms it works in the profile page, and ships. A week later someone reports that the old name is still showing under three comments. It will keep showing until those cached lists expire on their own — and nobody remembers what TTL they were given, because they were added by a different pull request eight months earlier.\n\nThis is why experienced people prefer boring alternatives. A short TTL means every copy is self-correcting within a known window with no bookkeeping at all. Key versioning — putting a value's updated-at timestamp or a version number into the key itself — makes old entries unreachable the instant the data changes, so you never delete anything; the old keys just age out. Reserve real invalidation for the few places where staleness is genuinely unacceptable. And when an agent writes an invalidation call, the question to ask is not whether that line is correct, but which other keys were built from this same row, and who is deleting those.",
  "he": "ביטול תוקף הוא זריקה מכוונת של עותק שמור כי אתה יודע שהנתונים שמאחוריו השתנו — בניגוד להמתנה ל-TTL שיפיג אותו בשבילך. זה נשמע כמו הגישה הנכונה מאליה, וזאת בדיוק הסיבה שהבדיחה הישנה קוראת לזה אחת משתי הבעיות הקשות במחשוב. הקושי הוא לא למחוק מפתח. הקושי הוא לדעת, ברגע הכתיבה, כל מקום במערכת שמחזיק כרגע עותק שנגזר מהנתון הזה, ולהגיע לכולם.\n\nמשתמש עורך את שם התצוגה שלו. השם שמור ב-Redis תחת user:88, אבל הוא גם אפוי בתוך רשימת התגובות השמורה של כל שרשור שהוא כתב בו, ברשימת חברי הצוות השמורה, בדף הפרופיל המרונדר שיושב ב-200 נקודות קצה של ה-CDN, וב-JSON שאפליקציית המובייל שמרה על הטלפון לפני שבוע. המפתח מוחק את user:88, מוודא שדף הפרופיל תקין, ומשחרר. שבוע אחר כך מישהו מדווח שהשם הישן עדיין מופיע מתחת לשלוש תגובות. הוא ימשיך להופיע עד שהרשימות השמורות האלה יפוגו מעצמן — ואף אחד לא זוכר איזה TTL ניתן להן, כי הן נוספו ב-pull request אחר לפני שמונה חודשים.\n\nבגלל זה אנשים מנוסים מעדיפים חלופות משעממות. TTL קצר אומר שכל עותק מתקן את עצמו בתוך חלון ידוע, בלי שום ניהול רישומים. גרסאות במפתח — להכניס את חותמת העדכון של הערך או מספר גרסה לתוך המפתח עצמו — הופכת רשומות ישנות לבלתי נגישות ברגע שהנתון משתנה, כך שאתה לא מוחק כלום; המפתחות הישנים פשוט מתיישנים ונופלים. תשמור ביטול תוקף אמיתי למעט המקומות שבהם יושן באמת לא מתקבל על הדעת. וכשסוכן כותב קריאת ביטול תוקף, השאלה היא לא אם השורה הזאת נכונה, אלא אילו מפתחות נוספים נבנו מאותה שורת נתונים, ומי מוחק אותם."},

 "Browser cache": {
  "en": "The browser keeps a private copy of most things it downloads — JavaScript bundles, stylesheets, fonts, images — keyed by URL, and decides how long to trust each one from the Cache-Control header the server sent with it. This is not an optimization you opt into; it is on by default for every visitor, and it is the cache closest to the user, which makes it both the fastest and the one you have the least control over once a file has been handed out.\n\nHere is the shape of the incident. You fix a bug, deploy, refresh, and it looks fine on your machine. Users report it is still broken. Your HTML was served with a one-hour Cache-Control, and the HTML is what points at your JavaScript file — so for the next hour a large share of returning visitors load the old HTML from disk, which requests the old script, which contains the old bug. You cannot reach those copies; there is no purge button for someone else's laptop. The standard fix is to make the filename change whenever the content changes — app.9f3c2a1.js — so new content is always a new URL, which lets you cache the assets for a year and cache the HTML for essentially zero.\n\nTwo practical habits. Before spending an hour debugging something that \"should already be fixed\", do a hard reload and check the Network tab: entries marked \"from disk cache\" or returning 304 are telling you the browser never asked. And when an AI generates your hosting config, look specifically at what Cache-Control it put on HTML versus on hashed assets. Getting those two backwards is one of the most common causes of a deploy that appears to have done nothing for everybody except you.",
  "he": "הדפדפן שומר עותק פרטי של רוב מה שהוא מוריד — באנדלים של JavaScript, גיליונות סגנון, פונטים, תמונות — לפי כתובת, ומחליט כמה זמן לסמוך על כל אחד מהם לפי כותרת Cache-Control שהשרת שלח איתו. זאת לא אופטימיזציה שאתה בוחר להיכנס אליה; היא דלוקה כברירת מחדל אצל כל מבקר, וזה הקאש הקרוב ביותר למשתמש — מה שהופך אותו גם למהיר ביותר וגם לזה שיש לך הכי פחות שליטה עליו ברגע שקובץ כבר יצא החוצה.\n\nזאת הצורה של התקלה. אתה מתקן באג, מעלה, מרענן, ונראה בסדר אצלך. משתמשים מדווחים שזה עדיין שבור. ה-HTML שלך הוגש עם Cache-Control של שעה, וה-HTML הוא זה שמצביע על קובץ ה-JavaScript — אז בשעה הקרובה חלק גדול מהמבקרים החוזרים טוענים את ה-HTML הישן מהדיסק, שמבקש את הסקריפט הישן, שמכיל את הבאג הישן. אתה לא יכול להגיע לעותקים האלה; אין כפתור ניקוי ללפטופ של מישהו אחר. התיקון הסטנדרטי הוא לגרום לשם הקובץ להשתנות בכל פעם שהתוכן משתנה — app.9f3c2a1.js — כך שתוכן חדש הוא תמיד כתובת חדשה, מה שמאפשר לשמור את הנכסים לשנה ואת ה-HTML כמעט לאפס.\n\nשני הרגלים מעשיים. לפני שאתה מבזבז שעה על דיבוג של משהו ש״כבר תוקן״, תעשה רענון קשיח ותסתכל בלשונית Network: שורות שמסומנות ״from disk cache״ או שמחזירות 304 אומרות לך שהדפדפן בכלל לא שאל. וכש-AI מייצר לך קונפיגורציה של אחסון, תסתכל בדיוק על איזה Cache-Control הוא שם על HTML לעומת נכסים עם האש. להפוך בין השניים זאת אחת הסיבות הנפוצות ביותר לדיפלוי שנראה כאילו לא עשה כלום לאף אחד חוץ ממך."},

 "CDN": {
  "en": "A CDN is a fleet of servers rented in dozens of cities that hold copies of your files close to whoever is asking. A visitor in Tel Aviv does not open a connection to your box in Virginia; they open one to a machine a few milliseconds away that already has your logo, your bundle and possibly your whole homepage. Your origin server only sees the requests the edge could not answer. That means the CDN is doing two jobs at once: cutting latency, and absorbing load your origin never has to be sized for.\n\nThe numbers are blunt. Tel Aviv to Virginia is roughly 180ms of round trip before a single byte of content; the same asset from a local edge is around 15ms, and a page that pulls thirty assets feels like a different product. Traffic-wise, a launch that sends 200,000 people to a static landing page can be served almost entirely from the edge at a trivial cost, while the same event against a bare origin is an outage. The classic disaster is the reverse: someone sets a blanket caching rule that also matches the logged-in dashboard, the edge stores one user's personalized page, and the next hundred visitors are served a page with a stranger's name and order history on it.\n\nSo the line to draw is about who the response belongs to. Content that is the same for everyone — assets, images, marketing pages, public reference data — belongs on the edge with a long life. Anything that varies per user, or that carries a Set-Cookie or an Authorization header, must be marked private and never stored there. When you let an AI write CDN or hosting rules, read them path by path and ask one question of each rule: could two different users receive this same stored response? If the answer is maybe, it is not cacheable at the edge.",
  "he": "CDN הוא צי שרתים ששכור בעשרות ערים ומחזיק עותקים של הקבצים שלך קרוב למי שמבקש אותם. מבקר בתל אביב לא פותח חיבור לשרת שלך בווירג׳יניה; הוא פותח חיבור למכונה במרחק כמה מילישניות שכבר מחזיקה את הלוגו שלך, את הבאנדל, ואולי את כל דף הבית. שרת המקור שלך רואה רק את הבקשות שהקצה לא הצליח לענות עליהן. כלומר ה-CDN עושה שתי עבודות בו-זמנית: מקצר השהיה, וסופג עומס שהמקור שלך אף פעם לא צריך להיות בנוי אליו.\n\nהמספרים בוטים. תל אביב לווירג׳יניה זה בערך 180ms של סבב עוד לפני בייט אחד של תוכן; אותו נכס מקצה מקומי הוא בערך 15ms, ודף שמושך שלושים נכסים מרגיש כמו מוצר אחר. מבחינת עומס, השקה ששולחת 200,000 אנשים לדף נחיתה סטטי מוגשת כמעט כולה מהקצה בעלות זניחה, בזמן שאותו אירוע מול מקור חשוף הוא נפילה. האסון הקלאסי הוא ההפך: מישהו מגדיר כלל קאש גורף שתופס גם את הדשבורד המחובר, הקצה שומר את הדף המותאם אישית של משתמש אחד, ומאה המבקרים הבאים מקבלים דף עם השם והזמנות של אדם זר.\n\nאז הקו שצריך למתוח הוא למי התשובה שייכת. תוכן שזהה לכולם — נכסים, תמונות, דפי שיווק, נתוני ייחוס ציבוריים — שייך לקצה עם חיים ארוכים. כל דבר שמשתנה לפי משתמש, או שנושא Set-Cookie או Authorization, חייב להיות מסומן private ואסור שיישמר שם. כשאתה נותן ל-AI לכתוב כללי CDN או אחסון, תקרא אותם נתיב-נתיב ותשאל כל כלל שאלה אחת: האם שני משתמשים שונים יכולים לקבל את אותה תשובה שמורה? אם התשובה היא אולי, זה לא ניתן לשמירה בקצה."},

 "Redis / in-memory store": {
  "en": "Redis is a separate database that keeps everything in RAM and answers in well under a millisecond. It is not a replacement for your Postgres; it is the shared scratch space that every one of your servers can reach. That word — shared — is the entire point. The moment your app runs as more than one process, any state you kept in a plain variable stops being one thing and becomes several things that disagree, and no error is raised when they do.\n\nThe failure looks like this. A rate limiter is implemented as a counter in a module-level map: 100 requests per minute per IP, tested locally, works. The app autoscales to three instances behind a load balancer, and each instance now keeps its own count, so the real limit is 300 per minute — and it drifts every time an instance restarts or a new one spins up. The same shape breaks sessions stored in process memory, where a user is logged in on one instance and logged out on the next, and it breaks background job locks, where three workers each believe they are the only one sending the invoice email. Moving the counter to a single Redis key with an expiry makes all three problems go away at once.\n\nTwo things to keep in mind when an agent reaches for it. Redis is memory, so treat it as disposable: it can restart, it can hit its memory limit and start evicting keys under an LRU policy, and it should never be the only place a piece of data exists. And every key you set should have an expiry unless you can explain why not — the slow leak where nothing ever expires is how a cache quietly becomes an unbounded, unbacked-up database that falls over at 3am. Ask where the state lives, and whether it survives a restart.",
  "he": "Redis הוא מסד נתונים נפרד שמחזיק הכל ב-RAM ועונה הרבה מתחת למילישנייה. הוא לא תחליף ל-Postgres שלך; הוא שטח העבודה המשותף שכל אחד מהשרתים שלך יכול להגיע אליו. המילה הזאת — משותף — היא כל העניין. ברגע שהאפליקציה שלך רצה ביותר מתהליך אחד, כל מצב ששמרת במשתנה רגיל מפסיק להיות דבר אחד והופך לכמה דברים שלא מסכימים ביניהם, ואף שגיאה לא נזרקת כשזה קורה.\n\nהכשל נראה ככה. מגביל קצב ממומש כמונה במפה ברמת המודול: 100 בקשות לדקה לכל IP, נבדק מקומית, עובד. האפליקציה מתרחבת אוטומטית לשלושה מופעים מאחורי מאזן עומסים, וכל מופע מחזיק עכשיו ספירה משלו, אז המגבלה האמיתית היא 300 לדקה — והיא נודדת בכל פעם שמופע מופעל מחדש או שנוסף חדש. אותה צורה שוברת סשנים שנשמרים בזיכרון התהליך, שבהם משתמש מחובר במופע אחד ומנותק בבא, והיא שוברת נעילות של משימות רקע, שבהן שלושה עובדים כל אחד בטוח שהוא היחיד ששולח את מייל החשבונית. העברת המונה למפתח יחיד ב-Redis עם פקיעה מעלימה את שלוש הבעיות בבת אחת.\n\nשני דברים לזכור כשסוכן מושיט יד ל-Redis. Redis הוא זיכרון, אז תתייחס אליו כאל בר-חלוף: הוא יכול לעלות מחדש, הוא יכול להגיע לתקרת הזיכרון ולהתחיל לפנות מפתחות לפי מדיניות LRU, ואסור שהוא יהיה המקום היחיד שבו נתון קיים. וכל מפתח שאתה כותב צריך פקיעה, אלא אם אתה יכול להסביר למה לא — הדליפה האיטית שבה שום דבר לא פג היא הדרך שבה קאש הופך בשקט למסד נתונים בלי גבול ובלי גיבוי שנופל בשלוש לפנות בוקר. תשאל איפה המצב חי, והאם הוא שורד הפעלה מחדש."},

 "Authentication vs Authorization": {
  "en": "Authentication answers \"who is this?\" — a password, a one-time code, a Google sign-in. Authorization answers \"is this person allowed to do this particular thing to this particular object?\" They are separate checks, they fail at separate moments, and confusing them is the single most common security hole in applications built quickly. Authentication tends to get built carefully because it is visible: there is a login screen, someone tests it. Authorization is invisible, so it is the one that gets skipped.\n\nHere is what that looks like from the attacker's side, and it requires no tools at all. A customer logs into a real account, opens an invoice, and sees the address bar read /orders/10428. They change the number to 10427 and press Enter. If the handler only checked that a valid session exists — and not that this order belongs to this user — the server happily returns someone else's name, address, items and total. From there it is a loop: a short script walking from 10000 to 11000 with their own valid cookie pulls a thousand customer records in under a minute, and every request looks completely legitimate in the access log, because it is. This is called IDOR, and it is found constantly in real products.\n\nThe defence is a rule, not a patch: every handler that receives an identifier from the outside must re-derive what the current user is allowed to see, in the handler, on the server. Fetch the row, compare its owner to the session user, return 403 otherwise. Hiding the admin button in the UI is not authorization; the endpoint behind it is still there. When an AI writes CRUD endpoints for you it will reliably add the login check and reliably omit the ownership check, so that is the exact line to look for in every route that takes an id.",
  "he": "אותנטיקציה עונה על ״מי זה?״ — סיסמה, קוד חד-פעמי, התחברות עם גוגל. הרשאה עונה על ״האם לאדם הזה מותר לעשות את הפעולה הזאת על האובייקט הזה?״. אלה שתי בדיקות נפרדות, הן נכשלות ברגעים נפרדים, והבלבול ביניהן הוא חור האבטחה הנפוץ ביותר באפליקציות שנבנות מהר. אותנטיקציה נוטה להיבנות בזהירות כי היא נראית לעין: יש מסך התחברות, מישהו בודק אותו. הרשאות הן בלתי נראות, ולכן דווקא הן אלה שמדלגים עליהן.\n\nככה זה נראה מהצד של התוקף, ולא צריך שום כלי. לקוח מתחבר לחשבון אמיתי, פותח חשבונית, ורואה בשורת הכתובת /orders/10428. הוא משנה את המספר ל-10427 ולוחץ Enter. אם המטפל רק בדק שקיים סשן תקף — ולא שההזמנה הזאת שייכת למשתמש הזה — השרת מחזיר בשמחה שם, כתובת, פריטים וסכום של מישהו אחר. משם זאת לולאה: סקריפט קצר שרץ מ-10000 עד 11000 עם הקוקי התקף שלו עצמו שולף אלף רשומות לקוח בפחות מדקה, וכל בקשה נראית לגמרי לגיטימית ביומן הגישה, כי היא באמת כזאת. לזה קוראים IDOR, וזה נמצא כל הזמן במוצרים אמיתיים.\n\nההגנה היא כלל, לא טלאי: כל מטפל שמקבל מזהה מבחוץ חייב לגזור מחדש מה מותר למשתמש הנוכחי לראות, בתוך המטפל, בצד השרת. לשלוף את השורה, להשוות את הבעלים למשתמש שבסשן, ולהחזיר 403 אחרת. להסתיר את כפתור האדמין בממשק זאת לא הרשאה; נקודת הקצה שמאחוריו עדיין שם. כש-AI כותב לך נקודות קצה של CRUD הוא יוסיף בעקביות את בדיקת ההתחברות ויוותר בעקביות על בדיקת הבעלות, אז זאת בדיוק השורה שצריך לחפש בכל נתיב שמקבל מזהה."},

 "Session & cookie": {
  "en": "A session is a row the server keeps saying \"this identifier belongs to user 88, created at this time\". The cookie is just a small piece of text the browser stores and attaches automatically to every subsequent request to that domain. The identity itself never leaves the server; the browser only carries a pointer. That design is why you can log someone out instantly — delete the row — and it is also why the word \"automatically\" in the previous sentence is the source of an entire class of attacks.\n\nThe attack is CSRF, and it is worth picturing concretely. You are logged into your bank in one tab. In another tab you open a page that looks like a meme gallery. That page contains a hidden form pointed at your bank's transfer endpoint with the amount and destination pre-filled, and a line of script that submits it the moment the page loads. Your browser sends that POST, and because the request goes to the bank's domain, it helpfully attaches your session cookie. The bank sees a fully authenticated request from a logged-in user. Nothing was stolen; the attacker never saw your cookie. They just borrowed the fact that it gets sent on its own. SameSite=Lax on the cookie stops the ordinary version of this, which is why it is now the browser default.\n\nThe flags are the whole defence and there are only a few: HttpOnly so page scripts cannot read the cookie and an XSS bug cannot steal the session, Secure so it never travels over plain HTTP, SameSite to control cross-site sending, and a sensible Max-Age. Beyond that, two habits: logging out must delete the server-side session, not just the cookie, and logging in must issue a brand-new session id rather than reusing whatever the visitor arrived with.",
  "he": "סשן הוא שורה שהשרת מחזיק שאומרת ״המזהה הזה שייך למשתמש 88, נוצר בזמן הזה״. הקוקי הוא רק פיסת טקסט קטנה שהדפדפן שומר ומצרף אוטומטית לכל בקשה הבאה לאותו דומיין. הזהות עצמה אף פעם לא יוצאת מהשרת; הדפדפן נושא רק מצביע. התכנון הזה הוא הסיבה שאפשר לנתק מישהו מיידית — למחוק את השורה — והוא גם הסיבה שהמילה ״אוטומטית״ במשפט הקודם היא המקור למשפחה שלמה של התקפות.\n\nההתקפה היא CSRF, ושווה לדמיין אותה בקונקרטי. אתה מחובר לבנק בלשונית אחת. בלשונית אחרת אתה פותח דף שנראה כמו גלריית ממים. הדף הזה מכיל טופס נסתר שמכוון לנקודת הקצה של ההעברות בבנק, עם הסכום והיעד כבר ממולאים, ושורת סקריפט ששולחת אותו ברגע שהדף נטען. הדפדפן שלך שולח את ה-POST הזה, ובגלל שהבקשה הולכת לדומיין של הבנק, הוא מצרף בשמחה את קוקי הסשן שלך. הבנק רואה בקשה מאומתת לגמרי ממשתמש מחובר. שום דבר לא נגנב; התוקף מעולם לא ראה את הקוקי שלך. הוא רק שאל את העובדה שהוא נשלח מעצמו. SameSite=Lax על הקוקי עוצר את הגרסה הרגילה של זה, ובגלל זה זאת כבר ברירת המחדל בדפדפנים.\n\nהדגלים הם כל ההגנה ויש רק כמה: HttpOnly כדי שסקריפטים בדף לא יוכלו לקרוא את הקוקי ובאג XSS לא יוכל לגנוב את הסשן, Secure כדי שהוא לעולם לא יעבור ב-HTTP רגיל, SameSite כדי לשלוט בשליחה חוצת-אתרים, ו-Max-Age הגיוני. מעבר לזה, שני הרגלים: התנתקות חייבת למחוק את הסשן בצד השרת, לא רק את הקוקי, והתחברות חייבת להנפיק מזהה סשן חדש לגמרי במקום להשתמש במה שהמבקר הגיע איתו."},

 "Token / JWT": {
  "en": "A JWT is three base64 segments joined by dots: a header saying how it was signed, a payload carrying claims like user id, role and expiry, and a signature the server computes with its secret. The appeal is that no lookup is needed — any server holding the secret can verify the signature and trust the claims, which is why tokens are the default for APIs and mobile clients where there is no cookie jar to lean on. The price is that a valid signature is the only thing being checked, so everything hinges on checking it properly and on the fact that you cannot un-issue what you already handed out.\n\nTwo real failures. The first is decoding instead of verifying: a library exposes both a decode function and a verify function, an AI-written middleware calls decode, and now an attacker can take their own token, base64-decode the payload, change \"role\":\"user\" to \"role\":\"admin\", re-encode it, leave the signature untouched and get full admin. Nothing validates the signature, so nothing complains. The second is revocation. An employee is fired at 10:00 and their access is removed from the database at 10:01 — but their token has a seven-day expiry and keeps working for the rest of the week, because no server ever asks the database anything.\n\nSo: keep access tokens short-lived — minutes, not days — and use a refresh token that is checked against the database, which restores your ability to cut someone off. Keep a deny list for the tokens you need to kill early. Never put anything sensitive in the payload; it is signed, not encrypted, and anyone holding the token can read it with one command. And if you are building a plain web app with a browser and a server you control, a session cookie is simpler, revocable, and usually the better choice — JWT is not an upgrade, it is a trade.",
  "he": "JWT הוא שלושה מקטעי base64 מחוברים בנקודות: כותרת שאומרת איך הוא נחתם, מטען שנושא טענות כמו מזהה משתמש, תפקיד ותוקף, וחתימה שהשרת מחשב עם הסוד שלו. הקסם הוא שלא נדרשת שום בדיקה במסד — כל שרת שמחזיק את הסוד יכול לאמת את החתימה ולסמוך על הטענות, ובגלל זה טוקנים הם ברירת המחדל ל-APIs וללקוחות מובייל שאין להם צנצנת קוקיז להישען עליה. המחיר הוא שחתימה תקפה היא הדבר היחיד שנבדק, אז הכל תלוי בכך שבודקים אותה כמו שצריך, ובעובדה שאי אפשר לבטל משהו שכבר חילקת.\n\nשני כשלים אמיתיים. הראשון הוא פענוח במקום אימות: ספרייה חושפת גם פונקציית decode וגם פונקציית verify, מידלוור שנכתב על ידי AI קורא ל-decode, ועכשיו תוקף יכול לקחת את הטוקן שלו עצמו, לפענח את המטען מ-base64, לשנות \"role\":\"user\" ל-\"role\":\"admin\", לקודד מחדש, להשאיר את החתימה כמו שהיא ולקבל הרשאות אדמין מלאות. שום דבר לא מאמת את החתימה, אז שום דבר לא מתלונן. השני הוא ביטול. עובד מפוטר ב-10:00 והגישה שלו נמחקת מהמסד ב-10:01 — אבל לטוקן שלו יש תוקף של שבעה ימים והוא ממשיך לעבוד כל השבוע, כי אף שרת לא שואל את המסד כלום.\n\nלכן: תחזיק טוקני גישה קצרי-חיים — דקות, לא ימים — ותשתמש ב-refresh token שכן נבדק מול המסד, מה שמחזיר לך את היכולת לנתק מישהו. תחזיק רשימת חסימה לטוקנים שצריך להרוג מוקדם. אף פעם אל תשים שום דבר רגיש במטען; הוא חתום, לא מוצפן, וכל מי שמחזיק את הטוקן קורא אותו בפקודה אחת. ואם אתה בונה אפליקציית ווב רגילה עם דפדפן ושרת שבשליטתך, קוקי סשן פשוט יותר, ניתן לביטול, ובדרך כלל הבחירה הטובה יותר — JWT הוא לא שדרוג, הוא עסקה."},

 "OAuth": {
  "en": "OAuth is a delegation protocol: it lets a user tell a provider like Google \"give this app permission to do these specific things with my account\" without that app ever seeing the password. The browser is redirected to the provider, the user sees a consent screen listing the requested scopes, and on approval the provider redirects back to your app with a short-lived code. Your server then exchanges that code, behind the scenes with its client secret, for an access token. The reason \"Sign in with Google\" is built on it is that identity is just the smallest possible version of the same delegation.\n\nThe flow has more moving parts than it looks, and the part that eats a day is almost always the redirect URI. It must match what you registered at the provider byte for byte — http versus https, a trailing slash, localhost:3000 versus 127.0.0.1:3000 are all different values — and when it does not, the provider refuses before your code ever runs, with an error page that mentions no detail. The second common trap is account linking: a user signs up with an email and password in March, comes back in June and clicks Sign in with Google with the same address. If you create a second account you have split their data in two; if you merge automatically without checking the provider marked the email verified, anyone who can register that address at a sloppy provider can walk into the existing account.\n\nPractical guidance: do not hand-roll this. Use the provider's library or an auth service; the protocol has real subtleties like PKCE and state parameters that exist to stop specific attacks, and an AI reproducing a blog post from 2016 will skip them. Keep the client secret on the server only, register one redirect URI per environment, and request the narrowest scopes you actually need — asking for full Drive access when you wanted an email address is how a consent screen scares users away.",
  "he": "OAuth הוא פרוטוקול האצלה: הוא מאפשר למשתמש להגיד לספק כמו גוגל ״תן לאפליקציה הזאת הרשאה לעשות את הדברים המסוימים האלה בחשבון שלי״ בלי שהאפליקציה הזאת תראה אי פעם את הסיסמה. הדפדפן מופנה לספק, המשתמש רואה מסך הסכמה שמפרט את ההרשאות המבוקשות, ועם האישור הספק מפנה חזרה לאפליקציה שלך עם קוד קצר-מועד. השרת שלך מחליף את הקוד הזה, מאחורי הקלעים עם ה-client secret שלו, בטוקן גישה. הסיבה ש״התחבר עם גוגל״ בנוי על זה היא שזהות היא פשוט הגרסה הקטנה ביותר של אותה האצלה.\n\nלתהליך יש יותר חלקים נעים ממה שנראה, והחלק שאוכל יום שלם הוא כמעט תמיד כתובת ההפניה. היא חייבת להתאים למה שרשמת אצל הספק בייט-בייט — http מול https, לוכסן בסוף, localhost:3000 מול 127.0.0.1:3000 הם ערכים שונים — וכשהיא לא מתאימה, הספק מסרב עוד לפני שהקוד שלך רץ, עם דף שגיאה בלי שום פרט. המלכודת הנפוצה השנייה היא קישור חשבונות: משתמש נרשם עם אימייל וסיסמה במרץ, חוזר ביוני ולוחץ ״התחבר עם גוגל״ עם אותה כתובת. אם תיצור חשבון שני, פיצלת את הנתונים שלו לשניים; אם תמזג אוטומטית בלי לבדוק שהספק סימן את האימייל כמאומת, כל מי שיכול לרשום את הכתובת הזאת אצל ספק רשלני נכנס לחשבון הקיים.\n\nהנחיה מעשית: אל תממש את זה בעצמך. תשתמש בספרייה של הספק או בשירות אותנטיקציה; לפרוטוקול יש דקויות אמיתיות כמו PKCE ופרמטר state שקיימות כדי לעצור התקפות מסוימות, ו-AI שמשחזר פוסט מ-2016 ידלג עליהן. תחזיק את ה-client secret רק בשרת, תרשום כתובת הפניה אחת לכל סביבה, ותבקש את ההרשאות הצרות ביותר שאתה באמת צריך — לבקש גישה מלאה ל-Drive כשרצית כתובת אימייל זאת הדרך להבריח משתמשים במסך ההסכמה."},

 "Hashing vs encryption": {
  "en": "Encryption is a two-way door. With the key you turn plaintext into ciphertext and back, which is what you want for data you must be able to read again: a stored API token, a customer's national id, a message in transit. Hashing is a one-way street. You turn input into a fixed-length fingerprint and there is no operation that goes back, which is exactly why it is the right tool for passwords — you never need the original, you only need to check whether what someone just typed produces the same fingerprint.\n\nWhy this distinction has teeth: a database of 120,000 users leaks. If the passwords were hashed with MD5 or SHA-256 — fast, general-purpose hashes with no salt — a single consumer GPU tries tens of billions of candidates per second, and because the hashes are unsalted, identical passwords produce identical values, so the attacker sorts by frequency and cracks the most common ones first. In practice a large fraction of that file is readable within hours, and since people reuse passwords, the damage is not limited to your product. Hashed with argon2 or bcrypt, tuned so a single check takes around a tenth of a second, the same GPU manages a few thousand guesses per second instead of billions, and a random salt per user means every password has to be attacked separately.\n\nThe rules that follow are short. Passwords are hashed, with a slow algorithm, never encrypted — if a service can email you your existing password, it is storing it reversibly and you should leave. Data you need to read back is encrypted, with the key kept outside the database it protects. And never write either one yourself: use argon2id or bcrypt through a maintained library, and if an AI suggests salting a SHA-256 yourself or inventing a scheme, that is the moment to stop and reach for the standard tool.",
  "he": "הצפנה היא דלת דו-כיוונית. עם המפתח אתה הופך טקסט גלוי לטקסט מוצפן ובחזרה, וזה מה שאתה רוצה לנתונים שאתה חייב לקרוא שוב: טוקן API שמור, תעודת זהות של לקוח, הודעה בתעבורה. האשינג הוא רחוב חד-סטרי. אתה הופך קלט לטביעת אצבע באורך קבוע ואין שום פעולה שחוזרת אחורה, וזאת בדיוק הסיבה שזה הכלי הנכון לסיסמאות — אתה אף פעם לא צריך את המקור, אתה רק צריך לבדוק אם מה שמישהו הקליד עכשיו מייצר את אותה טביעת אצבע.\n\nלמה להבחנה הזאת יש שיניים: מסד של 120,000 משתמשים דולף. אם הסיסמאות עברו האשינג עם MD5 או SHA-256 — האשים מהירים לשימוש כללי, בלי מלח — כרטיס מסך צרכני בודד מנסה עשרות מיליארדי מועמדים בשנייה, ובגלל שאין מלח, סיסמאות זהות מייצרות ערכים זהים, אז התוקף ממיין לפי שכיחות ושובר קודם את הנפוצות. בפועל חלק גדול מהקובץ הזה קריא תוך שעות, ובגלל שאנשים משתמשים באותה סיסמה בכמה מקומות, הנזק לא נעצר במוצר שלך. עם argon2 או bcrypt, מכוונן כך שבדיקה אחת לוקחת בערך עשירית שנייה, אותו כרטיס מסך מגיע לכמה אלפי ניחושים בשנייה במקום מיליארדים, ומלח אקראי לכל משתמש אומר שצריך לתקוף כל סיסמה בנפרד.\n\nהכללים שנגזרים מזה קצרים. סיסמאות עוברות האשינג, באלגוריתם איטי, אף פעם לא הצפנה — אם שירות יכול לשלוח לך במייל את הסיסמה הקיימת שלך, הוא שומר אותה באופן הפיך וכדאי לעזוב. נתונים שאתה צריך לקרוא בחזרה מוצפנים, כשהמפתח נשמר מחוץ למסד שהוא מגן עליו. ואף פעם אל תכתוב אף אחד מהשניים בעצמך: תשתמש ב-argon2id או bcrypt דרך ספרייה מתוחזקת, ואם AI מציע לך למלוח SHA-256 לבד או להמציא שיטה, זה הרגע לעצור ולהושיט יד לכלי הסטנדרטי."},

 "HTTPS / TLS": {
  "en": "TLS does two jobs, and people usually remember only the first. It encrypts the connection, so nobody sitting between the browser and the server can read or alter what passes. It also authenticates the server: the certificate, signed by an authority the browser already trusts, is what makes you confident the thing answering for your-bank.com really is your-bank.com. Encryption without that second half would be useless, because you would have a perfectly private conversation with an attacker.\n\nWhat plain HTTP costs is easy to picture. On café wifi, anyone on the same network can put a laptop in promiscuous mode and read every unencrypted request going past: the login form post with the password in the body, the session cookie attached to the next request, the API key in a header. They do not need to break anything; the text is simply there. Worse, they can modify responses in flight — injecting a script, rewriting a bank account number in a form. The second, more mundane outage is the other side of the same system: a certificate quietly expires on a Sunday, and every browser and every API client refuses to connect at all, with an alarming red page for customers.\n\nSo: certificates are free from Let's Encrypt and every serious host automates renewal — make sure something is renewing yours and alerting before day 80, not day 90. Redirect all HTTP to HTTPS and send HSTS so browsers refuse plain HTTP for your domain up front. And one AI-specific trap worth naming: when an HTTP client throws a certificate error, the suggestion that always appears is to disable certificate verification — rejectUnauthorized: false, verify=False. That line makes the error disappear by turning off the identity check entirely, and it has a way of surviving into production.",
  "he": "TLS עושה שתי עבודות, ואנשים בדרך כלל זוכרים רק את הראשונה. הוא מצפין את החיבור, כך שאף אחד שיושב בין הדפדפן לשרת לא יכול לקרוא או לשנות את מה שעובר. הוא גם מאמת את השרת: התעודה, חתומה על ידי רשות שהדפדפן כבר סומך עליה, היא מה שנותן לך ביטחון שמה שעונה בשם your-bank.com הוא באמת your-bank.com. הצפנה בלי החצי השני הייתה חסרת ערך, כי הייתה לך שיחה פרטית לחלוטין עם תוקף.\n\nקל לדמיין מה עולה HTTP רגיל. בוויי-פיי של בית קפה, כל מי שנמצא באותה רשת יכול לשים לפטופ במצב האזנה ולקרוא כל בקשה לא מוצפנת שעוברת: שליחת טופס ההתחברות עם הסיסמה בגוף, קוקי הסשן שמצורף לבקשה הבאה, מפתח ה-API בכותרת. הם לא צריכים לשבור כלום; הטקסט פשוט שם. גרוע מזה, הם יכולים לשנות תשובות תוך כדי תעופה — להזריק סקריפט, לשכתב מספר חשבון בנק בטופס. הנפילה השנייה, היומיומית יותר, היא הצד השני של אותה מערכת: תעודה פגה בשקט ביום ראשון, וכל דפדפן וכל לקוח API מסרבים להתחבר בכלל, עם דף אדום מבהיל ללקוחות.\n\nלכן: תעודות הן חינם מ-Let's Encrypt וכל אחסון רציני מבצע חידוש אוטומטי — תוודא שמשהו באמת מחדש את שלך ומתריע ביום ה-80, לא ביום ה-90. תפנה כל HTTP ל-HTTPS ותשלח HSTS כדי שדפדפנים יסרבו ל-HTTP רגיל בדומיין שלך מראש. ומלכודת אחת ששווה לתת לה שם בעידן ה-AI: כשלקוח HTTP זורק שגיאת תעודה, ההצעה שתמיד מופיעה היא לכבות את אימות התעודה — rejectUnauthorized: false, verify=False. השורה הזאת מעלימה את השגיאה על ידי כיבוי מוחלט של בדיקת הזהות, ויש לה נטייה לשרוד עד לפרודקשן."},

 "Environment variables / secrets": {
  "en": "A secret is any value that grants power: a database URL, a Stripe key, a signing key, a third-party token. The rule is that those values are supplied to the program when it starts, from the environment it runs in, rather than written into the code. The practical payoff is that the same build runs against your laptop's database, the staging database and production without a single line changing, and the thing that decides which one is a configuration living outside the repository — where it can be rotated, restricted and audited.\n\nThe cost of getting this wrong is measured in hours. Bots continuously scan every public push to GitHub for key patterns; a committed AWS key is typically found and used within minutes, and the standard outcome is a fleet of expensive GPU instances mining cryptocurrency in a region you have never deployed to, with a bill in the thousands by morning. The part people miss is that deleting the line and pushing again fixes nothing — the old commit is still in the history, and anyone who cloned or forked the repository has it. There is exactly one correct response: rotate the key so the leaked value stops working, then clean up.\n\nThe habits are cheap. Put .env in .gitignore before the first commit, keep a .env.example with placeholder values so the next person knows what is needed, and run a scanner like gitleaks before pushing. In production, prefer a secret manager over a file on disk. And there is one modern trap worth knowing: in frontend frameworks, variables with a public prefix — NEXT_PUBLIC_, VITE_ — are compiled into the JavaScript that ships to every visitor. Putting a real API key behind that prefix does not make it available, it makes it published, and an AI moving a variable to fix an \"undefined in the browser\" error will do this without comment.",
  "he": "סוד הוא כל ערך שמעניק כוח: כתובת מסד נתונים, מפתח Stripe, מפתח חתימה, טוקן של צד שלישי. הכלל הוא שהערכים האלה מסופקים לתוכנית כשהיא עולה, מהסביבה שבה היא רצה, במקום להיכתב בתוך הקוד. התועלת המעשית היא שאותה בנייה בדיוק רצה מול המסד של הלפטופ שלך, מול סטייג׳ינג ומול פרודקשן בלי שורה אחת שמשתנה, ומה שמחליט על איזה מהם מדובר הוא קונפיגורציה שחיה מחוץ לריפו — איפה שאפשר להחליף אותה, להגביל ולתעד.\n\nהמחיר של טעות כאן נמדד בשעות. בוטים סורקים כל הזמן כל דחיפה ציבורית ל-GitHub בחיפוש אחר תבניות של מפתחות; מפתח AWS שנדחף נמצא ומנוצל בדרך כלל תוך דקות, והתוצאה הסטנדרטית היא צי מכונות GPU יקרות שכורות מטבעות קריפטו באזור שמעולם לא פרסת אליו, עם חשבון של אלפי דולרים עד הבוקר. מה שאנשים מפספסים זה שמחיקת השורה ודחיפה מחדש לא מתקנת כלום — הקומיט הישן עדיין בהיסטוריה, וכל מי ששכפל או פיצל את הריפו מחזיק אותו. יש בדיוק תגובה נכונה אחת: להחליף את המפתח כדי שהערך שדלף יפסיק לעבוד, ורק אז לנקות.\n\nההרגלים זולים. תשים .env ב-.gitignore לפני הקומיט הראשון, תחזיק .env.example עם ערכי דמה כדי שהבא אחריך ידע מה נדרש, ותריץ סורק כמו gitleaks לפני דחיפה. בפרודקשן, תעדיף מנהל סודות על פני קובץ בדיסק. ויש מלכודת מודרנית אחת ששווה להכיר: בפריימוורקים של פרונט, משתנים עם קידומת ציבורית — NEXT_PUBLIC_, VITE_ — נבנים לתוך ה-JavaScript שנשלח לכל מבקר. לשים מפתח API אמיתי מאחורי הקידומת הזאת לא הופך אותו לזמין, הוא הופך אותו למפורסם, ו-AI שמזיז משתנה כדי לתקן שגיאת ״undefined בדפדפן״ יעשה את זה בלי להעיר מילה."},

 "CORS": {
  "en": "The same-origin policy is a browser rule: JavaScript running on one origin may not read the response from a different origin. It exists so that a random page you open cannot quietly call your bank's API with your cookies attached and read the answer. CORS is the controlled exception — a set of response headers with which a server says which origins are allowed to read its responses, with which methods and which headers. The crucial detail is who enforces it. The browser does. Your server is not blocking anything.\n\nThat is why a CORS error is so disorienting the first time. The console says the request was blocked by CORS policy, but your server log shows a clean 200 — because in most cases the request really was sent and really was handled; the browser simply refused to hand the response back to your script. The same call from curl or Postman works perfectly, which sends people looking for a bug in their frontend that does not exist. A second variant catches people too: for anything beyond a simple GET, the browser first sends an OPTIONS preflight, and if your router only registered POST for that path, the preflight gets a 404 and the real request is never attempted at all.\n\nSo fix it in exactly one place: the API server's response headers. Name the allowed origin explicitly rather than using a wildcard, especially if cookies are involved — a wildcard with credentials is rejected by the browser outright. Make sure OPTIONS is handled for every path that needs it. And resist the two shortcuts that appear whenever someone is frustrated: a browser extension that disables CORS, which fixes only your machine and hides the problem from you, and Allow-Origin set to * on an authenticated API, which hands every website on the internet permission to read your users' data.",
  "he": "מדיניות אותו-מקור היא חוק של הדפדפן: ל-JavaScript שרץ במקור אחד אסור לקרוא את התשובה ממקור אחר. היא קיימת כדי שדף אקראי שאתה פותח לא יוכל לקרוא בשקט ל-API של הבנק שלך עם הקוקיז שלך מצורפים ולקרוא את התשובה. CORS הוא החריג המבוקר — אוסף כותרות תשובה שבהן שרת אומר אילו מקורות מורשים לקרוא את התשובות שלו, באילו מתודות ועם אילו כותרות. הפרט הקריטי הוא מי אוכף את זה. הדפדפן. השרת שלך לא חוסם כלום.\n\nבגלל זה שגיאת CORS כל כך מבלבלת בפעם הראשונה. הקונסול אומר שהבקשה נחסמה על ידי מדיניות CORS, אבל היומן של השרת שלך מראה 200 נקי — כי ברוב המקרים הבקשה באמת נשלחה ובאמת טופלה; הדפדפן פשוט סירב להחזיר את התשובה לסקריפט שלך. אותה קריאה מ-curl או Postman עובדת מצוין, מה ששולח אנשים לחפש באג בפרונט שלהם שלא קיים. וריאציה שנייה תופסת גם היא: לכל דבר שהוא לא GET פשוט, הדפדפן שולח קודם preflight של OPTIONS, ואם הראוטר שלך רשם רק POST לנתיב הזה, ה-preflight מקבל 404 והבקשה האמיתית בכלל לא מנוסה.\n\nאז תתקן את זה בדיוק במקום אחד: כותרות התשובה של שרת ה-API. תציין את המקור המורשה במפורש במקום תו כללי, במיוחד אם מעורבים קוקיז — תו כללי יחד עם credentials נדחה על ידי הדפדפן מיידית. תוודא ש-OPTIONS מטופל בכל נתיב שצריך אותו. ותתנגד לשני הקיצורים שצצים כשמישהו מתוסכל: תוסף לדפדפן שמכבה CORS, שמתקן רק את המכונה שלך ומסתיר ממך את הבעיה, ו-Allow-Origin שמוגדר ל-* על API מאומת, שנותן לכל אתר באינטרנט רשות לקרוא את הנתונים של המשתמשים שלך."},

 "Injection & validation": {
  "en": "Injection is what happens when data the user supplied gets treated as instructions. The mechanism is always the same shape: you build a command — SQL, a shell line, an HTML fragment, an LDAP filter — by gluing strings together, and somewhere inside that string sits text a stranger wrote. The engine on the other end has no way to tell which characters came from you and which came from them, so it executes all of it. The fix is also always the same shape: send the command and the data on separate channels, so the data can never be parsed as syntax.\n\nPut yourself at the keyboard of the attacker. A support page looks up an order by email, and the query is assembled with the email pasted into the middle of it. Into that field they type ' OR '1'='1' -- and the WHERE clause becomes trivially true, so the page returns every order in the table. Once that works they escalate: ' UNION SELECT email, password_hash FROM users -- reuses your own endpoint to print the user table into your nicely formatted results list. No tooling, no exploit kit, just characters in a text box. The same idea with a filename becomes a deleted directory; with a comment body it becomes a script running in every reader's browser.\n\nTwo defences, and they are not interchangeable. Parameterized queries — placeholders with the values passed alongside — make injection structurally impossible in the database, and there is no case where string concatenation is the right choice. Validation is the second layer: check at the edge, with a schema, that qty is a positive integer under 100 and email looks like an email, and reject with a 400 before any logic sees it. Client-side checks are user experience; anyone can skip your form and post directly. And this is the review AI code needs most, because when you ask for dynamic filters or sorting, a template string is exactly what it will reach for.",
  "he": "הזרקה היא מה שקורה כשנתון שהמשתמש סיפק מטופל כהוראה. המנגנון תמיד באותה צורה: אתה בונה פקודה — SQL, שורת שֶׁל, קטע HTML, מסנן LDAP — על ידי הדבקת מחרוזות זו לזו, ואיפשהו בתוך המחרוזת הזאת יושב טקסט שזר כתב. למנוע בצד השני אין דרך להבחין אילו תווים הגיעו ממך ואילו מהם, אז הוא מריץ את הכל. התיקון גם הוא תמיד באותה צורה: לשלוח את הפקודה ואת הנתון בערוצים נפרדים, כך שהנתון לעולם לא ייקרא כתחביר.\n\nתשים את עצמך במקלדת של התוקף. דף תמיכה מחפש הזמנה לפי אימייל, והשאילתה מורכבת כשהאימייל מודבק לתוכה. בשדה הזה הוא מקליד ' OR '1'='1' -- וסעיף ה-WHERE הופך לנכון תמיד, אז הדף מחזיר את כל ההזמנות בטבלה. ברגע שזה עובד הוא מסלים: ' UNION SELECT email, password_hash FROM users -- מנצל את נקודת הקצה שלך עצמה כדי להדפיס את טבלת המשתמשים לתוך רשימת התוצאות המעוצבת יפה שלך. בלי כלים, בלי ערכת פריצה, רק תווים בתיבת טקסט. אותו רעיון עם שם קובץ הופך לתיקייה שנמחקה; עם גוף תגובה הוא הופך לסקריפט שרץ בדפדפן של כל קורא.\n\nשתי הגנות, והן לא מחליפות זו את זו. שאילתות עם פרמטרים — מצייני מקום כשהערכים מועברים בנפרד — הופכות הזרקה לבלתי אפשרית מבנית במסד, ואין מקרה שבו שרשור מחרוזות הוא הבחירה הנכונה. אימות הוא השכבה השנייה: לבדוק בקצה, עם סכמה, ש-qty הוא מספר שלם חיובי מתחת ל-100 ושהאימייל נראה כמו אימייל, ולדחות עם 400 לפני שהלוגיקה בכלל רואה את זה. בדיקות בצד הלקוח הן חוויית משתמש; כל אחד יכול לדלג על הטופס שלך ולשלוח ישירות. וזאת הביקורת שקוד של AI הכי זקוק לה, כי כשאתה מבקש סינון או מיון דינמי, מחרוזת תבנית היא בדיוק מה שהוא יושיט אליה יד."},
}

EXAMPLES_FIX = {

 "Invalidation": {"cap": {"en": "Version the key instead of hunting for copies",
                          "he": "לגרס את המפתח במקום לרדוף אחרי עותקים"},
  "code": "# the fragile way: you must remember every derived key\nDEL user:88\nDEL profile:html:88        # forgot this one? stale for its whole TTL\nDEL team:roster:4\n\n# the boring way: updated_at is part of the key\n# old entries become unreachable the instant the row changes\nGET user:88:v1737049201     # -> the new copy\n# user:88:v1737045600 is still in memory, nobody can ask for it,\n# and it dies on its own TTL. nothing to delete, nothing to forget.\n\n# CDN copies need their own purge - a DEL in Redis does not reach them:\ncurl -X POST https://api.cdn.example/purge -d '{\"paths\":[\"/u/88\"]}'"},

 "OAuth": {"cap": {"en": "The exchange, and the error that eats a day",
                   "he": "ההחלפה, והשגיאה שאוכלת יום שלם"},
  "code": "# 1. you send the user here (state = CSRF protection, keep it)\nGET https://accounts.google.com/o/oauth2/v2/auth\n  ?client_id=8123-abc.apps.googleusercontent.com\n  &redirect_uri=https://app.example.com/auth/callback\n  &response_type=code&scope=openid%20email&state=x7f2\n\n# 2. they approve -> google sends them back with a short-lived code\nGET /auth/callback?code=4/0Ab_5s...&state=x7f2\n\n# 3. YOUR SERVER swaps it for a token. the secret never leaves here.\ncurl -X POST https://oauth2.googleapis.com/token \\\n  -d code=4/0Ab_5s... -d client_id=8123-abc.apps.googleusercontent.com \\\n  -d client_secret=$GOOGLE_CLIENT_SECRET \\\n  -d redirect_uri=https://app.example.com/auth/callback \\\n  -d grant_type=authorization_code\n\n# redirect_uri must match the registered one EXACTLY, or:\n#   Error 400: redirect_uri_mismatch\n# http != https, trailing slash counts, localhost != 127.0.0.1"},

 "HTTPS / TLS": {"cap": {"en": "Check the cert, force HTTPS, never disable verification",
                         "he": "לבדוק תעודה, לכפות HTTPS, אף פעם לא לכבות אימות"},
  "code": "# when does it expire? (set an alert well before this date)\n$ echo | openssl s_client -connect example.com:443 2>/dev/null \\\n    | openssl x509 -noout -dates -issuer\nnotAfter=Dec  9 11:02:31 2026 GMT\nissuer=C=US, O=Let's Encrypt, CN=R11\n\n# tell browsers to never use plain http for this domain again\nStrict-Transport-Security: max-age=31536000; includeSubDomains\n\n# and the line to refuse in review - it turns identity checking OFF:\nnew https.Agent({ rejectUnauthorized: false })   // NO\nrequests.get(url, verify=False)                  # NO\n# a cert error means the chain is wrong or the clock is wrong. fix that."},
}

HE_FIX = {

 "Hit / Miss": {
  "t": {"he": "פגיעה / פספוס (Hit / Miss)"},
  "d": {"he": "פגיעה = העותק היה שם. פספוס = שילמת את המחיר המלא ושמרת את התוצאה."},
  "w": {"he": "אחוז הפגיעות (hit rate) הוא המספר שחשוב. קאש עם 20% פגיעות הוא בעיקר תקורה."}},

 "Authentication vs Authorization": {
  "t": {"he": "אותנטיקציה מול הרשאות"},
  "d": {"he": "אותנטיקציה מוכיחה מי אתה. הרשאות קובעות מה מותר לזהות הזאת לעשות."},
  "w": {"he": "401 = לא מכירים אותך. 403 = מכירים אותך והתשובה עדיין לא."}},

 "Session & cookie": {
  "t": {"he": "סשן וקוקי"},
  "d": {"he": "השרת זוכר סשן מחובר ונותן לדפדפן קוקי שמצביע אליו."},
  "w": {"he": "קוקיז נשלחים אוטומטית בכל בקשה — נוח, ובדיוק בגלל זה קיים CSRF."}},

 "Hashing vs encryption": {
  "t": {"he": "האשינג מול הצפנה"},
  "d": {"he": "האשינג הוא חד-כיווני ולא הפיך. הצפנה היא דו-כיוונית עם מפתח."},
  "w": {"he": "סיסמאות עוברות האשינג (bcrypt/argon2), אף פעם לא הצפנה. אם אתר יכול לשלוח לך את הסיסמה במייל — תברח."}},

 "Browser cache": {
  "t": {"he": "קאש הדפדפן"},
  "d": {"he": "הדפדפן שומר קבצים שכבר הוריד — JS, CSS, תמונות — ומשתמש בהם מחדש."},
  "w": {"he": "לפני שעה של דיבוג: רענון קשיח (hard refresh). Ctrl+Shift+R. זה זה, יותר פעמים ממה שהיית רוצה."}},

 "Cache": {
  "t": {"he": "קאש / מטמון (Cache)"}},
}
