# -*- coding: utf-8 -*-
"""Deep-dive text for every term, keyed by the English term name.
Abstract on purpose: mental model + the trade-off, not code."""

DETAIL = {
# ---------------- ground floor ----------------
"Source code": {
 "en": "Code is not a machine. It is a description of one, written down in a language strict enough that a machine can follow it without guessing. That strictness is the whole difficulty: a human reader forgives a missing comma, a computer does not.\n\nThis is why programming feels unforgiving compared to writing. You are not explaining an idea to someone who will fill in your gaps — you are specifying it completely, including every case you would rather not think about.",
 "he": "קוד הוא לא מכונה. הוא תיאור של מכונה, כתוב בשפה מחמירה מספיק כדי שמכונה תוכל לבצע אותו בלי לנחש. הדיוק הזה הוא כל הקושי: קורא אנושי יסלח על פסיק חסר, מחשב לא.\n\nבגלל זה תכנות מרגיש בלתי סלחני לעומת כתיבה. אתה לא מסביר רעיון למישהו שישלים את החורים — אתה מגדיר אותו במלואו, כולל כל מקרה שהיית מעדיף לא לחשוב עליו."},
"Compiler / Interpreter": {
 "en": "Both do the same job — turn your description into something a processor executes. They differ only in when. Compiling pays the cost once, up front, and buys speed and early error detection. Interpreting pays a little on every run, and buys the ability to change something and see it immediately.\n\nModern languages blur this. JavaScript is interpreted but compiles hot paths while running. The useful question is never which one, but when do my mistakes get caught — before shipping, or in front of a user.",
 "he": "שניהם עושים את אותה עבודה — הופכים את התיאור שלך למשהו שמעבד מבצע. ההבדל הוא רק מתי. הידור משלם את המחיר פעם אחת מראש, וקונה מהירות וזיהוי שגיאות מוקדם. פירוש משלם קצת בכל הרצה, וקונה את היכולת לשנות ולראות מיד.\n\nשפות מודרניות מטשטשות את זה. ג׳אווהסקריפט מפורשת אבל מהדרת נתיבים חמים תוך כדי ריצה. השאלה המועילה היא אף פעם לא איזה מהם, אלא מתי הטעויות שלי נתפסות — לפני השחרור, או מול משתמש."},
"Runtime": {
 "en": "Your code never runs alone. It runs inside something that gives it memory, a clock, a way to reach the network, and a set of rules. That container is the runtime, and it has a version, a configuration, and its own bugs.\n\nMost environment mysteries are runtime differences. The code is identical; the thing executing it is not. This is the entire reason containers were invented.",
 "he": "הקוד שלך אף פעם לא רץ לבד. הוא רץ בתוך משהו שנותן לו זיכרון, שעון, דרך להגיע לרשת, ואוסף חוקים. המיכל הזה הוא סביבת הריצה, ויש לו גרסה, קונפיגורציה, והבאגים שלו.\n\nרוב התעלומות בין סביבות הן הבדלי סביבת ריצה. הקוד זהה; מה שמריץ אותו לא. זו כל הסיבה שקונטיינרים הומצאו."},
"Terminal / CLI": {
 "en": "A graphical interface shows you the options someone decided you would need. A command line exposes the whole surface and lets you combine pieces that were never designed to meet.\n\nThat composability is why it survived fifty years. A command whose output feeds another command is a program you wrote without opening an editor — and it is repeatable, which a sequence of clicks never is.",
 "he": "ממשק גרפי מציג לך את האפשרויות שמישהו החליט שתצטרך. שורת פקודה חושפת את כל המשטח ומאפשרת לחבר חלקים שמעולם לא תוכננו להיפגש.\n\nהיכולת להרכיב היא הסיבה שהיא שרדה חמישים שנה. פקודה שהפלט שלה מוזן לפקודה אחרת היא תוכנית שכתבת בלי לפתוח עורך — והיא ניתנת לחזרה, מה שרצף לחיצות אף פעם לא."},
"Repository (repo)": {
 "en": "Version control changes what a mistake costs. Without it, every edit is a small bet you cannot unmake; with it, the worst case is losing the last few minutes.\n\nThat changes behaviour more than it changes tooling. People with a safety net try bolder things, delete more aggressively, and rewrite instead of patching around. The history is also a record of intent — why a line exists is often only answerable by finding the commit that added it.",
 "he": "בקרת גרסאות משנה כמה עולה טעות. בלעדיה, כל עריכה היא הימור קטן שאי אפשר לבטל; איתה, המקרה הגרוע הוא לאבד כמה דקות.\n\nזה משנה התנהגות יותר משהוא משנה כלים. אנשים עם רשת ביטחון מנסים דברים נועזים יותר, מוחקים בלי היסוס, ומשכתבים במקום לטלאי מסביב. ההיסטוריה היא גם תיעוד כוונה — למה שורה קיימת היא לרוב שאלה שנענית רק על ידי מציאת הקומיט שהוסיף אותה."},
"Commit / Branch / Merge": {
 "en": "A branch is a cheap parallel universe. You can be wrong in it for a week and it costs nothing, because the main line never saw it.\n\nThe skill is in the size of a commit. One commit should be one idea — small enough that its message is a single sentence, and that reverting it does exactly one thing. Big commits are where bugs hide, because nobody can tell which part of them caused the break.",
 "he": "ענף הוא יקום מקביל זול. אתה יכול לטעות בו שבוע וזה לא עולה כלום, כי הקו הראשי מעולם לא ראה אותו.\n\nהמיומנות היא בגודל של קומיט. קומיט אחד צריך להיות רעיון אחד — קטן מספיק שההודעה שלו היא משפט בודד, ושביטול שלו עושה בדיוק דבר אחד. בקומיטים גדולים באגים מתחבאים, כי אף אחד לא יכול לדעת איזה חלק מהם שבר."},
"Environment": {
 "en": "Environments exist because the same code needs different data and different consequences. A mistake on your laptop costs nothing; the same mistake against the live database costs real money and real trust.\n\nThe discipline is keeping them as identical as possible in everything except data. Every difference between staging and production is a bug waiting for the worst possible moment to reveal itself.",
 "he": "סביבות קיימות כי אותו קוד צריך נתונים שונים והשלכות שונות. טעות על המחשב שלך לא עולה כלום; אותה טעות מול מסד הנתונים החי עולה כסף אמיתי ואמון אמיתי.\n\nהמשמעת היא לשמור אותן זהות ככל האפשר בכל דבר חוץ מנתונים. כל הבדל בין סטייג׳ינג לפרודקשן הוא באג שמחכה לרגע הגרוע ביותר כדי להתגלות."},
"Bug / Stack trace": {
 "en": "A crash is generous. It tells you exactly where it stopped and how it got there. The expensive bugs are the ones that do not crash — they quietly produce a slightly wrong number for six months.\n\nDebugging is not cleverness, it is narrowing. Find the smallest input that still fails, and you have usually found the cause. Most time lost to bugs is time spent reading code instead of shrinking the problem.",
 "he": "קריסה היא נדיבה. היא אומרת לך בדיוק איפה היא עצרה ואיך הגיעה לשם. הבאגים היקרים הם אלה שלא קורסים — הם מייצרים בשקט מספר קצת שגוי במשך חצי שנה.\n\nדיבוג הוא לא חוכמה, הוא צמצום. מצא את הקלט הקטן ביותר שעדיין נכשל, ובדרך כלל מצאת את הסיבה. רוב הזמן שמתבזבז על באגים הוא זמן קריאת קוד במקום כיווץ הבעיה."},

# ---------------- two sides ----------------
"Client": {
 "en": "Everything on the client is a suggestion. The user can open the tools, change a value, and send whatever they like. Hidden buttons are still reachable; disabled fields are still submittable.\n\nSo the client has exactly one security job: none. It shapes the experience and it validates for convenience, but every rule it enforces must also be enforced on the other side, where the user cannot reach.",
 "he": "כל מה שנמצא אצל הלקוח הוא בגדר הצעה. המשתמש יכול לפתוח את הכלים, לשנות ערך, ולשלוח מה שבא לו. כפתורים מוסתרים עדיין נגישים; שדות מנוטרלים עדיין ניתנים לשליחה.\n\nאז ללקוח יש בדיוק תפקיד אבטחה אחד: אף אחד. הוא מעצב את החוויה ומאמת לנוחות, אבל כל חוק שהוא אוכף חייב להיאכף גם בצד השני, שם המשתמש לא מגיע."},
"Server": {
 "en": "The server is the only place you control. It is the boundary between what people want to do and what they are permitted to do, and it is the single source of truth about what actually happened.\n\nThinking of it as just a computer is right and useful. It has a disk that fills up, memory that runs out, and a clock that drifts. Every mysterious production issue eventually reduces to one of those three.",
 "he": "השרת הוא המקום היחיד שאתה שולט בו. הוא הגבול בין מה שאנשים רוצים לעשות לבין מה שמותר להם, והוא מקור האמת היחיד לגבי מה באמת קרה.\n\nלחשוב עליו כעל מחשב רגיל זה נכון ומועיל. יש לו דיסק שמתמלא, זיכרון שנגמר, ושעון שנסחף. כל תקלה מסתורית בפרודקשן מתכנסת בסוף לאחד משלושת אלה."},
"Frontend": {
 "en": "Frontend work is mostly state management wearing a costume. The visual part is the easy half; the hard half is that the screen must stay consistent with data that arrives late, arrives wrong, or never arrives.\n\nLoading, empty, error, and partial are not edge cases — they are four of the five states every screen has. Designs that only show the happy path are the main source of frontend rework.",
 "he": "עבודת פרונטאנד היא בעיקר ניהול מצב בתחפושת. החלק הוויזואלי הוא החצי הקל; החצי הקשה הוא שהמסך חייב להישאר עקבי מול נתונים שמגיעים מאוחר, מגיעים שגויים, או לא מגיעים בכלל.\n\nטעינה, ריק, שגיאה וחלקי הם לא מקרי קצה — הם ארבעה מתוך חמשת המצבים שיש לכל מסך. עיצובים שמציגים רק את המסלול המוצלח הם המקור העיקרי לעבודה חוזרת בפרונט."},
"Backend": {
 "en": "The backend is where the rules live, and a rule only counts if it cannot be bypassed. If the price can be changed by the caller, the price is not a rule — it is a default.\n\nIt is also where time and order become real problems. Two requests arriving at once, a retry after a timeout, a job that ran twice — none of these exist in the UI, and all of them exist here.",
 "he": "הבקאנד הוא המקום שבו החוקים חיים, וחוק נחשב רק אם אי אפשר לעקוף אותו. אם הקורא יכול לשנות את המחיר, המחיר הוא לא חוק — הוא ברירת מחדל.\n\nזה גם המקום שבו זמן וסדר הופכים לבעיות אמיתיות. שתי בקשות שמגיעות יחד, ניסיון חוזר אחרי פסק זמן, משימה שרצה פעמיים — כל אלה לא קיימים בממשק, וכולם קיימים כאן."},
"API": {
 "en": "An API is a promise about shape: these fields, these names, these meanings. Once someone depends on it, the promise is harder to change than the code behind it — that is the entire reason versioning exists.\n\nThe design question is never what data do I have, it is what does the caller need to do. An API that mirrors your database tables forces every consumer to understand your internals, and locks you out of changing them.",
 "he": "API הוא הבטחה לגבי צורה: השדות האלה, השמות האלה, המשמעויות האלה. ברגע שמישהו נשען עליו, קשה יותר לשנות את ההבטחה מאשר את הקוד שמאחוריה — זו כל הסיבה שקיים ניהול גרסאות.\n\nשאלת התכנון היא אף פעם לא אילו נתונים יש לי, אלא מה הקורא צריך לעשות. API שמשקף את טבלאות מסד הנתונים שלך מכריח כל צרכן להבין את הפנימיות שלך, ונועל אותך מלשנות אותן."},
"localhost & port": {
 "en": "A machine has one address but thousands of doors. A port is how the operating system decides which running program a arriving connection belongs to.\n\nThis is why a conflict is always two programs wanting the same door, never a broken network. And it is why exposing a port is a security decision: you are deciding who, from where, may knock.",
 "he": "למכונה יש כתובת אחת אבל אלפי דלתות. פורט הוא הדרך שבה מערכת ההפעלה מחליטה לאיזו תוכנית רצה שייך חיבור שמגיע.\n\nבגלל זה התנגשות היא תמיד שתי תוכניות שרוצות את אותה דלת, אף פעם לא רשת שבורה. ובגלל זה חשיפת פורט היא החלטת אבטחה: אתה מחליט מי, ומאיפה, רשאי לדפוק."},
"DNS": {
 "en": "DNS is a global cache with no reliable way to clear it. Your change is instant at the source and arbitrarily slow everywhere else, because thousands of machines in between are still holding the old answer until its timer expires.\n\nThe practical rule: lower the record TTL a day before a planned move, not during it. Once the move has started, everyone already has the old value and the old timer.",
 "he": "DNS הוא מטמון גלובלי בלי דרך אמינה לנקות אותו. השינוי שלך מיידי במקור ואיטי באופן שרירותי בכל מקום אחר, כי אלפי מכונות בדרך עדיין מחזיקות בתשובה הישנה עד שהטיימר שלהן יפוג.\n\nהכלל המעשי: הורד את ה-TTL של הרשומה יום לפני מעבר מתוכנן, לא תוך כדי. ברגע שהמעבר התחיל, לכולם כבר יש את הערך הישן ואת הטיימר הישן."},
"Full stack": {
 "en": "Full stack is not knowing everything. It is knowing enough of each layer to find which layer is lying to you.\n\nThat diagnostic ability is the actual value. A slow page could be the query, the network, the render, or the cache — and someone who can only see one layer will confidently optimise the wrong one.",
 "he": "פול סטאק זה לא לדעת הכל. זה לדעת מספיק מכל שכבה כדי למצוא איזו שכבה משקרת לך.\n\nיכולת האבחון הזו היא הערך האמיתי. דף איטי יכול להיות השאילתה, הרשת, הרינדור או המטמון — ומי שרואה רק שכבה אחת יבצע אופטימיזציה בטוחה בעצמה לשכבה הלא נכונה."},

# ---------------- http ----------------
"Request / Response": {
 "en": "HTTP is deliberately forgetful. Each exchange is complete in itself; the server does not remember you between them. Everything that feels like memory — being logged in, a shopping cart — is rebuilt on every single request from something you sent along.\n\nThat forgetfulness is what makes the web scalable. Because no request depends on a previous one landing on the same machine, you can put a hundred machines behind one address.",
 "he": "HTTP שכחן בכוונה. כל חילופי דברים שלמים בפני עצמם; השרת לא זוכר אותך ביניהם. כל מה שמרגיש כמו זיכרון — להיות מחובר, עגלת קניות — נבנה מחדש בכל בקשה בודדת ממשהו ששלחת איתה.\n\nהשכחנות הזו היא מה שהופך את הרשת לניתנת להרחבה. מכיוון שאף בקשה לא תלויה בכך שקודמתה נחתה על אותה מכונה, אפשר לשים מאה מכונות מאחורי כתובת אחת."},
"GET": {
 "en": "The promise a GET makes is that reading changes nothing. Everything in the ecosystem is built on that promise: browsers prefetch links, proxies cache responses, crawlers follow every URL they find.\n\nBreak the promise and the ecosystem turns against you. A delete link that responds to GET will eventually be triggered by something that was only trying to be helpful.",
 "he": "ההבטחה ש-GET נותן היא שקריאה לא משנה כלום. כל האקוסיסטם בנוי על ההבטחה הזו: דפדפנים טוענים מראש קישורים, שרתי ביניים שומרים תגובות במטמון, זחלנים עוקבים אחרי כל כתובת שהם מוצאים.\n\nתשבור את ההבטחה והאקוסיסטם יפנה נגדך. קישור מחיקה שמגיב ל-GET יופעל בסוף על ידי משהו שרק ניסה לעזור."},
"POST / PUT / PATCH / DELETE": {
 "en": "The verbs encode two things a URL cannot: intent, and whether repeating is safe. PUT and DELETE can be sent twice with the same outcome; POST cannot, which is why double-submitted forms create duplicate orders.\n\nChoosing correctly costs nothing and buys you correct behaviour from every proxy, client library and retry mechanism between you and the user.",
 "he": "הפעלים מקודדים שני דברים שכתובת לא יכולה: כוונה, והאם חזרה בטוחה. PUT ו-DELETE אפשר לשלוח פעמיים עם אותה תוצאה; POST לא, ובגלל זה טפסים שנשלחים פעמיים יוצרים הזמנות כפולות.\n\nבחירה נכונה לא עולה כלום וקונה לך התנהגות נכונה מכל שרת ביניים, ספריית לקוח ומנגנון ניסיון חוזר שבינך לבין המשתמש."},
"Headers": {
 "en": "Headers are the envelope; the body is the letter. They carry everything about the message that is not the message: who is sending, what format, what language, whether a cached copy is still valid.\n\nBecause they are invisible in normal use, they are where a disproportionate number of bugs hide. When a request works in one tool and fails in another, the difference is almost always a header.",
 "he": "כותרות הן המעטפה; הגוף הוא המכתב. הן נושאות כל מה שקשור להודעה ואינו ההודעה: מי שולח, איזה פורמט, איזו שפה, האם עותק שמור עדיין תקף.\n\nמכיוון שהן בלתי נראות בשימוש רגיל, הן המקום שבו מספר לא פרופורציונלי של באגים מתחבא. כשבקשה עובדת בכלי אחד ונכשלת באחר, ההבדל הוא כמעט תמיד כותרת."},
"Payload / Body": {
 "en": "The body is the only part of a request with no fixed structure — which means it is the part you must never trust. Its size, its shape and its contents are all chosen by whoever is calling you.\n\nSo two limits matter from day one: a maximum size, and a strict check of the shape before any of it reaches your logic. Both are boring, and both prevent whole categories of outage.",
 "he": "הגוף הוא החלק היחיד בבקשה בלי מבנה קבוע — כלומר החלק שלעולם אסור לסמוך עליו. הגודל, הצורה והתוכן נבחרים כולם על ידי מי שקורא לך.\n\nאז שתי מגבלות חשובות מהיום הראשון: גודל מקסימלי, ובדיקה קפדנית של הצורה לפני שמשהו מזה מגיע ללוגיקה שלך. שתיהן משעממות, ושתיהן מונעות קטגוריות שלמות של תקלות."},
"Status codes": {
 "en": "The status code is the machine-readable summary; the body is the human explanation. Getting the code right matters because automated things — retry logic, monitoring, load balancers — read only the code.\n\nThe most consequential distinction is 4xx versus 5xx. A 4xx says do not retry, you sent something wrong. A 5xx says try again, it might work. Returning 200 with an error inside the body defeats every one of those systems.",
 "he": "קוד הסטטוס הוא התקציר שהמכונה קוראת; הגוף הוא ההסבר לאדם. חשוב לדייק בקוד כי דברים אוטומטיים — לוגיקת ניסיון חוזר, ניטור, מאזני עומסים — קוראים רק את הקוד.\n\nההבחנה המשמעותית ביותר היא 4xx מול 5xx. 4xx אומר אל תנסה שוב, שלחת משהו שגוי. 5xx אומר נסה שוב, אולי יעבוד. החזרת 200 עם שגיאה בתוך הגוף מנטרלת כל אחת מהמערכות האלה."},
"JSON": {
 "en": "JSON won because it is the smallest format that is both human-readable and unambiguous to machines. Its limitations are deliberate: no comments, no dates, no distinction between an integer and a decimal.\n\nThose gaps are where integration bugs live. Dates are strings by convention, and two systems that disagree on the convention will silently be years apart.",
 "he": "JSON ניצח כי הוא הפורמט הקטן ביותר שגם קריא לאדם וגם חד-משמעי למכונה. המגבלות שלו מכוונות: אין הערות, אין תאריכים, אין הבחנה בין שלם לעשרוני.\n\nהחורים האלה הם המקום שבו חיים באגי אינטגרציה. תאריכים הם מחרוזות לפי מוסכמה, ושתי מערכות שחלוקות על המוסכמה יהיו בשקט במרחק שנים זו מזו."},
"REST": {
 "en": "REST is a set of expectations, not a specification, and almost nothing called RESTful fully follows it. Its useful core is simple: name things as nouns, act on them with verbs, and keep each request independent.\n\nThat independence is the part that actually matters. It is what lets any server answer any request, which is what lets you scale horizontally at all.",
 "he": "REST הוא אוסף ציפיות, לא מפרט, וכמעט שום דבר שנקרא RESTful לא עוקב אחריו במלואו. הליבה המועילה שלו פשוטה: קרא לדברים בשמות עצם, פעל עליהם עם פעלים, ושמור כל בקשה עצמאית.\n\nהעצמאות הזו היא החלק שבאמת חשוב. היא מה שמאפשר לכל שרת לענות לכל בקשה, וזה מה שמאפשר סקייל אופקי בכלל."},
"Endpoint": {
 "en": "An endpoint is the smallest unit anyone measures, alerts on, or blames. Latency, error rate, and traffic are all per-endpoint numbers — the average across your whole app hides everything interesting.\n\nWhen you design one, you are choosing a granularity. Too coarse and every client over-fetches; too fine and a single screen needs eight round trips.",
 "he": "Endpoint הוא היחידה הקטנה ביותר שמישהו מודד, מתריע עליה או מאשים. זמן תגובה, שיעור שגיאות ותעבורה הם כולם מספרים לכל endpoint — הממוצע על כל האפליקציה מסתיר כל מה שמעניין.\n\nכשאתה מתכנן אחד, אתה בוחר רזולוציה. גס מדי וכל לקוח מושך יותר מדי; עדין מדי ומסך אחד צריך שמונה הלוך-ושוב."},

# ---------------- data ----------------
"Database": {
 "en": "A database is not storage. It is a set of guarantees about storage: that a write either happened completely or not at all, that two simultaneous writers cannot corrupt each other, that a power cut does not lose what it said it saved.\n\nYou can rebuild any single feature of a database yourself. Rebuilding the guarantees is what takes a decade, and it is exactly what fails at the worst moment when you try.",
 "he": "בסיס נתונים הוא לא אחסון. הוא אוסף הבטחות לגבי אחסון: שכתיבה קרתה במלואה או בכלל לא, ששני כותבים במקביל לא יכולים להשחית זה את זה, שהפסקת חשמל לא מאבדת את מה שהוא אמר ששמר.\n\nאפשר לבנות בעצמך כל תכונה בודדת של בסיס נתונים. לבנות מחדש את ההבטחות לוקח עשור, וזה בדיוק מה שנכשל ברגע הגרוע ביותר כשמנסים."},
"SQL vs NoSQL": {
 "en": "The real difference is where the structure is enforced. SQL puts it in one place the database owns; NoSQL spreads it across every piece of code that reads or writes.\n\nFlexible sounds like freedom on day one and like an archaeology dig on day four hundred, when six versions of the same document shape coexist and no one knows which fields are safe to read.",
 "he": "ההבדל האמיתי הוא איפה המבנה נאכף. SQL שם אותו במקום אחד שבסיס הנתונים מחזיק; NoSQL מפזר אותו על פני כל קטע קוד שקורא או כותב.\n\nגמיש נשמע כמו חופש ביום הראשון וכמו חפירה ארכיאולוגית ביום ארבע מאות, כששש גרסאות של אותו מבנה מסמך חיות יחד ואף אחד לא יודע אילו שדות בטוח לקרוא."},
"Schema": {
 "en": "A schema is the only validation that cannot be forgotten. Application checks live in code paths; a database constraint applies to every writer forever, including the migration script someone runs at 2am.\n\nIts second job is communication. A well-named schema tells the next reader what the system believes about the world — which things are optional, which are unique, what must exist before what.",
 "he": "סכמה היא האימות היחיד שאי אפשר לשכוח. בדיקות אפליקציה חיות בנתיבי קוד; אילוץ בבסיס הנתונים חל על כל כותב לנצח, כולל סקריפט המיגרציה שמישהו מריץ בשתיים בלילה.\n\nהתפקיד השני שלה הוא תקשורת. סכמה עם שמות טובים מספרת לקורא הבא מה המערכת מאמינה לגבי העולם — מה אופציונלי, מה ייחודי, מה חייב להתקיים לפני מה."},
"Query": {
 "en": "You describe what you want; the database decides how to get it. That separation is powerful and is also why performance can change overnight without any code change — the planner simply chose differently as the data grew.\n\nThe habit worth building: for anything on a hot path, ask the database to explain its plan. It will tell you whether it is jumping to rows or reading the entire table, and that single fact explains most slowness.",
 "he": "אתה מתאר מה אתה רוצה; בסיס הנתונים מחליט איך להשיג. ההפרדה הזו חזקה, והיא גם הסיבה שביצועים יכולים להשתנות בן לילה בלי שינוי קוד — המתכנן פשוט בחר אחרת ככל שהנתונים גדלו.\n\nההרגל ששווה לפתח: לכל דבר בנתיב חם, בקש מבסיס הנתונים להסביר את התוכנית שלו. הוא יגיד לך אם הוא קופץ לשורות או קורא את כל הטבלה, והעובדה הבודדת הזו מסבירה את רוב האיטיות."},
"Index": {
 "en": "An index trades write speed and disk space for read speed. Every insert must also update every index on that table, so indexing everything makes writes slow and helps nothing in particular.\n\nThe mental model: an index answers one question shape very fast. Look at the filters and sorts you actually run, and index those — not the columns that merely look important.",
 "he": "אינדקס ממיר מהירות כתיבה ומקום בדיסק במהירות קריאה. כל הוספה חייבת לעדכן גם כל אינדקס על הטבלה, אז אינדוקס של הכל מאט כתיבות ולא עוזר לשום דבר מסוים.\n\nהמודל המנטלי: אינדקס עונה על צורת שאלה אחת מהר מאוד. תסתכל על הסינונים והמיונים שאתה באמת מריץ, ואנדקס אותם — לא את העמודות שסתם נראות חשובות."},
"Migration": {
 "en": "A migration turns a schema change from an event into an artifact. It is reviewable, repeatable, and applied identically in every environment and in the same order.\n\nThe discipline that matters most is that migrations are forward-only in practice. Once production has run one, the safe fix is another migration — not editing the old file, which every other environment already applied.",
 "he": "מיגרציה הופכת שינוי סכמה מאירוע לפריט. היא ניתנת לסקירה, לחזרה, ומיושמת באופן זהה בכל סביבה ובאותו סדר.\n\nהמשמעת החשובה ביותר היא שמיגרציות הן קדימה בלבד בפועל. ברגע שפרודקשן הריץ אחת, התיקון הבטוח הוא מיגרציה נוספת — לא עריכת הקובץ הישן, שכל סביבה אחרת כבר הריצה."},
"Transaction": {
 "en": "A transaction is a promise that the outside world will never see a half-finished change. Either all of it is visible or none of it, no matter what crashes in the middle.\n\nThe cost is that other work may wait while you hold one. Long transactions are a classic cause of mysterious stalls: one slow operation inside a transaction can block dozens of unrelated ones.",
 "he": "טרנזקציה היא הבטחה שהעולם החיצוני לעולם לא יראה שינוי שנעשה חצי. או שהכל נראה או ששום דבר לא, לא משנה מה קורס באמצע.\n\nהמחיר הוא שעבודה אחרת עשויה להמתין בזמן שאתה מחזיק אחת. טרנזקציות ארוכות הן סיבה קלאסית לתקיעות מסתוריות: פעולה איטית אחת בתוך טרנזקציה יכולה לחסום עשרות פעולות לא קשורות."},
"ORM": {
 "en": "An ORM hides SQL, and hiding a cost does not remove it. The classic failure is writing a loop that looks like ordinary code and quietly issues one query per iteration.\n\nTreat it as a convenience layer you can always see through. Log the generated SQL in development, and the moment a page feels slow, look at how many queries it actually ran.",
 "he": "ORM מסתיר SQL, והסתרת עלות לא מבטלת אותה. הכשל הקלאסי הוא כתיבת לולאה שנראית כמו קוד רגיל ויורה בשקט שאילתה אחת לכל סיבוב.\n\nתתייחס אליו כאל שכבת נוחות שתמיד אפשר לראות דרכה. תרשום את ה-SQL שנוצר בפיתוח, וברגע שדף מרגיש איטי, תסתכל כמה שאילתות הוא באמת הריץ."},

# ---------------- languages ----------------
"Typed vs untyped": {
 "en": "Types are a proof, checked by a machine, that certain mistakes are not present. They cost you some ceremony when writing and save you a category of error you would otherwise find by accident.\n\nThe cost-benefit shifts with lifespan. For a script you will run once, types are overhead; for anything another person or a future you will edit, they are the cheapest documentation that cannot go stale.",
 "he": "טיפוסים הם הוכחה, שנבדקת על ידי מכונה, שטעויות מסוימות אינן קיימות. הם עולים לך קצת טקס בזמן הכתיבה וחוסכים לך קטגוריה של שגיאות שאחרת היית מוצא במקרה.\n\nהמאזן משתנה עם אורך החיים. לסקריפט שתריץ פעם אחת, טיפוסים הם תקורה; לכל דבר שאדם אחר או אתה בעתיד יערוך, הם התיעוד הזול ביותר שלא יכול להתיישן."},
"Compiled vs interpreted": {
 "en": "This is a question about feedback loops. A compiler gives you a slower loop with more certainty at the end of it; an interpreter gives you an instant loop with less.\n\nFor most products, developer feedback speed matters more than machine speed, right up until the moment it does not. That moment is measurable, not philosophical — profile before you switch languages for performance.",
 "he": "זו שאלה על לולאות משוב. מהדר נותן לך לולאה איטית יותר עם יותר ודאות בסופה; מפרש נותן לך לולאה מיידית עם פחות.\n\nלרוב המוצרים, מהירות המשוב למפתח חשובה יותר ממהירות המכונה, עד בדיוק לרגע שבו זה מתהפך. הרגע הזה ניתן למדידה, לא לפילוסופיה — תמדוד לפני שאתה מחליף שפה בגלל ביצועים."},
"JavaScript / TypeScript": {
 "en": "JavaScript is the only language with a guaranteed runtime on every device on earth. That accident of history, not merit, is why it ended up everywhere including servers.\n\nTypeScript is the correction layer. It changes nothing at runtime and everything at authoring time, which is exactly the trade you want when a machine is generating large amounts of code for you.",
 "he": "ג׳אווהסקריפט היא השפה היחידה עם סביבת ריצה מובטחת בכל מכשיר על פני כדור הארץ. התאונה ההיסטורית הזו, לא הזכות, היא הסיבה שהיא הגיעה לכל מקום כולל שרתים.\n\nTypeScript היא שכבת התיקון. היא לא משנה כלום בזמן ריצה והכל בזמן כתיבה, וזו בדיוק העסקה שאתה רוצה כשמכונה מייצרת עבורך כמויות גדולות של קוד."},
"Python": {
 "en": "Python optimises for the time between having an idea and seeing a result. Its ecosystem, not the language, is the real asset — for most data, scripting or model-adjacent problems, someone has already solved the hard 80 percent.\n\nIts weakness is the same as its strength: so little is enforced that large Python systems depend entirely on the discipline of the people writing them.",
 "he": "פייתון ממוטבת לזמן שבין רעיון לתוצאה. האקוסיסטם שלה, לא השפה, הוא הנכס האמיתי — לרוב בעיות הדאטה, הסקריפטים או המודלים, מישהו כבר פתר את 80 האחוז הקשים.\n\nהחולשה שלה זהה לחוזק שלה: כל כך מעט נאכף, שמערכות פייתון גדולות תלויות לגמרי במשמעת של מי שכותב אותן."},
"Go / Rust / Java / C#": {
 "en": "These exist because at some scale, the cost of a mistake exceeds the cost of ceremony. Each buys safety or speed by asking more of you up front.\n\nYou rarely choose a language on merit alone. You choose the one your team, your libraries and your hiring pool already speak — and that is a legitimate engineering reason, not a compromise.",
 "he": "אלה קיימות כי בסקייל מסוים, מחיר הטעות עולה על מחיר הטקס. כל אחת קונה בטיחות או מהירות בכך שהיא דורשת ממך יותר מראש.\n\nלעיתים רחוקות בוחרים שפה לפי הזכות שלה בלבד. בוחרים את זו שהצוות, הספריות ושוק הגיוס שלך כבר מדברים — וזו סיבה הנדסית לגיטימית, לא פשרה."},
"Package manager": {
 "en": "A package manager solves a problem that sounds trivial and is not: making the same set of code appear on two different machines, including the dependencies of your dependencies.\n\nThe lock file is the solution. It records exact versions of the entire tree, so a build today and a build in a year produce the same thing. Without it, your build is a function of what the internet felt like that morning.",
 "he": "מנהל חבילות פותר בעיה שנשמעת טריוויאלית ואינה: לגרום לאותו אוסף קוד להופיע על שתי מכונות שונות, כולל התלויות של התלויות שלך.\n\nקובץ ה-lock הוא הפתרון. הוא רושם גרסאות מדויקות של כל העץ, כך שבנייה היום ובנייה בעוד שנה מייצרות את אותו דבר. בלעדיו, הבילד שלך הוא פונקציה של מה שהאינטרנט הרגיש באותו בוקר."},
"Dependency": {
 "en": "Adding a dependency is outsourcing a decision to a stranger, permanently. You inherit their bugs, their security holes, their breaking changes and their decision to stop maintaining it.\n\nThe test is not can this library do it, it is would I rather own this code or own this relationship. For something you could write in twenty lines, owning the code is almost always cheaper.",
 "he": "הוספת תלות היא הוצאת החלטה החוצה לזר, לצמיתות. אתה יורש את הבאגים שלו, חורי האבטחה שלו, השינויים השוברים שלו וההחלטה שלו להפסיק לתחזק.\n\nהמבחן הוא לא האם הספרייה הזו יכולה, אלא האם אני מעדיף להחזיק את הקוד הזה או את הקשר הזה. למשהו שאפשר לכתוב בעשרים שורות, להחזיק את הקוד כמעט תמיד זול יותר."},
"Framework vs library": {
 "en": "A framework makes decisions for you, which is enormous leverage when its decisions match your problem and a permanent tax when they do not.\n\nThe honest way to choose: look at an application built with it that is three years old and much bigger than yours. That is what you are signing up for, not the tutorial.",
 "he": "פריימוורק מקבל החלטות במקומך, וזה מנוף עצום כשההחלטות שלו תואמות לבעיה שלך ומס קבוע כשלא.\n\nהדרך הכנה לבחור: תסתכל על אפליקציה שנבנתה איתו, בת שלוש שנים והרבה יותר גדולה משלך. זה מה שאתה חותם עליו, לא המדריך."},

# ---------------- memory ----------------
"RAM vs disk": {
 "en": "There is a hierarchy, and each step down is roughly a thousand times slower and a thousand times more permanent: processor cache, RAM, SSD, network, another continent.\n\nAlmost all performance work is moving data up this hierarchy, and almost all data-loss incidents are assuming something was one level lower than it really was.",
 "he": "יש היררכיה, וכל שלב למטה איטי בערך פי אלף וקבוע פי אלף: מטמון המעבד, RAM, SSD, רשת, יבשת אחרת.\n\nכמעט כל עבודת ביצועים היא הזזת נתונים למעלה בהיררכיה הזו, וכמעט כל אירוע אובדן נתונים הוא הנחה שמשהו היה רמה אחת נמוך יותר ממה שהיה באמת."},
"Stack & heap": {
 "en": "The stack is automatic because it is strictly ordered: the last thing in is the first thing out, so the machine always knows when something can be discarded. The heap has no such order, which is why it needs either a garbage collector or your attention.\n\nThis is the root of the two most famous crashes: exhausting the ordered space by recursing forever, or exhausting the unordered one by holding on to too much.",
 "he": "המחסנית אוטומטית כי היא מסודרת בקפדנות: הדבר האחרון שנכנס הוא הראשון שיוצא, אז המכונה תמיד יודעת מתי אפשר לזרוק משהו. לערימה אין סדר כזה, ובגלל זה היא צריכה או אוסף זבל או את תשומת לבך.\n\nזה השורש של שתי הקריסות המפורסמות: מיצוי המרחב המסודר על ידי רקורסיה אינסופית, או מיצוי הלא-מסודר על ידי החזקה של יותר מדי."},
"Garbage collection": {
 "en": "Automatic memory management trades a class of catastrophic bugs for a class of timing surprises. You will never free memory twice; you will occasionally pause at an inconvenient moment.\n\nFor most applications that is an excellent trade. It stops being one only when consistent millisecond-level response times matter more than developer time — which is rarer than people assume.",
 "he": "ניהול זיכרון אוטומטי ממיר קטגוריה של באגים קטסטרופליים בקטגוריה של הפתעות תזמון. לעולם לא תשחרר זיכרון פעמיים; מדי פעם תיעצר ברגע לא נוח.\n\nלרוב היישומים זו עסקה מצוינת. היא מפסיקה להיות כזו רק כשזמני תגובה עקביים ברמת המילישנייה חשובים יותר מזמן מפתחים — וזה נדיר יותר משנוטים להניח."},
"Memory leak": {
 "en": "A leak is not memory escaping. It is memory you are still technically holding on to, which means the collector is behaving correctly — the bug is in what your code still references.\n\nThe usual suspects are collections that only ever grow: a cache with no limit, an array of listeners nobody removes, a map keyed by user id that outlives the users.",
 "he": "דליפה היא לא זיכרון שבורח. זה זיכרון שאתה עדיין טכנית מחזיק בו, כלומר האוסף מתנהג נכון — הבאג הוא במה שהקוד שלך עדיין מפנה אליו.\n\nהחשודים הרגילים הם אוספים שרק גדלים: מטמון בלי מגבלה, מערך מאזינים שאף אחד לא מסיר, מפה לפי מזהה משתמש ששורדת את המשתמשים."},
"Latency vs throughput": {
 "en": "A highway can be wide or fast, and widening it does not shorten anyone's trip. Batching, queuing and parallelism all raise throughput by making individual items wait.\n\nDecide which one your user experiences. A person waiting for a page cares only about latency; a nightly job processing ten million rows cares only about throughput.",
 "he": "כביש יכול להיות רחב או מהיר, והרחבה שלו לא מקצרת לאף אחד את הנסיעה. אצוות, תורים ומקביליות מעלים תפוקה בכך שהם גורמים לפריטים בודדים להמתין.\n\nתחליט מה מהם המשתמש שלך חווה. אדם שממתין לדף אכפת לו רק מזמן תגובה; משימה לילית שמעבדת עשרה מיליון שורות אכפת לה רק מתפוקה."},
"Big-O": {
 "en": "Big-O ignores constants deliberately, because at small sizes everything is fast and the constants are all that matter — while at large sizes the shape of the growth is all that matters.\n\nIts practical use is prediction. It lets you answer what happens at a hundred times this data without running the experiment, which is the only way to catch the problem before your users do.",
 "he": "Big-O מתעלם מקבועים בכוונה, כי בגדלים קטנים הכל מהיר והקבועים הם כל מה שחשוב — ואילו בגדלים גדולים צורת הגדילה היא כל מה שחשוב.\n\nהשימוש המעשי שלו הוא חיזוי. הוא מאפשר לך לענות מה יקרה בפי מאה מהנתונים האלה בלי להריץ את הניסוי, וזו הדרך היחידה לתפוס את הבעיה לפני המשתמשים."},
"Blocking vs async": {
 "en": "Waiting is not work. Async exists so that a program waiting for a disk or a network can spend that time serving someone else instead of standing still.\n\nThe mental shift is that your code no longer runs top to bottom in one unbroken line. Things happen in an order you did not write, and errors can surface far from where they started — which is the real learning curve, not the syntax.",
 "he": "המתנה היא לא עבודה. אסינכרוניות קיימת כדי שתוכנית שממתינה לדיסק או לרשת תוכל לבלות את הזמן הזה בשירות מישהו אחר במקום לעמוד.\n\nהשינוי המנטלי הוא שהקוד שלך כבר לא רץ מלמעלה למטה בקו אחד רציף. דברים קורים בסדר שלא כתבת, ושגיאות יכולות לצוץ רחוק מהמקום שבו התחילו — וזו עקומת הלמידה האמיתית, לא התחביר."},
"Race condition": {
 "en": "A race is a bug in your assumptions about time. Your code reads a value, decides something, and writes — and between the read and the write, reality changed.\n\nRetrying makes races more likely, not less. The fixes are structural: let the database decide with a constraint or a transaction, or design the operation so that doing it twice is harmless.",
 "he": "מירוץ הוא באג בהנחות שלך לגבי זמן. הקוד שלך קורא ערך, מחליט משהו, וכותב — ובין הקריאה לכתיבה, המציאות השתנתה.\n\nניסיון חוזר הופך מירוצים לסבירים יותר, לא פחות. התיקונים מבניים: תן לבסיס הנתונים להחליט עם אילוץ או טרנזקציה, או תכנן את הפעולה כך שעשייה כפולה שלה אינה מזיקה."},

# ---------------- cache ----------------
"Cache": {
 "en": "Every cache is a bet that the past predicts the future, and a deliberate acceptance that some users will see slightly old data.\n\nBefore adding one, be explicit about two things: how stale is acceptable here, and what breaks if a user sees the previous value. If the answer to the second is something serious, you do not want a cache, you want a faster query.",
 "he": "כל מטמון הוא הימור שהעבר מנבא את העתיד, וקבלה מכוונת של כך שחלק מהמשתמשים יראו נתונים קצת ישנים.\n\nלפני שמוסיפים אחד, תהיה מפורש לגבי שני דברים: כמה ישן מקובל כאן, ומה נשבר אם משתמש רואה את הערך הקודם. אם התשובה לשני היא משהו רציני, אתה לא רוצה מטמון, אתה רוצה שאילתה מהירה יותר."},
"Hit / Miss": {
 "en": "A cache only helps if the same things are requested repeatedly. If every request is unique, you have added a lookup, a write and a memory cost, and gained nothing.\n\nSo measure before and after. A hit rate below roughly half usually means the key is wrong — too specific, including something that varies per user or per request.",
 "he": "מטמון עוזר רק אם מבקשים את אותם דברים שוב ושוב. אם כל בקשה ייחודית, הוספת חיפוש, כתיבה ועלות זיכרון, ולא הרווחת כלום.\n\nאז תמדוד לפני ואחרי. שיעור פגיעות מתחת לחצי בערך אומר בדרך כלל שהמפתח שגוי — ספציפי מדי, כולל משהו שמשתנה לכל משתמש או לכל בקשה."},
"TTL": {
 "en": "A TTL converts correctness into a deadline. It is a promise that wrongness is bounded — this data may be stale, but never by more than sixty seconds.\n\nThat bound is why TTL is usually the better tool than precise invalidation. It is simple, it recovers automatically from every failure mode, and it requires no coordination between the systems that write and the systems that read.",
 "he": "TTL ממיר נכונות למועד אחרון. זו הבטחה שהשגיאה חסומה — הנתון הזה עשוי להיות ישן, אבל אף פעם לא ביותר משישים שניות.\n\nהחסם הזה הוא הסיבה ש-TTL הוא בדרך כלל כלי טוב יותר מביטול תוקף מדויק. הוא פשוט, הוא מתאושש אוטומטית מכל מצב כשל, והוא לא דורש תיאום בין המערכות שכותבות למערכות שקוראות."},
"Invalidation": {
 "en": "Invalidation is hard because it requires every writer to know about every cache, forever, including the ones added after they were written.\n\nThat coupling is the real cost. Each new cache makes every future write path slightly more dangerous, and the failure is silent — nobody gets an error, users just see the wrong thing.",
 "he": "ביטול תוקף קשה כי הוא דורש שכל כותב יידע על כל מטמון, לנצח, כולל אלה שנוספו אחריו.\n\nהצימוד הזה הוא המחיר האמיתי. כל מטמון חדש הופך כל נתיב כתיבה עתידי למסוכן קצת יותר, והכשל שקט — אף אחד לא מקבל שגיאה, משתמשים פשוט רואים את הדבר הלא נכון."},
"Browser cache": {
 "en": "The browser cache is the one you control least and affects users most. You cannot reach into someone's machine and clear it.\n\nThe industry answer is to make the filename change when the content changes. A new name is a new file, so there is nothing to invalidate — the old copy simply stops being requested.",
 "he": "מטמון הדפדפן הוא זה שאתה שולט בו הכי פחות ומשפיע על משתמשים הכי הרבה. אתה לא יכול להיכנס למכונה של מישהו ולנקות אותו.\n\nהתשובה של התעשייה היא לגרום לשם הקובץ להשתנות כשהתוכן משתנה. שם חדש הוא קובץ חדש, אז אין מה לבטל — פשוט מפסיקים לבקש את העותק הישן."},
"CDN": {
 "en": "Distance is the one latency you cannot optimise away in code, because it is bounded by physics. A CDN attacks it by moving the copy, not the request.\n\nIts underrated second job is absorbing load. Traffic that never reaches your servers cannot overwhelm them, which is why a CDN in front of static files is the cheapest resilience you can buy.",
 "he": "מרחק הוא זמן התגובה היחיד שאי אפשר לייעל בקוד, כי הוא חסום על ידי הפיזיקה. CDN תוקף אותו על ידי הזזת העותק, לא הבקשה.\n\nהתפקיד השני שלו, שלא מעריכים מספיק, הוא ספיגת עומס. תעבורה שלא מגיעה לשרתים שלך לא יכולה להציף אותם, ולכן CDN לפני קבצים סטטיים הוא החוסן הזול ביותר שאפשר לקנות."},
"Redis / in-memory store": {
 "en": "The moment you run more than one server, anything held in one process becomes invisible to the others. A shared in-memory store is the fix: fast like local memory, visible to everyone.\n\nIt is also the natural home for anything short-lived and shared — rate limit counters, session data, locks, job queues. Its weakness is exactly its strength: it is memory, so plan for it losing everything.",
 "he": "ברגע שאתה מריץ יותר משרת אחד, כל מה שמוחזק בתהליך אחד הופך בלתי נראה לאחרים. אחסון משותף בזיכרון הוא התיקון: מהיר כמו זיכרון מקומי, נראה לכולם.\n\nהוא גם הבית הטבעי לכל דבר קצר-חיים ומשותף — מוני הגבלת קצב, נתוני סשן, נעילות, תורי משימות. החולשה שלו היא בדיוק החוזק שלו: זה זיכרון, אז תתכנן לכך שהוא יאבד הכל."},

# ---------------- auth ----------------
"Authentication vs Authorization": {
 "en": "These fail differently. Bad authentication lets the wrong person in; bad authorization lets the right person do the wrong thing — and the second is far more common in real breaches.\n\nThe usual hole is checking permission where the button is drawn instead of where the action happens. If the check lives only in the UI, the action is open to anyone who sends the request directly.",
 "he": "אלה נכשלים אחרת. אימות גרוע מכניס את האדם הלא נכון; הרשאה גרועה נותנת לאדם הנכון לעשות את הדבר הלא נכון — והשני הרבה יותר נפוץ בפריצות אמיתיות.\n\nהחור הרגיל הוא בדיקת הרשאה במקום שבו מצויר הכפתור במקום במקום שבו הפעולה קורית. אם הבדיקה חיה רק בממשק, הפעולה פתוחה לכל מי ששולח את הבקשה ישירות."},
"Session & cookie": {
 "en": "A session means the server holds the truth and hands out a reference to it. That makes revoking access trivial — delete the session and the reference is worthless immediately.\n\nThe cost is that every server must be able to see that session store, which is one more shared dependency. This is the central trade-off against tokens.",
 "he": "סשן אומר שהשרת מחזיק באמת ומחלק הפניה אליה. זה הופך ביטול גישה לטריוויאלי — מוחקים את הסשן וההפניה חסרת ערך מיידית.\n\nהמחיר הוא שכל שרת חייב לראות את מאגר הסשנים, וזו עוד תלות משותפת. זו ההתלבטות המרכזית מול טוקנים."},
"Token / JWT": {
 "en": "A token moves the truth into the message itself, so any server can verify it alone. That independence is the whole appeal, and it comes with one hard consequence: you cannot un-issue it.\n\nA stolen token stays valid until it expires. That is why short lifetimes plus a refresh mechanism is the standard pattern — you are trading convenience for a bounded window of damage.",
 "he": "טוקן מעביר את האמת לתוך ההודעה עצמה, כך שכל שרת יכול לאמת אותו לבד. העצמאות הזו היא כל הקסם, והיא מגיעה עם השלכה קשה אחת: אי אפשר לבטל הנפקה.\n\nטוקן גנוב נשאר תקף עד שהוא פג. בגלל זה חיים קצרים בתוספת מנגנון רענון הם הדפוס הסטנדרטי — אתה ממיר נוחות בחלון נזק חסום."},
"OAuth": {
 "en": "OAuth is delegation. You are not receiving a password, you are receiving a statement from a provider the user already trusts, saying this person is who they claim to be.\n\nThe security win is that the most dangerous thing you could hold, you never hold. The cost is a dependency: if that provider is down or bans the user, your login is down too.",
 "he": "OAuth הוא האצלה. אתה לא מקבל סיסמה, אתה מקבל הצהרה מספק שהמשתמש כבר סומך עליו, שאומרת שהאדם הזה הוא מי שהוא טוען.\n\nהרווח האבטחתי הוא שהדבר המסוכן ביותר שיכולת להחזיק, אתה לעולם לא מחזיק. המחיר הוא תלות: אם הספק הזה נופל או חוסם את המשתמש, ההתחברות שלך נופלת איתו."},
"Hashing vs encryption": {
 "en": "Encryption answers what did this say. Hashing answers is this the same thing, without ever being able to answer the first question.\n\nPassword hashing adds a deliberate slowness on top. A fast hash is a weakness here, because the attacker's advantage is volume — making each guess take a fraction of a second turns billions of guesses into an impractical number.",
 "he": "הצפנה עונה על מה זה אמר. גיבוב עונה על האם זה אותו דבר, בלי יכולת לענות אי פעם על השאלה הראשונה.\n\nגיבוב סיסמאות מוסיף איטיות מכוונת מעל. גיבוב מהיר הוא חולשה כאן, כי היתרון של התוקף הוא נפח — לגרום לכל ניחוש לקחת שבריר שנייה הופך מיליארדי ניחושים למספר לא מעשי."},
"HTTPS / TLS": {
 "en": "TLS provides three things at once, and people usually remember only the first: nobody can read the traffic, nobody can change it undetected, and you are talking to who you think you are.\n\nThe third is the one certificates are actually about. Encryption to an impostor is perfectly secure and completely useless.",
 "he": "TLS מספק שלושה דברים בבת אחת, ואנשים בדרך כלל זוכרים רק את הראשון: אף אחד לא יכול לקרוא את התעבורה, אף אחד לא יכול לשנות אותה בלי שיבחינו, ואתה מדבר עם מי שאתה חושב.\n\nהשלישי הוא מה שתעודות באמת עוסקות בו. הצפנה למתחזה היא מאובטחת לחלוטין וחסרת תועלת לחלוטין."},
"Environment variables / secrets": {
 "en": "The principle is separation: the code is the same everywhere, the secrets differ per environment and never live in the repository.\n\nTreat any secret that has ever touched Git, a log file, a screenshot or a chat message as public. Rotation is the only real remedy, and building the habit before you need it is what makes an incident boring instead of catastrophic.",
 "he": "העיקרון הוא הפרדה: הקוד זהה בכל מקום, הסודות שונים לכל סביבה ואף פעם לא חיים בריפוזיטורי.\n\nתתייחס לכל סוד שאי פעם נגע ב-Git, בקובץ לוג, בצילום מסך או בהודעת צ׳אט כאל ציבורי. החלפה היא התרופה האמיתית היחידה, ופיתוח ההרגל לפני שצריך אותו הוא מה שהופך אירוע למשעמם במקום לקטסטרופה."},
"CORS": {
 "en": "CORS protects users from their own browsers. Because a browser automatically attaches your cookies to requests, any site you visit could otherwise act as you on any site you are logged into.\n\nSo the rule is enforced by the browser, on behalf of the user, against the page. Understanding that explains why you cannot fix it in your frontend code — the frontend is the thing being restricted.",
 "he": "CORS מגן על משתמשים מהדפדפנים שלהם. מכיוון שדפדפן מצרף אוטומטית את העוגיות שלך לבקשות, כל אתר שתבקר בו יוכל אחרת לפעול בשמך בכל אתר שאתה מחובר אליו.\n\nאז החוק נאכף על ידי הדפדפן, בשם המשתמש, נגד הדף. הבנת זה מסבירה למה אי אפשר לתקן את זה בקוד הפרונט — הפרונט הוא הדבר שמוגבל."},
"Injection & validation": {
 "en": "Every injection bug is the same bug: data crossed a boundary and was treated as instructions. SQL, shell commands, HTML and now AI prompts all share this shape.\n\nThe structural fix is never cleverer escaping. It is keeping data and instructions in separate channels — parameters instead of string building — so the question of what counts as an instruction never arises.",
 "he": "כל באג הזרקה הוא אותו באג: נתונים חצו גבול וטופלו כהוראות. SQL, פקודות מעטפת, HTML ועכשיו גם פרומפטים ל-AI חולקים את אותה צורה.\n\nהתיקון המבני הוא אף פעם לא בריחה חכמה יותר. זו הפרדה של נתונים והוראות לערוצים נפרדים — פרמטרים במקום בניית מחרוזות — כך שהשאלה מה נחשב הוראה לא עולה בכלל."},

# ---------------- cloud ----------------
"The cloud": {
 "en": "The cloud converts capital expense into operating expense, and hardware decisions into software ones. You can create a database at three in the morning without asking anyone.\n\nThe hidden cost is that everything is now a recurring bill and everything is now a permission. Forgotten resources keep charging, and a misconfigured permission is a breach — both are failure modes that simply did not exist with a server in a cupboard.",
 "he": "הענן ממיר הוצאה הונית בהוצאה תפעולית, והחלטות חומרה בהחלטות תוכנה. אתה יכול ליצור בסיס נתונים בשלוש לפנות בוקר בלי לשאול אף אחד.\n\nהעלות הנסתרת היא שהכל עכשיו חשבון חוזר והכל עכשיו הרשאה. משאבים שנשכחו ממשיכים לחייב, והרשאה שגויה היא פריצה — שני מצבי כשל שפשוט לא היו קיימים עם שרת בארון."},
"AWS / Azure / GCP": {
 "en": "All three sell the same primitives: compute, storage, network, database, identity. The differences are naming, pricing shape and which managed services are genuinely good.\n\nLearn the primitives, not the provider. Someone who understands what a load balancer, a subnet and an IAM role do can find them in any of the three in an afternoon.",
 "he": "שלושתם מוכרים את אותם רכיבי בסיס: חישוב, אחסון, רשת, בסיס נתונים, זהות. ההבדלים הם שמות, צורת תמחור ואילו שירותים מנוהלים באמת טובים.\n\nתלמד את רכיבי הבסיס, לא את הספק. מי שמבין מה עושים מאזן עומסים, תת-רשת ותפקיד IAM ימצא אותם בכל אחד מהשלושה בצהריים אחד."},
"S3 / object storage": {
 "en": "Object storage gives up the things a filesystem promises — directories, partial edits, locking — and gets back near-infinite capacity, durability, and a URL for every item.\n\nThinking of it as a bucket of immutable blobs rather than a folder is what makes the design decisions obvious: you replace an object, you do not edit it.",
 "he": "אחסון אובייקטים מוותר על מה שמערכת קבצים מבטיחה — תיקיות, עריכות חלקיות, נעילה — ומקבל בתמורה קיבולת כמעט אינסופית, עמידות, וכתובת לכל פריט.\n\nלחשוב עליו כעל דלי של גושים בלתי-משתנים ולא כעל תיקייה הוא מה שהופך את החלטות התכנון לברורות: מחליפים אובייקט, לא עורכים אותו."},
"EC2 / VM vs Lambda / serverless": {
 "en": "The question is who owns the idle time. With a VM you rent the machine and the idle is yours to pay for; with serverless the provider owns it and you pay per invocation.\n\nThat makes serverless excellent for spiky, unpredictable work and expensive for steady high traffic. The other cost is the cold start — the first request after a quiet period waits for a runtime to exist.",
 "he": "השאלה היא למי שייך זמן הסרק. עם מכונה וירטואלית אתה שוכר את המכונה וזמן הסרק הוא שלך לשלם עליו; עם סרברלס הספק מחזיק בו ואתה משלם לכל הפעלה.\n\nזה הופך סרברלס למצוין לעבודה קופצנית ובלתי צפויה ויקר לתעבורה גבוהה וקבועה. העלות האחרת היא ה-cold start — הבקשה הראשונה אחרי תקופה שקטה ממתינה שסביבת ריצה תיווצר."},
"Container / Docker": {
 "en": "A container is a reproducible description of an environment, kept in version control next to the code it runs. That is the actual innovation — not isolation, which existed before, but the fact that the environment became a file you can review.\n\nIt also makes servers disposable. If any machine can run the image, replacing a sick one is routine rather than an incident.",
 "he": "קונטיינר הוא תיאור סביבה שניתן לשחזור, נשמר בבקרת גרסאות ליד הקוד שהוא מריץ. זו החדשנות האמיתית — לא בידוד, שהיה קיים קודם, אלא העובדה שהסביבה הפכה לקובץ שאפשר לסקור.\n\nזה גם הופך שרתים לחד-פעמיים. אם כל מכונה יכולה להריץ את הדמות, החלפת מכונה חולה היא שגרה ולא אירוע."},
"Deploy": {
 "en": "Deployment is a risk-management problem disguised as a technical one. The goal is not never breaking; it is making breakage small, visible and quick to undo.\n\nEverything good in this area follows from that: small releases, a way to roll back, and shipping to a fraction of users first. The question to ask of any deploy setup is how fast can we undo this, not how fast can we ship.",
 "he": "פריסה היא בעיית ניהול סיכונים בתחפושת של בעיה טכנית. המטרה היא לא אף פעם לא לשבור; היא להפוך שבירה לקטנה, נראית ומהירה לביטול.\n\nכל מה שטוב בתחום נובע מזה: שחרורים קטנים, דרך לחזור אחורה, ושליחה לחלק מהמשתמשים קודם. השאלה שצריך לשאול על כל מערך פריסה היא כמה מהר אפשר לבטל, לא כמה מהר אפשר לשחרר."},
"CI/CD": {
 "en": "CI is a machine that disagrees with you on a schedule. Its value is not automation, it is that the checks are unskippable and identical for everyone.\n\nThe pipeline is also the honest definition of done in a team. Whatever it does not check, nobody checks — so what you choose to put in it is a statement about what you actually care about.",
 "he": "CI היא מכונה שחולקת עליך לפי לוח זמנים. הערך שלה הוא לא אוטומציה, אלא שהבדיקות בלתי ניתנות לדילוג וזהות לכולם.\n\nהפייפליין הוא גם ההגדרה הכנה של גמור בצוות. מה שהוא לא בודק, אף אחד לא בודק — אז מה שאתה בוחר לשים בו הוא הצהרה על מה באמת אכפת לך."},
"Logs & monitoring": {
 "en": "You cannot debug what you cannot observe, and production is the one place you cannot attach a debugger. Logs are therefore the only evidence you will ever have about what really happened.\n\nThe useful discipline is logging decisions, not events. Not started processing but chose path B because the value was 47 — the second one answers the question you will actually be asking at midnight.",
 "he": "אי אפשר לדבג את מה שאי אפשר לצפות בו, ופרודקשן הוא המקום היחיד שאי אפשר לחבר אליו דיבאגר. לכן לוגים הם הראיה היחידה שתהיה לך לגבי מה באמת קרה.\n\nהמשמעת המועילה היא לתעד החלטות, לא אירועים. לא התחיל עיבוד אלא בחר בנתיב ב׳ כי הערך היה 47 — השני עונה על השאלה שבאמת תשאל בחצות."},

# ---------------- scale ----------------
"Scaling up vs out": {
 "en": "Scaling up is buying your way out with no code changes, and it works remarkably well for longer than most people expect. It ends at a hard ceiling, and the last steps before the ceiling are disproportionately expensive.\n\nScaling out has no ceiling but demands a property from your code: that no request depends on which machine handles it. Earning that property is the real work, and it is cheaper to do early than to retrofit.",
 "he": "סקייל אנכי הוא לקנות את דרכך החוצה בלי שינויי קוד, וזה עובד טוב להפליא לאורך זמן רב יותר ממה שרוב האנשים מצפים. הוא נגמר בתקרה קשיחה, והצעדים האחרונים לפני התקרה יקרים באופן לא פרופורציונלי.\n\nלסקייל אופקי אין תקרה אבל הוא דורש תכונה מהקוד שלך: שאף בקשה לא תלויה באיזו מכונה מטפלת בה. להשיג את התכונה הזו היא העבודה האמיתית, וזול יותר לעשות את זה מוקדם מאשר להתאים בדיעבד."},
"Load balancer": {
 "en": "A load balancer turns many machines into one address, and quietly becomes the place where several important decisions live: which machines are healthy, how connections are distributed, where TLS terminates.\n\nIts health check is the most underrated setting in most systems. If it only checks that the port answers, it will happily keep sending traffic to a server whose database connection died twenty minutes ago.",
 "he": "מאזן עומסים הופך הרבה מכונות לכתובת אחת, ובשקט הופך למקום שבו חיות כמה החלטות חשובות: אילו מכונות בריאות, איך חיבורים מתחלקים, איפה TLS מסתיים.\n\nבדיקת הבריאות שלו היא ההגדרה הכי לא מוערכת ברוב המערכות. אם היא רק בודקת שהפורט עונה, היא תמשיך בשמחה לשלוח תעבורה לשרת שחיבור מסד הנתונים שלו מת לפני עשרים דקות."},
"Stateless": {
 "en": "Stateless does not mean there is no state. It means the state does not live in the process — it lives in the database, the cache, or the request itself.\n\nOnce you have that property, a great deal becomes easy: adding machines, replacing sick ones, deploying without draining connections, recovering from a crash. Almost every operational nicety in modern infrastructure assumes it.",
 "he": "חסר מצב לא אומר שאין מצב. זה אומר שהמצב לא חי בתהליך — הוא חי בבסיס הנתונים, במטמון, או בבקשה עצמה.\n\nברגע שיש לך את התכונה הזו, הרבה דברים הופכים לקלים: הוספת מכונות, החלפת חולות, פריסה בלי לרוקן חיבורים, התאוששות מקריסה. כמעט כל נוחות תפעולית בתשתית מודרנית מניחה אותה."},
"Queue / worker": {
 "en": "A queue separates accepting work from doing it. That single separation gives you three things at once: fast responses, survival of traffic spikes, and retries for free.\n\nThe cost is that you now owe the user an answer later, through some other channel, and you have to handle a job that fails on its ninth attempt. Queues do not remove complexity, they move it somewhere you can see it.",
 "he": "תור מפריד בין קבלת עבודה לבין ביצועה. ההפרדה הבודדת הזו נותנת לך שלושה דברים בבת אחת: תגובות מהירות, שרידות לקפיצות תעבורה, וניסיונות חוזרים בחינם.\n\nהמחיר הוא שאתה חייב עכשיו למשתמש תשובה מאוחר יותר, דרך ערוץ אחר, ואתה צריך לטפל במשימה שנכשלת בניסיון התשיעי שלה. תורים לא מסירים מורכבות, הם מזיזים אותה למקום שאתה יכול לראות."},
"Idempotency": {
 "en": "Distributed systems cannot tell the difference between a request that failed and a response that got lost. So the only safe assumption is that anything may be delivered twice.\n\nIdempotency is how you make that assumption harmless. Usually it means the caller supplies a unique key for the operation, and the server remembers that key — turning a duplicate into a repeated answer instead of a repeated action.",
 "he": "מערכות מבוזרות לא יכולות להבחין בין בקשה שנכשלה לבין תגובה שאבדה. אז ההנחה הבטוחה היחידה היא שכל דבר עלול להימסר פעמיים.\n\nאידמפוטנטיות היא איך שהופכים את ההנחה הזו לבלתי מזיקה. בדרך כלל הקורא מספק מפתח ייחודי לפעולה, והשרת זוכר את המפתח — והופך כפילות לתשובה חוזרת במקום לפעולה חוזרת."},
"Monolith vs microservices": {
 "en": "Splitting a system does not reduce its complexity, it changes its currency. Function calls that could not fail become network calls that can; a single transaction becomes a distributed one you must now coordinate by hand.\n\nMicroservices solve an organisational problem — teams blocking each other on one deploy. If you do not have that problem, you are paying the price without buying anything.",
 "he": "פיצול מערכת לא מקטין את המורכבות שלה, הוא משנה את המטבע שלה. קריאות פונקציה שלא יכלו להיכשל הופכות לקריאות רשת שכן; טרנזקציה אחת הופכת למבוזרת שאתה צריך לתאם ידנית.\n\nמיקרו-שירותים פותרים בעיה ארגונית — צוותים שחוסמים זה את זה על פריסה אחת. אם אין לך את הבעיה הזו, אתה משלם את המחיר בלי לקנות כלום."},
"Rate limiting": {
 "en": "A rate limit is a statement about fairness and survival: no single caller may consume the capacity that belongs to everyone.\n\nIt protects you from more than attackers. The most common thing a rate limit saves you from is one of your own clients stuck in a retry loop, and one of your own integrations with a runaway bill.",
 "he": "הגבלת קצב היא הצהרה על הוגנות והישרדות: אף קורא בודד לא רשאי לצרוך את הקיבולת ששייכת לכולם.\n\nהיא מגנה עליך מיותר מתוקפים. הדבר הנפוץ ביותר שהגבלת קצב מצילה ממנו הוא לקוח שלך עצמך שתקוע בלולאת ניסיונות, ואינטגרציה שלך עם חשבון שברח."},
"Single point of failure": {
 "en": "Redundancy is not free and not always correct. Two of everything doubles cost and adds the hardest problem in the field — keeping copies in agreement.\n\nThe mature version of this is not eliminating every single point, it is knowing where they are and how long recovery takes. An accepted, documented, five-minute failure is engineering; an unknown one is luck.",
 "he": "יתירות אינה חינם ואינה תמיד נכונה. שניים מכל דבר מכפילים עלות ומוסיפים את הבעיה הקשה ביותר בתחום — שמירה על עותקים בהסכמה.\n\nהגרסה הבוגרת של זה היא לא לחסל כל נקודה בודדת, אלא לדעת איפה הן וכמה זמן לוקחת התאוששות. כשל מוסכם, מתועד, בן חמש דקות הוא הנדסה; כשל לא מוכר הוא מזל."},
"Technical debt": {
 "en": "Debt is not bad code. It is a conscious decision to be fast now and pay later — which is often correct, because an unshipped perfect system earns nothing.\n\nIt becomes dangerous when it stops being conscious. Debt nobody wrote down is indistinguishable from design, and the next person will faithfully extend the shortcut believing it was intentional.",
 "he": "חוב הוא לא קוד גרוע. זו החלטה מודעת להיות מהיר עכשיו ולשלם אחר כך — וזה לרוב נכון, כי מערכת מושלמת שלא שוחררה לא מרוויחה כלום.\n\nהוא הופך למסוכן כשהוא מפסיק להיות מודע. חוב שאף אחד לא רשם אינו ניתן להבחנה מתכנון, והאדם הבא יאריך בנאמנות את קיצור הדרך מתוך אמונה שהוא היה מכוון."},
}
